{
  id:'rom', nav:'Roma', name:'Roma', plate:'ATAC', accent:'#A16207', lt:'#FDE047', maps:'Roma',
  lede:'Cuatro días completos y el hotel en el mejor lugar posible, a metros de Piazza Navona. Casi todo el plan entra caminando, así que el orden importa más que el transporte.',
  quick:[
    ['Cuándo','Dom 4 a jue 8 de octubre'],
    ['Dormimos','Four Rivers, junto a Navona'],
    ['Se cena','20:00 a 22:30'],
    ['Octubre','23° / 13°, anochece 18:50'],
    ['Salimos','Jue 8, tren 9:20 de Termini']
  ],
  sections:[
  {s:'El plan, día por día', k:'plan', html:`
      <h3>Domingo 4: llegada y el centro barroco</h3>
      <ul>
        <li>Valijas en el Four Rivers y almuerzo liviano y cerca: <b>Supplizio</b>, a siete minutos, unos supplì de pie y seguimos.</li>
        <li>El circuito clásico, todo en la puerta: <b>Piazza Navona</b> y la fuente de los Cuatro Ríos, que le da nombre al hotel; el <b>Panteón</b>; la <b>Piazza della Minerva</b> con el elefantito de Bernini; y de ahí al río, al <b>Ponte Sant’Angelo</b> y el castillo. Quince minutos de punta a punta.</li>
        <li>Al caer la tarde, <b>Fontana di Trevi</b> y subida a la <b>Fontana delle Naiadi</b> en Piazza della Repubblica. Ahí mismo, Santa Maria degli Angeli, gratis y diez minutos.</li>
        <li>Cena en <b>La Matriciana dal 1870</b>, a pocos minutos de la Repubblica. Reservar sí o sí, y siendo el día del vuelo, hora temprana: 19:30 o 20:00.</li>
      </ul>
      <p><b>Ojo con el Ghetto este día.</b> El domingo 4 cae en Simjá Torá, así que las panaderías y los restaurantes kosher del Portico d’Ottavia, Boccione incluido, lo más probable es que estén cerrados. Por eso el Ghetto queda para el miércoles.</p>
      <h3>Lunes 5: Trevi al amanecer, Trastevere y el Aventino</h3>
      <ul>
        <li><b>Fontana di Trevi</b> a las 7, con el sol saliendo 7:15. Es la única forma de tener la foto sin gente.</li>
        <li><b>Coliseo</b>. Sin entradas, la vuelta por fuera y la vista desde la <b>Via dei Fori Imperiali</b> y la terraza del Campidoglio son gratis. La entrada al Foro se compra aparte, ahí hay chance.</li>
        <li>Mediodía en <b>Trastevere</b>, todo junto: <b>Trapizzino</b>, la <b>Norcineria Iacozzilli</b> para porchetta y embutidos, y <b>Otaleg</b> de postre.</li>
        <li>De Trastevere al <b>Aventino</b>, en este orden para no subir y bajar la colina dos veces: <b>ojo de la cerradura</b> en la Piazza dei Cavalieri di Malta, <b>Giardino degli Aranci</b> a dos minutos para el atardecer, y recién ahí el <b>Roseto Comunale</b> y el <b>Circo Massimo</b>, al pie.</li>
        <li>Cena en el centro, en <b>Renato e Luisa</b>, chico y de reservar con días.</li>
      </ul>
      <h3>Martes 6: el Vaticano y la tarde libre</h3>
      <ul>
        <li>Entrada a las 8:00, el mejor turno. Museos y basílica en unas cuatro horas; a las 12:30 salimos a almorzar por Prati. La logística fina está en la sección del Vaticano.</li>
        <li>Tarde liviana a propósito: Castel Sant’Angelo por dentro está a diez minutos de la basílica, o una siesta corta y salir de nuevo a las cinco.</li>
        <li>Cena en <b>Al 384</b>, la pizzería lejana. La tarde tranquila es el día que mejor aguanta un taxi de ida y vuelta. Reservar temprano.</li>
      </ul>
      <h3>Miércoles 7: Coliseo, Foro y el Ghetto</h3>
      <ul>
        <li>El día que más depende de las entradas. Con Coliseo y Foro, van de mañana temprano: se entra por el Coliseo, se sigue por el Palatino y se sale por el Foro hacia los Fori Imperiali, cuesta abajo.</li>
        <li>Almuerzo en el <b>Ghetto</b>, a quince minutos: sándwich de pastrami del <b>Cappuccino Bar</b> en Via Arenula y la tarta de ricota y visciole de la <b>Pasticceria Boccione</b>, a tres cuadras. Hoy funciona normal.</li>
        <li>Tarde según el cuerpo: <b>Galleria Borghese</b> si hay turno, <b>Basílica de San Clemente</b> con sus tres niveles enterrados, o el <b>Ghetto y la Isola Tiberina</b> con calma.</li>
        <li>Última cena en <b>Roscioli</b>, a ocho minutos del hotel, con parada previa en <b>Dar Filettaro</b> por un filete de bacalao. Cerca y sin trasnochar, que al otro día hay tren.</li>
      </ul>
      <h3>Jueves 8: a Florencia</h3>
      <p>Tren 9:20 desde Termini. Del hotel a Termini, veinte minutos en taxi con valijas: salimos 8:15 y llegamos con margen. La vía se anuncia con poca anticipación, así que mejor esperar dentro de la estación.</p>
    `},

  {s:'Cómo moverse', k:'mover', items:[
    {m:'Four Rivers Hotel, Roma', n:'Dónde dormimos: Four Rivers', d:'A metros de Piazza Navona, que es la mejor ubicación posible para estos cuatro días: el Panteón, Campo de’ Fiori, el Ghetto y el río quedan todos a menos de quince minutos a pie.', t:'mover', tip:'Al hacer el check in, pedir el mapa del barrio y preguntar por dónde entra el taxi, porque la zona de Navona es peatonal y semipeatonal y el auto no siempre llega hasta la puerta.'},
    {nota:1, n:'Del aeropuerto al centro', d:'Desde Fiumicino hay dos opciones sensatas: el <em>Leonardo Express</em>, que va directo a Termini en poco más de media hora, o el taxi, que tiene tarifa fija hasta el centro histórico.', t:'mover', tip:'Con valijas y llegando de un vuelo largo, el taxi vale la pena porque el tren nos deja en Termini y de ahí igual hay que llegar a Navona. La tarifa fija es por viaje y no por persona: hay que confirmar el número antes de subir y tomar solo los taxis blancos de la fila oficial, nunca a alguien que se acerca a ofrecer dentro de la terminal.'},
    {ruta:['Piazza Navona, Roma','Pantheon, Roma','Fontana di Trevi, Roma','Piazza della Repubblica, Roma'], n:'El centro se camina', d:'De Navona al Panteón son 5 minutos, del Panteón a Trevi 8, y de Trevi a la Repubblica 10. Todo el plan del domingo entra caminando sin apuro.', t:'mover', tip:'Es la ciudad donde menos falta hace el transporte. Vamos a usar taxi para el aeropuerto, para Termini y para la cena lejana, y el resto son las piernas.'},
    {nota:1, n:'Metro y bus', d:'El metro tiene tres líneas y no pasa por el centro histórico, porque cada vez que excavan aparecen ruinas. La A y la B se cruzan en Termini y sirven sobre todo para el Vaticano (parada Ottaviano o Cipro) y para el Coliseo.', t:'mover', tip:'El billete sencillo vale 100 minutos con transbordos y se compra en los quioscos, en las máquinas o con contactless directo en el molinete. Los buses de superficie son lentos y en el centro casi nunca convienen.'},
    {nota:1, n:'Taxis: cómo se toman', d:'En Roma el taxi no se para en la calle con la mano: se toma en las paradas, que están señalizadas y hay muchas en el centro, o se pide por app.', t:'mover', tip:'FreeNow e itTaxi funcionan bien y muestran el precio estimado. Para la cena lejana del martes conviene pedirlo por app también para la vuelta, que a la salida de un restaurante de barrio no hay parada cerca.'},
    {nota:1, n:'Las canillas de agua', d:'Roma tiene más de dos mil <em>nasoni</em>, las fuentes de hierro con el chorrito continuo, y el agua es potable y buenísima. Tapando el agujero de abajo con el dedo, el agua sale por un orificio de arriba y se puede tomar directo.', t:'mover', tip:'Una botella recargable ahorra varios euros por día y bastante plástico. Están marcadas en Google Maps buscando "nasone".'},
    {nota:1, n:'Termini, el jueves', d:'Es enorme y confusa, con los andenes 1 al 24 en el cuerpo principal y una zona de andenes cortos al costado. El cartel general anuncia la vía a veces con quince minutos de anticipación.', t:'mover', tip:'Llegar cuarenta minutos antes con valijas. Los trenes de alta velocidad se validan solos con el QR del teléfono, no hay que picar nada. Y ojo con la gente que se ofrece a ayudar con la valija en la escalera: después pide plata.'}
  ]},

  {s:'Sentarse a comer', k:'comer', items:[
    {nota:1, n:'El coperto y el agua', d:'Casi todas las trattorias cobran un coperto por persona, que cubre el pan y el mantel. Tiene que estar avisado en la carta y aparece al final de la cuenta, aunque no toquemos el pan. Si además dice <em>servizio</em>, esa es la propina y ya está cobrada.', t:'comer', tip:'El agua es siempre de botella, <em>naturale</em> o <em>frizzante</em>. El agua de la canilla no se sirve en la mesa, aunque afuera haya nasoni por todos lados.'},
    {nota:1, n:'Cómo está armada la carta', d:'Va en orden: antipasto, primo (la pasta), secondo (la carne o el pescado) y contorno (la guarnición, que se pide y se cobra aparte). Nadie está obligado a pedir los cuatro pasos, y pedir dos cosas entre los dos está bien visto.', t:'comer', tip:'El detalle que descoloca: el primo llega solo, sin nada al lado, y el secondo llega sin guarnición si no la pedimos. No es que se olvidaron.'},
    {nota:1, n:'La cuenta se pide siempre', d:'No la traen sin que la pidan, porque apurar a la mesa es de mala educación. Se pide con un "il conto, per favore". Dividirla en partes iguales es tan normal que tiene nombre propio, <em>pagare alla romana</em>.', t:'comer', tip:'Por ley tienen que aceptar tarjeta y darnos el ticket fiscal, pero en los locales chicos de mostrador conviene llevar algo de efectivo igual.'},
    {nota:1, n:'En el bar se paga antes de pedir', d:'En los bares de café y en muchas heladerías el orden es al revés: primero se paga en la caja diciendo qué queremos, dan un ticket y con ese ticket se pide en la barra. Pararse en la barra sin ticket es la forma más rápida de que nos ignoren.', t:'comer', tip:'En los lugares de comida de calle, en cambio, se pide y se paga en el mismo mostrador. La duda se saca mirando diez segundos qué hace el que está adelante.'},
    {nota:1, n:'Reservar, o llegar cuando abren', d:'Los buenos son de dos tipos: los que no toman reserva y hay que estar en la puerta cuando abren, y los que se reservan con días. En el medio no hay mucho.', t:'comer', tip:'De los nuestros, La Matriciana, Renato e Luisa, Roscioli y Al 384 son de reservar. Los de mostrador son de caer. Y muchas trattorias cierran domingo de noche o lunes entero: conviene confirmar el día de cierre de cada una al reservar.'},
    {nota:1, n:'Los horarios de la cocina', d:'Almuerzo de 12:30 a 15:00 y cena desde las 19:30 o 20:00, con las cocinas trabajando hasta cerca de las 23:00. Entre una cosa y la otra casi todo cierra y a las 17:00 solo queda algún bar.', t:'comer', tip:'Los romanos cenan sobre las 20:30. Sentarse a las 19:30 muchas veces significa conseguir mesa sin reserva en lugares que después se llenan.'},
    {nota:1, n:'Si nos invitan a pasar desde la puerta, seguimos de largo', d:'Alguien parado en la vereda con la carta plastificada en cuatro idiomas y fotos de los platos es, en el centro de Roma, la señal más confiable de que ahí se come mal y se paga caro.', t:'comer', tip:'La otra señal es la carbonara con crema en la foto. Los lugares buenos no salen a la calle a buscar gente.'},
    {nota:1, n:'Las cuatro pastas romanas', d:'Cacio e pepe es queso pecorino y pimienta; gricia suma guanciale, que es cachete de cerdo curado; amatriciana suma tomate a la gricia; y carbonara suma huevo en vez de tomate. Son variaciones de lo mismo y conviene probar más de una.', t:'comer', tip:'Ninguna lleva crema, y la carbonara tampoco lleva panceta ni cebolla. Si en la carta aparece con crema, es un lugar hecho para turistas.'}
  ]},

  {s:'Comer parada: la lista corta', k:'comer', items:[
    {n:'Supplizio', d:'El supplì es la croqueta romana: una bola de arroz al ragú con mozzarella adentro, empanada y frita, que se estira como un hilo de teléfono al abrirla. Acá los hace Arcangelo Dandini, que los llevó a otra categoría sin dejar de cobrarlos como comida de calle.', t:'comer', p:'€', serv:'mostrador', res:'no', a:'Via dei Banchi Vecchi', tip:'Está entre Campo de’ Fiori y el río, a siete minutos del hotel. Es el almuerzo del domingo: se come de pie y seguimos. Además del clásico hay versiones con carbonara o amatriciana adentro.'},
    {m:'Trapizzino Trastevere, Roma', n:'Trapizzino', d:'Un triángulo de pizza bianca abierto y relleno con guisos romanos: pollo alla cacciatora, lengua en salsa verde, albóndigas. Se inventó en el Testaccio y ahora hay varios locales.', t:'comer', p:'€', serv:'mostrador', res:'no', tip:'Dos por persona y una cerveza es un almuerzo completo por poca plata. Los supplì de acá también son de los mejores de la ciudad, así que se puede comparar con los de Supplizio.'},
    {m:'Norcineria Iacozzilli, Trastevere, Roma', n:'Norcineria Iacozzilli', d:'Una norcineria es una charcutería de cerdo, y esta es de las de toda la vida en Trastevere: porchetta cortada al momento, embutidos, quesos y sándwiches armados ahí mismo.', t:'comer', p:'€', serv:'mostrador', res:'no', tip:'La porchetta es cerdo asado entero con hierbas, cortado en fetas gruesas y metido en pan. Se pide por peso o directamente el sándwich, y se come en la calle. Cierran a media tarde.'},
    {n:'Cappuccino Bar', d:'En Via Arenula, a la entrada del Ghetto. El sándwich de pastrami es el motivo para ir, y no es lo que uno espera encontrar en Roma.', t:'comer', p:'€', serv:'mostrador', res:'no', a:'Via Arenula', tip:'Es el almuerzo del miércoles, saliendo del Coliseo. Queda a tres cuadras de Boccione, así que salado y dulce se resuelven en la misma cuadra.'},
    {n:'Dar Filettaro a Santa Barbara', d:'Una placita escondida a media cuadra de Campo de’ Fiori, y un local que hace una sola cosa desde hace décadas: filete de bacalao rebozado y frito, que se come con las manos.', t:'comer', p:'€', serv:'mesa', res:'no', a:'Largo dei Librari 88', tip:'Abre solo de noche. Está a la vuelta de Roscioli, así que el miércoles se puede empezar acá con un filete y una copa de vino blanco y seguir a la cena.'},
    {n:'Antico Forno Roscioli', d:'La panadería de la familia Roscioli, en Via dei Chiavari. Pizza al corte, pan y una vitrina de sándwiches armados con los mismos fiambres y quesos que venden en la charcutería de al lado.', t:'comer', p:'€', serv:'mostrador', res:'cola', a:'Via dei Chiavari', tip:'A mediodía hay cola de oficinistas y avanza rápido. Sirve como plan B de cualquier almuerzo, porque está en el medio de todo.'},
    {n:'Forno Campo de’ Fiori', d:'En la plaza del mercado. La pizza bianca con aceite y sal es el snack romano por excelencia y sale por muy poco.', t:'comer', p:'€', serv:'mostrador', res:'no', tip:'Pedirla "con la mortazza", con mortadela adentro, es como la comen los romanos. Está a cinco minutos del hotel y resuelve cualquier hambre de media tarde.'},
    {n:'Pizzarium Bonci', d:'Junto a los Museos Vaticanos. Pizza al taglio de masa fermentada muchas horas, cortada con tijera y pesada. Gabriele Bonci cambió la forma en que Roma come pizza.', t:'comer', p:'€', serv:'mostrador', res:'no', tip:'Se come de pie en la calle y queda a diez minutos de la salida de los museos. Es la mejor opción para el almuerzo del martes sin alejarse.'}
  ]},

  {s:'Comer sentados', k:'comer', items:[
    {m:'La Matriciana dal 1870, Roma', n:'La Matriciana dal 1870', d:'Un clásico romano con más de un siglo encima, a pocos minutos de la Piazza della Repubblica. Las pastas romanas hechas como corresponde y un salón de los de siempre.', t:'comer', p:'€€', serv:'mesa', res:'si', tip:'Es la cena del domingo, porque cierra el día justo donde lo terminamos. Reservar sí o sí y, siendo el día del vuelo, pedir una hora temprana: 19:30 o 20:00 y a dormir.'},
    {m:'Renato e Luisa, Roma', n:'Renato e Luisa', d:'Cerca de Largo Argentina, chico y siempre lleno. Trattoria de las buenas con algunos platos que se van de lo clásico sin ponerse pretenciosos.', t:'comer', p:'€€', serv:'mesa', res:'si', tip:'Tiene pocas mesas y se reserva con días. Abre solo de noche. Es la cena del lunes, volviendo del Aventino al centro.'},
    {n:'Roscioli Salumeria con Cucina', d:'Mitad charcutería, mitad restaurante, en Via dei Giubbonari. Una de las mejores carbonaras de Roma, una selección de embutidos y quesos enorme y una carta de vinos larguísima.', t:'comer', p:'€€', serv:'mesa', res:'si', a:'Via dei Giubbonari 21', tip:'Reservar. Sentarse en la barra, entre los jamones colgados, es mejor que en el salón. Es la última cena, a ocho minutos del hotel.'},
    {m:'Al 384 Pizzeria con Cucina, Roma', n:'Al 384, la pizzería lejana', d:'Fuera del circuito turístico, que es justamente por lo que vale la pena. Pizza y cocina, con la calma de un lugar de barrio al que va gente del barrio.', t:'comer', p:'€€', serv:'mesa', res:'si', tip:'Reservar temprano, que es chico. Va el martes, que es el día de tarde liviana: taxi de ida y taxi de vuelta pedido por app, porque ahí no hay parada cerca.'},
    {n:'Da Enzo al 29', d:'En Trastevere, trattoria diminuta con los cuatro clásicos romanos impecables: cacio e pepe, carbonara, amatriciana y gricia.', t:'comer', p:'€€', serv:'mesa', res:'cola', tip:'No toman reserva para cenar y la cola empieza antes de que abran. Si el lunes queremos quedarnos a cenar en Trastevere en vez de volver al centro, esta es la alternativa: estar en la puerta a las 19:00 en punto.'},
    {n:'Il Sorpasso', d:'En Prati, a diez minutos del Vaticano. Mitad bar, mitad restaurante, abierto todo el día sin cerrar la cocina, con embutidos, trapizzini y platos del día.', t:'comer', p:'€€', serv:'mesa', res:'conviene', tip:'Justamente porque no cierra a media tarde, es la solución del martes si salimos del Vaticano tarde y con hambre y todo lo demás ya cerró la cocina.'},
    {n:'Armando al Pantheon', d:'A cincuenta metros del Panteón, en manos de la misma familia desde 1961. Cocina romana clásica y sin concesiones al turista, pese a la ubicación.', t:'comer', p:'€€', serv:'mesa', res:'si', w:'https://www.armandoalpantheon.it/', tip:'Reservar con semanas. Es de los pocos lugares buenos que quedan en pleno centro turístico y está a cinco minutos del hotel, así que sirve como reemplazo si alguna reserva se cae.'}
  ]},

  {s:'Café, gelato y dulce', k:'cafe', items:[
    {m:'Pasticceria Boccione, Roma', n:'Pasticceria Boccione', d:'El horno del Ghetto, sin cartel y sin vidriera bonita, con una vitrina y poco más. La tarta de ricota y visciole, que son unas cerezas ácidas, es la que hay que pedir, y la pizza ebraica es la otra.', t:'cafe', p:'€', serv:'mostrador', res:'no', a:'Via del Portico d’Ottavia', tip:'Cierra los sábados y en las fiestas judías, así que el domingo 4 casi seguro está cerrado y por eso lo dejamos para el miércoles. La superficie quemada de la tarta no es un error, es como se hace.'},
    {m:'Otaleg, Via di San Cosimato, Trastevere, Roma', n:'Otaleg', d:'Gelato al revés, que es lo que dice el nombre leído de atrás para adelante. Marco Radicioni cambia la carta todo el tiempo y trabaja los sorbetes de fruta de estación como nadie.', t:'cafe', p:'€', serv:'mostrador', res:'no', tip:'Es el postre del lunes en Trastevere, después de Trapizzino y la norcineria. Está a pocas cuadras de las dos.'},
    {n:"Sant'Eustachio Il Caffè", d:'A dos calles del Panteón. Para muchos, el mejor espresso de Roma. Lo preparan tapando la máquina con un paño para que no se vea el método.', t:'cafe', p:'€', serv:'barra', res:'no', tip:'El "gran caffè" viene ya azucarado por defecto. Si lo queremos sin azúcar, hay que pedirlo <em>senza zucchero</em> al pagar, antes de que lo hagan.'},
    {n:'Tazza d’Oro', d:'Pegado al Panteón, desde 1944. La granita di caffè con panna, café granizado con crema arriba y abajo, es lo que hay que pedir incluso en octubre.', t:'cafe', p:'€', serv:'barra', res:'no', tip:'Está a un minuto del Panteón, así que entra perfecto en el paseo del domingo.'},
    {n:'Giolitti', d:'Heladería de 1900 cerca del Panteón. Gelato clásico y muy bueno, con crema batida gratis por encima si se pide.', t:'cafe', p:'€', serv:'mostrador', res:'no', tip:'Es la más famosa de las buenas y por eso está siempre llena. Se paga primero en la caja y se lleva el ticket al mostrador.'},
    {n:'Fatamorgana', d:'Sabores que no existen en ningún otro lado, todos naturales y sin colorantes: pera con gorgonzola, chocolate con tabaco de Kentucky, ricota con higo. Hay locales en varios barrios.', t:'cafe', p:'€', serv:'mostrador', res:'no', tip:'Si queremos ir a lo seguro igual tiene los clásicos impecables. Siempre hay uno cerca de donde estemos.'},
    {nota:1, n:'Cómo se reconoce un gelato bueno', d:'Si está apilado en montañas brillantes y el pistacho es verde flúor, es industrial y va a estar lleno de aire. El bueno está al ras de la cubeta o tapado, y tiene colores apagados: el pistacho de verdad es marrón grisáceo y la banana es gris, no amarilla.', t:'cafe', tip:'Sirve para toda Italia, así que vale también para Florencia y para San Gimignano. Otra seña: si en octubre tienen sabores de fruta de verano, es que no la usan fresca.'},
    {nota:1, n:'La regla del café', d:'Tomado de pie en la barra cuesta la mitad o menos que sentados en la mesa, y en zonas turísticas la diferencia es de varias veces. La lista con los dos precios está siempre publicada.', t:'cafe', tip:'Y después de las once de la mañana ningún italiano toma cappuccino. Nadie nos va a decir nada, pero es el detalle que delata al turista más rápido que la cámara.'}
  ]},

  {s:'Un trago', k:'coctel', items:[
    {n:'Freni e Frizioni', d:'En Trastevere, un antiguo taller mecánico convertido en bar, con terraza que da al Tíber. El aperitivo incluye buffet con el precio de la bebida.', t:'coctel', p:'€', serv:'barra', res:'no', tip:'El aperitivo va de 19:00 a 22:00 y es de lo mejor que hay en relación precio y diversión. El lunes, si nos quedamos en Trastevere, es la parada obvia antes de cenar.'},
    {n:'Salotto42', d:'En Piazza di Pietra, frente a las columnas del templo de Adriano. Un salón con libros de arte y sillones, y una de las plazas más lindas de Roma para tomar algo.', t:'coctel', p:'€€', serv:'mesa', res:'no', tip:'Está a cinco minutos del hotel. Es el trago tranquilo de cualquier noche, sin planificar nada.'},
    {n:'Drink Kong', d:'En Monti. Estética de Blade Runner con neones y luz baja, y coctelería de las mejores del mundo.', t:'coctel', p:'€€', serv:'mesa', res:'conviene', w:'https://www.drinkkong.com/', tip:'Sobre las 19:00 todavía se consigue lugar y se puede hablar sin gritar. Queda cerca del Coliseo, así que combina con el miércoles.'},
    {n:'Terrazza Borromini', d:'Azotea con vista directa sobre la Piazza Navona y las cúpulas de Borromini. Cara, pero esa vista no la tiene nadie más y está a dos cuadras del hotel.', t:'coctel', p:'€€€', serv:'mesa', res:'conviene', tip:'Ir al atardecer y quedarse una copa. Con el hotel tan cerca, es el lujo más barato de organizar del viaje.'}
  ]},

  {s:'Imprescindibles y dónde sacar la foto', k:'visita', items:[
    {n:'Piazza Navona', d:'La plaza barroca sobre la planta de un estadio romano, con la Fuente de los Cuatro Ríos de Bernini en el medio: el Danubio, el Ganges, el Nilo y el Río de la Plata, uno en cada esquina.', t:'visita', tip:'El del Río de la Plata es el calvo con el brazo levantado y una montaña de monedas al lado. Es literalmente nuestro río, y es la fuente que le da nombre al hotel. La plaza a las 7 de la mañana está vacía y es otra cosa.'},
    {n:'Panteón', d:'El edificio antiguo mejor conservado del mundo y la cúpula de hormigón sin refuerzo más grande que se haya construido, de hace casi dos mil años. El agujero del centro es de verdad un agujero: cuando llueve, llueve adentro.', t:'visita', p:'€', w:'https://www.pantheon.cultura.gov.it/', tip:'Desde 2023 se paga entrada y conviene reservarla online para saltar la fila. Ojo con un detalle: el primer domingo de mes la entrada es gratis, y el 4 de octubre es primer domingo. Gratis pero lleno, así que o vamos apenas abre o volvemos otro día pagando.'},
    {n:'Piazza della Minerva y el elefantito', d:'Detrás del Panteón, un elefante de Bernini cargando un obelisco egipcio, que los romanos llaman el <em>pulcino della Minerva</em>. Y al lado, Santa Maria sopra Minerva, la única iglesia gótica de Roma, con un Cristo de Miguel Ángel y el techo azul con estrellas.', t:'visita', tip:'La iglesia es gratis y casi nadie entra, teniendo el Panteón a treinta metros. Adentro está enterrado Fra Angelico. Diez minutos que valen mucho.'},
    {ruta:["Ponte Sant'Angelo, Roma","Castel Sant'Angelo, Roma","Piazza San Pietro, Roma"], n:'Ponte y Castel Sant’Angelo', d:'El puente de los ángeles de Bernini cruzando al castillo, que fue mausoleo de Adriano, fortaleza papal y cárcel. Desde la terraza de arriba se ve Roma entera y la cúpula de San Pedro de frente.', t:'visita', p:'€', tip:'Por fuera y de tarde es una de las postales de Roma, con la luz pegando en el castillo. Por dentro se hace en una hora y media y la terraza vale la entrada. El pasaje elevado que va del castillo al Vaticano es el que usaban los papas para escaparse.'},
    {n:'Fontana di Trevi', d:'La fuente barroca más grande de Roma, encajada contra la fachada de un palacio en una placita que le queda chica. De día es una masa de gente; a las siete de la mañana está vacía.', t:'visita', tip:'Por eso el lunes arrancamos acá. En horario pico hay control de acceso y filas para bajar hasta el borde. La moneda se tira con la mano derecha por encima del hombro izquierdo, de espaldas a la fuente.'},
    {n:'Fontana delle Naiadi y Santa Maria degli Angeli', d:'La fuente de las ninfas en el centro de la Piazza della Repubblica, que cuando se inauguró en 1901 fue un escándalo. Enfrente, una iglesia que Miguel Ángel armó adentro de las termas de Diocleciano aprovechando los muros romanos.', t:'visita', tip:'La iglesia es gratis y por fuera parece una pared rota, así que casi nadie entra. Adentro está la línea meridiana de bronce en el piso, con el agujero en la bóveda por donde entra el sol al mediodía.'},
    {ruta:['Piazza Trilussa, Roma','Santa Maria in Trastevere, Roma','Piazza di San Cosimato, Roma'], n:'Trastevere a pie', d:'El barrio del otro lado del río, con calles de adoquín, ropa colgada y enredaderas. Santa Maria in Trastevere es de las iglesias más antiguas de Roma y tiene mosaicos dorados del siglo XII.', t:'visita', tip:'Es el recorrido del lunes al mediodía, y de paso pasa por Trapizzino, la norcineria y Otaleg. La plaza de Santa Maria de noche, con la fuente y los escalones llenos de gente, es lo mejor del barrio.'},
    {m:'Piazza dei Cavalieri di Malta, Roma', n:'El ojo de la cerradura', d:'En el portón verde del Priorato de los Caballeros de Malta hay una cerradura, y mirando por ahí se ve la cúpula de San Pedro perfectamente centrada al final de un túnel de árboles recortados. No es casualidad, está diseñado así.', t:'visita', tip:'Es gratis y hay cola, que avanza rápido porque cada uno mira diez segundos. La foto con el celular es difícil porque el agujero es chico: conviene apoyar el lente contra el metal y dejar que enfoque solo.'},
    {m:'Giardino degli Aranci, Roma', n:'Giardino degli Aranci', d:'A dos minutos de la cerradura, un jardín de naranjos amurallado con una terraza que da sobre todo Roma: el Tíber, el Trastevere y las cúpulas hasta el fondo. Es el mejor atardecer de la ciudad y es gratis.', t:'visita', tip:'El lunes hay que estar acá cerca de las 18:30, porque a las 18:50 se pone el sol. Cierra al oscurecer. Si el Roseto está cerrado, esto lo reemplaza con creces.'},
    {n:'Roseto Comunale', d:'El rosedal municipal, en la ladera del Aventino, justo enfrente del Circo Massimo. Fue el cementerio judío de Roma durante siglos y por eso los canteros tienen forma de candelabro visto desde arriba.', t:'visita', tip:'Abre en primavera y suele tener una apertura corta en octubre por la segunda floración, pero no está garantizado. Conviene mirar la web del ayuntamiento antes de bajar. Si está cerrado, no pasa nada: el Giardino degli Aranci está a cinco minutos y es mejor.'},
    {n:'Circo Massimo', d:'El estadio de carreras de carros más grande del imperio, con capacidad para más de cien mil personas. Hoy es un óvalo de pasto enorme y vacío, y hay que imaginarlo.', t:'visita', tip:'Está al pie del Aventino, así que se baja del Roseto directo. Al fondo se ven las ruinas de los palacios del Palatino, que es la mejor vista gratis del Palatino que existe.'},
    {n:'Basílica de San Clemente', d:'Tres edificios apilados: la basílica del siglo XII arriba, una del siglo IV debajo, y abajo del todo una casa romana con un templo de Mitra. Se baja por escaleras y se escucha correr un río subterráneo.', t:'visita', p:'€', tip:'Está a cinco minutos del Coliseo y casi nadie la conoce. Es una opción buenísima para la tarde del miércoles. Los niveles de abajo se pagan aparte y no se pueden fotografiar.'},
    {n:'Galleria Borghese', d:'La mejor colección de esculturas de Bernini que existe, en la villa de la familia Borghese: el Apolo y Dafne, el Rapto de Proserpina con los dedos hundidos en el mármol, el David. Más Caravaggio, Rafael y Tiziano.', t:'visita', p:'€€', w:'https://galleriaborghese.beniculturali.it/', tip:'Solo con reserva previa y turnos de dos horas, con cupo limitado. Si conseguimos entrada, es lo mejor de la tarde del miércoles. Se ve completa en las dos horas del turno sin correr.'},
    {ruta:['Portico d’Ottavia, Roma','Isola Tiberina, Roma','Bocca della Verità, Roma'], n:'El Ghetto y la Isola Tiberina', d:'El barrio judío de Roma, habitado desde hace más de dos mil años, con el Portico d’Ottavia en ruinas en el medio de la calle y la sinagoga a un costado. Desde ahí se cruza a la isla del Tíber, que es una isla en el medio de la ciudad.', t:'visita', tip:'Es el paseo del miércoles después del almuerzo. Las <em>pietre d’inciampo</em>, las placas doradas en el piso con nombres, marcan las casas de los deportados en 1943. Vale la pena mirar el piso.'}
  ]},

  {s:'El Vaticano, martes 8:00', k:'visita', items:[
    {nota:1, n:'Cuánto lleva y cómo ordenar el día', d:'Con nuestro ritmo, ágil y sin quedarnos mucho en cada sala, los Museos Vaticanos se hacen en dos horas y media y la Basílica de San Pedro en una. Con la entrada a las 8:00, a las 12:30 estamos afuera y almorzando.', t:'visita', tip:'El orden correcto es museos primero y basílica después, no al revés: los museos abren temprano y la basílica está abierta todo el día. Al revés se pierde la única hora buena del día.'},
    {nota:1, n:'La entrada a las 8:00 es la buena', d:'Es el primer turno y hace toda la diferencia: la Capilla Sixtina a las 8:30 se puede mirar, y a las 11 es una lata de sardinas donde los guardias gritan cada dos minutos.', t:'visita', tip:'Llegar 7:30 a la puerta de los museos, en Viale Vaticano. La fila de los que tienen entrada es distinta de la de los que no, y hay que buscar el cartel que lo dice: la primera avanza y la otra no. En metro, la parada Cipro queda más cerca de la entrada de los museos que Ottaviano.'},
    {nota:1, n:'El recorrido corto y qué saltarse', d:'Del molinete a la Sixtina hay un camino largo de galerías. Lo que vale la pena en el camino: la Galería de los Candelabros, la de los Tapices y sobre todo la <em>Galería de los Mapas</em>, que son cuarenta metros de mapas de Italia pintados en 1580 con el techo dorado. Después las Estancias de Rafael y ahí sí la Sixtina.', t:'visita', tip:'Se pueden saltar sin culpa el museo egipcio, el etrusco, el Braccio Nuovo y toda la sección de arte moderno. La Pinacoteca es buena y está vacía a las 8, así que si alguna sobra, esa es la que se puede hacer al final si queda cuerpo.'},
    {nota:1, n:'La Capilla Sixtina', d:'No se puede hablar ni sacar fotos, y lo hacen cumplir. Los bancos laterales son pocos y se llenan: si quedan libres a las 8:30, hay que sentarse, porque mirar el techo parado se vuelve incómodo en tres minutos.', t:'visita', tip:'Mirar primero el Juicio Final de la pared del fondo y después el techo de derecha a izquierda, que es el orden en que Miguel Ángel lo pintó. La escena famosa de los dedos está en el medio.'},
    {nota:1, n:'El atajo a San Pedro', d:'Al fondo de la Sixtina, a la derecha, hay una puerta reservada para grupos guiados que sale directo a la basílica y ahorra media hora de caminata y toda la cola de la plaza. Muchas veces dejan pasar y muchas veces no, según el guardia.', t:'visita', tip:'Vale intentarlo con cara de que sabemos lo que hacemos. Si no nos dejan, se sale por la salida normal y se camina diez minutos hasta la plaza, donde hay control de seguridad con fila.'},
    {n:'Museos Vaticanos', d:'Siete kilómetros de salas y una de las colecciones de arte más grandes del mundo, que termina en la Capilla Sixtina. La escalera de caracol doble de Momo, la de la salida, es una foto en sí misma.', t:'visita', p:'€€', w:'https://www.museivaticani.va/', tip:'Ya tenemos la entrada de las 8:00. Llevar el QR bajado al teléfono, porque en la fila la señal es mala. Y una botella vacía: adentro hay canillas.'},
    {n:'Basílica de San Pedro', d:'La iglesia más grande del mundo, con la Pietà de Miguel Ángel apenas entrando a la derecha, el baldaquino de Bernini sobre el altar y una escala que no se entiende hasta que uno ve lo chicas que quedan las personas al fondo.', t:'visita', w:'https://www.vatican.va/', tip:'La entrada es gratis, lo que se paga es la cúpula. Hay control de seguridad en la plaza y la fila avanza rápido. Los mosaicos que parecen cuadros son mosaicos: no hay un solo cuadro pintado en toda la basílica.'},
    {n:'La cúpula de San Pedro', d:'Se sube por dentro de la cúpula, primero a la galería interior que da sobre el altar y después hasta la linterna, con Roma entera y los jardines vaticanos abajo. El último tramo es una escalera angosta y en caracol, con la pared inclinada.', t:'visita', p:'€', tip:'Con ascensor hasta la terraza quedan unos trescientos escalones; a pie son más de quinientos. La entrada se compra ahí mismo, a la derecha del atrio. Si hay claustrofobia, el tramo final es incómodo de verdad.'},
    {nota:1, n:'El código de vestimenta', d:'Hombros y rodillas cubiertos, para los dos, tanto en los museos como en la basílica. Lo controlan en la puerta y no hay discusión: se vuelve uno a cambiar.', t:'visita', tip:'Si el día viene caluroso, un pañuelo grande en la mochila resuelve. En la calle venden ponchos de papel carísimos justamente por esto.'},
    {nota:1, n:'Los días que conviene evitar', d:'Los miércoles de mañana hay audiencia papal y la plaza de San Pedro se cierra por eso: no se entra a la basílica hasta el mediodía. Los domingos los museos están cerrados, salvo el último de cada mes, que es gratis y por eso imposible.', t:'visita', tip:'Nuestro martes es de los días más tranquilos de la semana, así que quedó bien elegido. Lo que sí conviene: no ir a San Pedro el miércoles de mañana, que es nuestro día libre.'},
    {nota:1, n:'Dónde comer al salir', d:'Alrededor de los museos casi todo es malo y caro, con menús plastificados y gente en la puerta. Hay que caminar cinco o diez minutos hacia Prati y cambia todo.', t:'visita', tip:'Pizzarium Bonci está a diez minutos de la salida de los museos y es de lo mejor de Roma. Il Sorpasso, en Prati, no cierra la cocina a media tarde. Y la Gelateria dei Gracchi, también en Prati, es la respuesta al problema del gelato malo de la zona.'}
  ]},

  {s:'El Coliseo y el Foro', k:'visita', items:[
    {nota:1, n:'La situación de las entradas', d:'Las oficiales salen en coopculture.it unos treinta días antes, a las 9:00 de Italia, y se agotan en minutos. No hay truco ni contacto: es entrar puntual el día que se abre la venta.', t:'visita', tip:'Si el día que queremos ya voló, quedan tres caminos oficiales: la visita guiada o el Full Experience, que tienen cupo aparte; el ticket de Foro Romano y Palatino, que se vende por separado; y mirar la web dos o tres días antes por devoluciones. Lo que no vale la pena es la reventa.'},
    {nota:1, n:'El Foro se puede visitar sin entrada del Coliseo', d:'Esta es la respuesta a la duda: el Parque Arqueológico vende un ticket de <em>Foro Romano y Palatino</em> separado del que incluye el Coliseo. Con ese se entra al Foro y al Palatino sin problema, y es bastante más fácil de conseguir.', t:'visita', tip:'Además el Palatino es la parte que más se disfruta y la que menos gente tiene: son las ruinas de los palacios imperiales sobre la colina, con vista al Foro de un lado y al Circo Massimo del otro.'},
    {nota:1, n:'Si igual no hay entradas', d:'El Coliseo por fuera es gratis y sigue siendo impresionante. La vuelta completa a pie lleva veinte minutos y de noche, iluminado, es mejor que de día.', t:'visita', tip:'La otra jugada gratis: la terraza del Campidoglio, subiendo la escalinata de Miguel Ángel y pasando por el costado derecho del palacio, da sobre el Foro entero desde arriba. Es la mejor vista del Foro que hay y no cuesta nada.'},
    {n:'Coliseo', d:'El anfiteatro más grande del imperio, con capacidad para más de cincuenta mil personas y un sistema de sótanos con ascensores para subir animales a la arena. Lo que falta de la fachada se lo llevaron para construir media Roma.', t:'visita', p:'€€', w:'https://parcocolosseo.it/', tip:'Si entramos, ir temprano: a las 9 hay sombra y menos gente. El acceso a la arena y a los sótanos se paga aparte y se agota antes que todo lo demás.'},
    {ruta:['Colosseo, Roma','Arco di Tito, Roma','Foro Romano, Roma','Piazza del Campidoglio, Roma'], n:'Foro Romano y Palatino', d:'El centro de la vida pública de la Roma antigua, hoy un campo de columnas sueltas y basas de templos. Sin contexto es un montón de piedras, y con contexto es donde pasó todo.', t:'visita', p:'€€', tip:'Se entra por el Coliseo, se sube al Palatino y se sale por el Foro hacia los Fori Imperiali, que es cuesta abajo y termina cerca del Campidoglio. Bajarse un audioguía o un mapa antes: adentro casi no hay carteles y la señal es mala.'},
    {ruta:['Via dei Fori Imperiali, Roma','Piazza Venezia, Roma','Piazza del Campidoglio, Roma'], n:'Los Foros Imperiales por fuera', d:'La avenida que Mussolini abrió por el medio de las ruinas, con el Foro de Trajano y su columna de un lado y el Foro Romano del otro. Se ve todo desde la vereda, gratis, y a la noche está iluminado.', t:'visita', tip:'Es el camino natural del Coliseo al Ghetto, que es justo lo que hacemos el miércoles. La columna de Trajano tiene la historia de una guerra tallada en espiral de abajo arriba, y se ve bien desde la baranda.'}
  ]}
  ]
},
