{
  id:'tos', nav:'Toscana', name:'Toscana', plate:'San Gimignano', accent:'#4D7C0F', lt:'#BEF264', maps:'Toscana',
  lede:'Cuatro noches en San Gimignano con auto, que es la única forma de aprovechar esto. La base está bien elegida: Siena, Volterra, el Chianti y la Val d’Orcia quedan todos a menos de hora y media.',
  quick:[
    ['Cuándo','Vie 9 a mar 13 de octubre'],
    ['Dormimos','Hotel Sovestro, San Gimignano'],
    ['El auto','Se retira en Peretola'],
    ['Octubre','21° / 10°, niebla al amanecer'],
    ['Ojo','ZTL: cámara y multa en cada pueblo']
  ],
  sections:[
  {s:'El plan, día por día', k:'plan', html:`
      <h3>Viernes 9: llegada y San Gimignano de noche</h3>
      <ul>
        <li>De Florencia con el auto retirado en Peretola, llegada al <b>Hotel Sovestro</b> a la tarde. Está afuera de las murallas, sobre la carretera: tiene estacionamiento y no hay ZTL.</li>
        <li>La primera tarde es para <b>San Gimignano</b>, que es la mejor hora: los excursionistas de un día se van a las cinco y el pueblo queda casi vacío. Piazza della Cisterna, Piazza del Duomo, la subida a la Rocca para ver las torres contra el atardecer, y un <b>Dondoli</b>, el heladero campeón del mundo, en la plaza.</li>
      </ul>
      <h3>Sábado 10: Siena y Monteriggioni</h3>
      <ul>
        <li><b>Siena</b>, a cuarenta y cinco minutos, la excursión más grande que tenemos cerca. La Piazza del Campo con forma de concha, el Duomo con la fachada rayada y, con suerte, el piso de mármol descubierto, que solo se destapa unas semanas por año, casi siempre hasta mediados de octubre.</li>
        <li>Volviendo, <b>Monteriggioni</b>, en el camino: un pueblo amurallado circular y minúsculo, entero dentro de sus murallas, que se recorre en cuarenta minutos por arriba de la muralla incluida.</li>
      </ul>
      <h3>Domingo 11: la Val d’Orcia y las termas</h3>
      <ul>
        <li>El día largo y el más lindo. Temprano hacia el sur por las carreteras de cipreses: <b>Pienza</b> para el pecorino y la vista del valle, <b>Bagno Vignoni</b> con su plaza que es una pileta termal humeante del siglo XV, y <b>Bagni San Filippo</b> para meterse de verdad en el agua caliente, gratis, entre formaciones blancas de cal.</li>
        <li>Si queda cuerpo, <b>Montalcino</b> a la vuelta para un Brunello en la enoteca de la fortaleza. Son unas seis horas de paseo y dos y media de auto en total.</li>
      </ul>
      <h3>Lunes 12: Volterra y el Chianti, o descanso</h3>
      <ul>
        <li><b>Volterra</b>, a cuarenta y cinco minutos, lo opuesto a San Gimignano: etrusca, oscura, de piedra gris, con un teatro romano y talleres de alabastro donde se ve trabajar.</li>
        <li>La <b>ruta del Chianti</b> hacia el norte, parando en Castellina y Panzano, con una bodega reservada de antemano. Si elegimos esta, decidir antes quién maneja y quién prueba.</li>
        <li>O quedarse en San Gimignano, siesta y caminar el pueblo con calma. Son cuatro días de mucho auto y uno de descanso a la mitad no es tiempo perdido.</li>
      </ul>
      <h3>Martes 13: a La Spezia</h3>
      <ul>
        <li>Salida sobre las 8:30, unas dos horas y cuarto hasta La Spezia. Auto en la oficina de la rentadora, valijas en el alojamiento, y a Cinque Terre con la tarde entera por delante.</li>
        <li>Pisa queda de paso y tienta, pero el desvío cuesta una hora larga entre ida, vuelta y estacionamiento, y esa hora sale de Cinque Terre. Si igual queremos la foto de la torre, salir 7:30 y no estirar la parada más de cuarenta minutos.</li>
      </ul>
    `},

  {s:'El auto: todo lo que hay que saber', k:'mover', items:[
    {m:'Hotel Sovestro, San Gimignano', n:'Dónde dormimos: Hotel Sovestro', d:'Afuera de las murallas de San Gimignano, sobre la carretera de Poggibonsi, con estacionamiento propio y campo alrededor. Al pueblo se llega en unos minutos en auto o caminando un tramo de subida.', t:'mover', tip:'Estar afuera de las murallas es una ventaja y no una desventaja: no hay ZTL, hay dónde dejar el auto y de noche se ve el pueblo iluminado desde afuera.'},
    {nota:1, n:'La ZTL, otra vez y en todos lados', d:'San Gimignano, Siena, Volterra, Montalcino y Pienza tienen zona restringida en el centro histórico, con cámara que lee la patente. La multa llega meses después a la rentadora, que la reenvía con su cargo agregado.', t:'mover', tip:'La regla que no falla: se estaciona <em>afuera</em> de las murallas y se entra caminando. En estos pueblos siempre hay playas de estacionamiento pagas justo antes de la puerta, señalizadas con la P. Nunca cruzar un cartel redondo con borde rojo que diga "zona traffico limitato", aunque el GPS lo indique.'},
    {nota:1, n:'Estacionar en San Gimignano y en Siena', d:'En San Gimignano hay varias playas numeradas alrededor de las murallas, todas pagas y a pocos minutos a pie de las puertas. En Siena, lo más cómodo es el estacionamiento del Santa Caterina, que tiene escaleras mecánicas que suben hasta el centro.', t:'mover', tip:'Se paga en la máquina antes de volver al auto, no al salir. Y conviene llevar algunas monedas: algunas máquinas viejas todavía no toman tarjeta.'},
    {nota:1, n:'Nafta, gasoil y las estaciones', d:'Al retirar el auto hay que preguntar y anotar qué carga: <em>benzina</em> es nafta y <em>gasolio</em> es gasoil. Equivocarse arruina el motor y no lo cubre ningún seguro.', t:'mover', tip:'En las estaciones hay dos surtidores del mismo combustible: <em>fai da te</em>, que es autoservicio y más barato, y <em>servito</em>, donde te atienden y cuesta bastante más. En el campo muchas cierran al mediodía y los domingos, y funcionan con una máquina que solo toma billetes o tarjeta. No conviene andar con menos de un cuarto de tanque.'},
    {nota:1, n:'Peajes de autopista', d:'En la autopista se saca un ticket al entrar y se paga al salir según los kilómetros. Las cabinas amarillas con la T son solo para Telepass y no hay que meterse: si entramos en una sin el dispositivo, se traba todo.', t:'mover', tip:'Las cabinas blancas son de tarjeta y las azules de billetes. Las carreteras secundarias entre pueblos son gratis, más lindas y más lentas: para la Val d’Orcia son las que hay que tomar, para llegar a La Spezia conviene la autopista.'},
    {nota:1, n:'Devolver el auto en La Spezia', d:'Es un alquiler de una punta a la otra, así que tiene cargo por devolución en otra ciudad. Conviene tener claro de antemano la dirección exacta de la oficina, el horario y si cierran al mediodía, que muchas lo hacen.', t:'mover', tip:'Devolverlo con el tanque como lo entregaron y sacar fotos del auto por los cuatro lados y del tablero con el nivel de combustible antes de entregar las llaves. Es lo único que sirve si después aparece un cargo por un rayón que no hicimos.'},
    {nota:1, n:'Manejar en la Toscana', d:'Las carreteras son angostas, con curvas cerradas y sin banquina, y los locales manejan rápido. Las rutas de tierra blanca, las <em>strade bianche</em>, son normales y están bien mantenidas, pero se anda despacio.', t:'mover', tip:'La señal de celular se corta entre colinas, así que los mapas hay que bajarlos antes. Y ojo con la niebla de la mañana en octubre: en el valle a las 8 puede no verse nada y a las 10 estar despejado.'}
  ]},

  {s:'Sentarse a comer', k:'comer', items:[
    {nota:1, n:'Acá el horario de la cocina es una pared', d:'En los pueblos no hay red de contención. Si la cocina cierra a las 14:00 y llegamos a las 14:10, no comemos: no hay otro lugar abierto a la vuelta de la esquina.', t:'comer', tip:'En octubre encima muchos cierran un día entre semana o directamente por temporada. Antes de manejar media hora hasta un pueblo a almorzar, mirar el horario de ese día en Google o llamar.'},
    {nota:1, n:'Reservar aunque el lugar parezca chico', d:'Justamente porque es chico. Una trattoria de pueblo tiene seis mesas y en octubre hace un solo turno de cena, así que se llena con dos familias y ya no entra nadie más.', t:'comer', tip:'Se reserva llamando por teléfono, que fuera de Florencia sigue siendo lo normal, y muchas veces atiende quien cocina. Con decir el día, la hora y cuántos somos alcanza.'},
    {nota:1, n:'En la enoteca se come de parada', d:'Una enoteca no es un restaurante: se pide en la barra, sirven el vino por copa y sale una tabla de fiambre y queso para picar. Muchas tienen dos mesas o ninguna.', t:'comer', tip:'Es la mejor manera de almorzar liviano un día de manejar, y de probar tres vinos distintos sin comprometerse con una botella. Se paga en la barra al final, todo junto.'},
    {nota:1, n:'Qué se come acá y no en otro lado', d:'Los pici, que son un espagueti gordo hecho a mano, casi siempre <em>all’aglione</em>, con una salsa de tomate y ajo dulce. La ribollita, que es una sopa espesa de pan y verdura. Y los embutidos de Colonnata y de Cinta Senese, que es un cerdo local.', t:'comer', tip:'Y la Vernaccia di San Gimignano, que es el vino blanco del pueblo y fue la primera denominación de origen de Italia. En una tierra de tintos, tomar el blanco local es lo que hace la gente de acá.'}
  ]},

  {s:'Comer', k:'comer', items:[
    {a:'San Gimignano', n:'Dal Bertelli', d:'Un cuarto diminuto sin mesas, con jamones colgados y libros viejos en los estantes. Hacen una sola cosa, sándwiches de embutido y queso de la zona, y los hacen muy bien.', t:'comer', p:'€', serv:'mostrador', res:'no', tip:'No hay carta ni precios a la vista: se elige señalando. Cierra temprano y cuando se acaba el pan, se acabó. Es el almuerzo perfecto de un día de pueblo.'},
    {a:'San Gimignano', n:'Osteria delle Catene', d:'Adentro de las murallas, cocina toscana de la buena sin ponerse cara: pici, sopas, embutidos y una carta corta de Vernaccia.', t:'comer', p:'€€', serv:'mesa', res:'conviene', tip:'Es la cena de cualquiera de las noches en San Gimignano. Reservar, porque tiene pocas mesas.'},
    {a:'San Gimignano', n:'Cum Quibus', d:'La cocina más ambiciosa del pueblo, en un local minúsculo con un patio interior. Menú de pasos y técnica seria, a precio de restaurante de pueblo y no de ciudad.', t:'comer', p:'€€€', serv:'mesa', res:'si', tip:'Si vamos a hacer una sola cena cara en la Toscana, es esta o Buca Lapi en Florencia. Se reserva con bastante antelación porque entran muy pocas mesas.'},
    {a:'Siena', n:'La Taverna di San Giuseppe', d:'En un sótano excavado en la roca etrusca, a cinco minutos de la Piazza del Campo. Cocina sienesa seria, con pici hechos a mano y una carta de vinos larga.', t:'comer', p:'€€', serv:'mesa', res:'si', tip:'Reservar con días. Es de los pocos lugares de Siena que no bajan la guardia con el turismo.'},
    {a:'Siena', n:'Trattoria Papei', d:'Detrás de la Piazza del Campo, en la Piazza del Mercato. Casera, barata y de toda la vida: pici all’aglione, ribollita, conejo.', t:'comer', p:'€', serv:'mesa', res:'conviene', tip:'Es el almuerzo del sábado en Siena. Tiene mesas afuera con vista al valle, que es un lujo que no cobra.'},
    {a:'Pienza', n:'Los quesos de Pienza', d:'Pienza vive del pecorino y la calle principal es una sucesión de tiendas donde te hacen probar antes de comprar: fresco, semicurado, curado, o envuelto en heno o en hojas de nogal.', t:'comer', p:'€', serv:'mostrador', res:'no', tip:'El curado aguanta el viaje sin heladera y llega bien a Uruguay envuelto en papel. El fresco no. Se puede armar un almuerzo de picnic con queso, pan y una botella y comerlo mirando el valle desde la muralla.'},
    {a:'Montalcino', n:'Enoteca de la Fortezza de Montalcino', d:'Adentro de la fortaleza del pueblo, con mesas entre los muros. Es el lugar más directo para probar un Brunello sin sacar turno en una bodega.', t:'comer', p:'€€', serv:'barra', res:'no', tip:'El Brunello necesita años en botella y por eso es caro. El Rosso di Montalcino es el mismo viñedo con menos crianza, sale bastante menos y para tomar ahora está mejor.'}
  ]},

  {s:'Café y gelato', k:'cafe', items:[
    {a:'San Gimignano', n:'Gelateria Dondoli', d:'En la Piazza della Cisterna, del heladero que ganó el campeonato mundial de gelato. Sabores raros que funcionan, tipo azafrán con piñones o queso de oveja con nueces.', t:'cafe', p:'€', serv:'mostrador', res:'no', tip:'En verano la cola da la vuelta a la plaza; en octubre se entra caminando. Es una de las ventajas de venir ahora. El de Vernaccia y el de champagne con pomelo rosado son los que lo hicieron famoso.'},
    {a:'San Gimignano', n:'Un café en la Piazza della Cisterna', d:'La plaza triangular de ladrillo con el pozo en el medio, rodeada de torres. Sentarse ahí a media mañana con un café y ver cómo se llena y se vacía el pueblo es media razón para haber venido.', t:'cafe', p:'€', serv:'mesa', res:'no', tip:'Sentarse en la mesa cuesta bastante más que tomarlo en la barra, y acá se paga la plaza. Una vez vale.'},
    {nota:1, n:'El desayuno del hotel y la barra del pueblo', d:'El desayuno italiano es dulce y corto: café, cornetto y poco más. Si el del hotel no alcanza, en cualquier bar del pueblo se resuelve de pie en tres minutos.', t:'cafe', tip:'Y una advertencia de octubre: en los pueblos chicos los bares abren temprano pero cierran a media tarde, y el domingo muchos directamente no abren.'}
  ]},

  {s:'Vino', k:'coctel', items:[
    {a:'San Gimignano', n:'Vernaccia en la Rocca', d:'La Vernaccia di San Gimignano fue la primera denominación de origen de Italia, en 1966, y es un blanco seco y mineral que casi no sale del pueblo. Arriba, en la Rocca de Montestaffoli, hay una terraza con vista a las torres y al valle donde se toma por copa.', t:'coctel', p:'€', serv:'barra', res:'no', tip:'La subida a la Rocca es gratis y la vista al atardecer es la mejor del pueblo. Es el plan de la primera tarde.'},
    {m:'Antinori nel Chianti Classico, Bargino', n:'Bodega Antinori nel Chianti Classico', d:'Una bodega enterrada en la colina, con el techo cubierto de viñedo y una escalera de caracol que baja entre las barricas. La familia hace vino desde 1385 y el edificio es de lo mejor de la arquitectura italiana reciente.', t:'coctel', p:'€€', serv:'mesa', res:'si', w:'https://www.antinorichianticlassico.it/', tip:'Está camino a Florencia, a unos cuarenta minutos, y se visita solo con reserva. Es la bodega más fácil de sumar a un día de Chianti sin meterse en caminos de tierra.'},
    {nota:1, n:'Bodegas en octubre', d:'Octubre es después de la vendimia, así que las bodegas están tranquilas y siguen recibiendo, pero con horario corto y solo con reserva previa. La ventaja es grande: en vez de una visita en grupo de treinta personas, muchas veces atiende el dueño sin apuro.', t:'coctel', tip:'Si manejamos, hay que acordar antes quién prueba y quién no. Una degustación son cinco o seis copas por cabeza, que es media botella, y los controles en la ruta existen y son duros.'},
    {nota:1, n:'La ruta del Chianti', d:'La carretera SR222, que va de Florencia a Siena por el medio de las colinas, es el paseo en auto clásico de la Toscana: viñedos, cipreses, castillos y pueblos de piedra cada quince minutos.', t:'coctel', tip:'Los pueblos que valen la parada son Castellina, Panzano, que tiene la carnicería de Dario Cecchini, y Radda. En una tarde se hacen dos, no los tres.'}
  ]},

  {s:'Las termas', k:'aire', items:[
    {m:'Bagni San Filippo, Fosso Bianco', n:'Bagni San Filippo', d:'Un arroyo de agua caliente que baja por el bosque entre formaciones blancas de cal, la más grande de las cuales le dicen la Ballena Blanca. Se entra al agua en las pozas naturales, es gratis y está abierto siempre.', t:'aire', tip:'Es la recomendación principal: está a una hora y tres cuartos, entra perfecto en el día de la Val d’Orcia y es de las termas libres más impresionantes de Italia. No hay vestuarios ni nada: se llega cambiado o se cambia en el auto. Ojotas, toalla y una bolsa para la ropa mojada.'},
    {m:'Bagno Vignoni, Val d Orcia', n:'Bagno Vignoni', d:'Un pueblo cuya plaza central no es una plaza sino una pileta termal enorme del siglo XV, humeando en el medio de las casas. No se puede entrar a esa, pero abajo, en el Parco dei Mulini, hay pozas libres sobre la roca con vista al valle.', t:'aire', tip:'Está a diez minutos de San Filippo, así que los dos entran en el mismo día. La plaza con vapor a primera hora de la mañana es una de las imágenes más raras de la Toscana.'},
    {m:'Terme di Saturnia, Cascate del Mulino', n:'Las cascadas de Saturnia', d:'Las termas más famosas de Italia: una serie de piletas de travertino blanco escalonadas, con el agua turquesa cayendo de una a otra. La versión libre, las Cascate del Mulino, es gratis y abierta las veinticuatro horas.', t:'aire', tip:'El problema es la distancia: son unas dos horas y cuarto desde San Gimignano, cada tramo. Es un día entero de auto para un baño. Si lo que queremos es la foto famosa, vale; si lo que queremos es meternos en agua caliente, San Filippo está mucho más cerca y es igual de lindo.'},
    {m:'Terme San Giovanni, Rapolano Terme', n:'Rapolano Terme', d:'Termas de verdad, con piletas de agua caliente, vestuarios, toallas y bar. La opción cómoda y sin barro, a poco más de una hora.', t:'aire', p:'€€', res:'conviene', tip:'Abren de noche varios días de la semana, y meterse en agua a treinta y ocho grados con el aire fresco de octubre y ya oscuro es exactamente el plan de un día de mucho auto. Conviene confirmar el horario nocturno antes de ir.'},
    {nota:1, n:'Cómo se va a las termas libres', d:'Ojotas o sandalias que se puedan mojar, porque el fondo es piedra resbalosa. Toalla grande, bolsa para la ropa mojada, y agua para tomar, que el calor deshidrata más de lo que parece.', t:'aire', tip:'Dos cosas que nadie avisa: el azufre huele a huevo podrido y el olor queda en la malla y en el pelo, así que mejor una malla vieja. Y el azufre ennegrece la plata: los anillos y las cadenas se sacan antes de entrar.'}
  ]},

  {s:'Los pueblos', k:'visita', items:[
    {a:'San Gimignano', n:'San Gimignano y sus torres', d:'Quedan catorce de las setenta y dos torres que llegó a tener, construidas por familias rivales para ver quién la tenía más alta. Es el único sitio donde se puede ver cómo era una ciudad medieval italiana antes de que las tiraran todas.', t:'visita', tip:'El truco es el horario: de 10 a 17 se llena de excursiones de un día y a las 18 queda vacío. Dormir acá es tener el pueblo para nosotros a la mañana temprano y de noche. Se sube a la Torre Grossa, la más alta, con entrada.'},
    {a:'Siena', n:'Piazza del Campo', d:'La plaza con forma de concha, inclinada hacia el Palazzo Pubblico, donde dos veces por año corren el Palio alrededor del borde. Está hecha en nueve sectores de ladrillo por los Nueve que gobernaban la ciudad.', t:'visita', tip:'Sentarse en el piso de la plaza, que está inclinado, es lo que hace todo el mundo y es gratis. La Torre del Mangia se sube con entrada y son más de cuatrocientos escalones, con la mejor vista de la Toscana arriba.'},
    {a:'Siena', n:'Duomo de Siena', d:'Rayado en blanco y negro por dentro y por fuera, con un piso de mármol con incrustaciones que cuenta escenas enteras y que está tapado casi todo el año para protegerlo.', t:'visita', p:'€€', w:'https://operaduomo.siena.it/', tip:'El piso se destapa unas pocas semanas por año, normalmente entre agosto y mediados de octubre. Vale la pena mirar en la web si nuestra fecha cae adentro, porque cambia la visita por completo. Y la Libreria Piccolomini, con los frescos de Pinturicchio de colores intactos, es lo mejor de adentro.'},
    {a:'Monteriggioni', n:'Monteriggioni', d:'Un círculo de murallas con catorce torres en el medio del campo, y adentro apenas una plaza y dos calles. Dante lo nombra en el Infierno comparando las torres con gigantes asomados.', t:'visita', tip:'Se estaciona abajo y se sube caminando cinco minutos. Se recorre entero en cuarenta minutos, se puede caminar por arriba de un tramo de muralla y es la parada perfecta volviendo de Siena.'},
    {a:'Volterra', n:'Volterra', d:'Etrusca antes que romana y romana antes que medieval, en lo alto de una colina pelada. Piedra gris, un teatro romano que se ve entero desde arriba y gratis, y talleres de alabastro donde se puede entrar a ver trabajar.', t:'visita', tip:'Es el contraste perfecto con San Gimignano: acá no hay postal, hay ciudad. El Museo Etrusco Guarnacci tiene la Sombra de la Noche, una figura de bronce alargadísima de hace dos mil quinientos años.'},
    {a:'Pienza', n:'Pienza y el balcón de la Val d’Orcia', d:'Un pueblo entero rediseñado en el siglo XV por un papa que había nacido ahí, como la primera ciudad ideal del Renacimiento. Detrás de la catedral hay un paseo colgado sobre el valle que es la vista de postal de la Toscana.', t:'visita', tip:'Es chico y se ve en una hora. Las calles del centro tienen nombres como Via dell’Amore y Via del Bacio, que le puso el mismo papa. Ideal para el almuerzo del domingo antes de las termas.'},
    {ruta:['Pienza, Italia','San Quirico d Orcia, Italia','Bagno Vignoni, Italia','Bagni San Filippo, Italia'], n:'La ruta de los cipreses', d:'El tramo de la Val d’Orcia entre Pienza y San Quirico es el paisaje que sale en todas las fotos: colinas peladas, caminos de tierra en curva y grupos de cipreses solitarios.', t:'aire', tip:'Los dos puntos más fotografiados están sobre esta ruta y señalizados en Google Maps: la Cappella della Madonna di Vitaleta y el grupo de cipreses de la Podere Baccoleno. Hay que parar en la banquina, no en medio de la curva.'}
  ]}
  ]
},
