{
  id:'sev', nav:'Sevilla', name:'Sevilla', plate:'Tussam', accent:'#7E22CE', lt:'#D8B4FE', maps:'Sevilla',
  lede:'Una semana entera y con otra lógica: Vale en la universidad de lunes a viernes, yo trabajando desde el apartamento, y las tardes y el fin de semana para los dos. Es la parte del viaje donde conviene vivir la ciudad en vez de recorrerla.',
  quick:[
    ['Cuándo','Dom 18 a dom 25 de octubre'],
    ['Dormimos','Airbnb, con 3 compañeras de Vale'],
    ['Vale','Loyola, lun a vie'],
    ['Octubre','27° / 14°, sol casi seguro'],
    ['Volvemos','Dom 25 de noche, vía Madrid']
  ],
  sections:[
  {s:'El plan de la semana', k:'plan', html:`
      <h3>Domingo 18: llegada y primera vuelta</h3>
      <p>Llegamos de Barcelona, hacemos el check in en el apartamento y salimos a caminar sin plan. Lo primero es lo práctico: encontrar el supermercado más cercano, ver cómo funciona la casa con cinco personas adentro y comprar para el desayuno de la semana.</p>
      <p>Después, la primera vuelta por el centro con la última luz, que es la mejor hora de Sevilla: la <b>Catedral</b> y la <b>Giralda</b> por fuera, el <b>Barrio de Santa Cruz</b> y una cena de tapas temprana, que el domingo muchas cocinas cierran a las once.</p>
      <p>Y lo más importante del día: <b>medir el camino a Loyola</b>. Con la dirección exacta en la mano, ver en Google Maps cuánto lleva a la hora a la que Vale tiene que estar el lunes, y sumarle un margen. Si la sede está en el campus de Dos Hermanas, afuera de la ciudad, el viaje no es corto y conviene saberlo hoy y no mañana a las ocho.</p>
      <h3>Lunes a viernes: la semana partida</h3>
      <p>Las mañanas cada uno con lo suyo: Vale en la universidad y yo trabajando. El horario juega a favor, porque Uruguay está cinco horas atrás y la mañana española es tiempo tranquilo antes de que arranque el día allá.</p>
      <p>El plan de las tardes es simple: aprovechar que anochece a las 19:35 y que a las seis de la tarde Sevilla recién se despierta. Una cosa por tarde, sin apurar:</p>
      <p><b>Lunes</b>, la <b>Plaza de España</b> al atardecer, que es la más impresionante de la ciudad y es gratis. <b>Martes</b>, <b>Triana</b> cruzando el puente, el mercado y la calle Betis con la vista de la ciudad del otro lado del río. <b>Miércoles</b>, las <b>Setas</b> al atardecer y tapas por la Alfalfa. <b>Jueves</b>, la <b>Catedral y la Giralda</b>, que ya están reservadas a las 17:20. <b>Viernes</b>, el <b>Real Alcázar</b> a las 16:30 y, saliendo, flamenco.</p>
      <p>Las noches son de tapeo, que acá no es una comida sino un recorrido: se toma algo y una tapa en un bar, se paga, y se sigue al siguiente. Tres o cuatro bares es una cena.</p>
      <h3>Sábado 24: el día largo</h3>
      <p>El único día completo de los dos juntos. Dos opciones y las dos buenas.</p>
      <p>La ambiciosa: <b>Córdoba</b> en el AVE, que son cuarenta y cinco minutos, para ver la Mezquita, que es de las cosas más impresionantes de España. Se va temprano, se vuelve de noche y es un día redondo.</p>
      <p>La otra, y la que recomiendo si la semana viene pesada: quedarse. Un paseo en barco por el <b>Guadalquivir</b>, el <b>Parque de María Luisa</b> con calma, la <b>Casa de Pilatos</b>, que casi nadie visita y es preciosa, y una cena larga sin mirar el reloj.</p>
      <h3>Domingo 25: el último día</h3>
      <p>Cambio de hora de madrugada, así que ganamos una hora de sueño. El vuelo es de noche, así que el día está entero: el vermut del domingo, un último paseo por el río y las valijas a media tarde.</p>
      <p>Cuidado con dos cosas: el domingo muchos negocios y varios restaurantes cierran, y el aeropuerto de Sevilla es chico pero el check in de un vuelo con conexión internacional pide margen.</p>
    `},

  {s:'Cómo moverse y vivir acá', k:'mover', items:[
    {nota:1, n:'El campus de Loyola, que es el dato a confirmar', d:'La Universidad Loyola tiene su campus de Sevilla afuera de la ciudad, hacia el sur, en Dos Hermanas, y también actividades en edificios del centro. No es lo mismo caminar quince minutos que tomarse un cercanías más un bus todos los días.', t:'mover', tip:'Hay que preguntarle a la organización del programa la dirección exacta antes de viajar, y con eso medir el trayecto real a la hora exacta. Si es Dos Hermanas, las opciones son el tren de cercanías C-1 desde Santa Justa o San Bernardo, más un tramo en bus o taxi, o directamente un taxi compartido entre las cuatro, que dividido sale razonable.'},
    {nota:1, n:'Sevilla se camina, y el resto es bici', d:'El centro histórico es chico y plano, y casi todo está a veinte minutos de casi todo. El calor del mediodía es el único enemigo.', t:'mover', tip:'Sevici es el sistema de bicis públicas y tiene abono semanal, que para esta semana viene perfecto. Hay estaciones por todos lados y la ciudad está llena de bicisendas separadas del tránsito. Es la mejor forma de moverse acá.'},
    {nota:1, n:'Bus, tranvía y taxi', d:'La red de buses de Tussam cubre todo y hay un tranvía corto que une San Bernardo con la Plaza Nueva por el centro. El metro tiene una sola línea y no pasa por donde uno quiere.', t:'mover', tip:'Para las noches, Cabify y Bolt funcionan bien y son bastante más baratas que el taxi. Y el taxi tiene tarifa fija desde el aeropuerto al centro, que conviene confirmar al subir.'},
    {nota:1, n:'La casa con cinco adentro', d:'Somos nosotros dos más tres compañeras de Vale, así que los baños, la cocina y la wifi se comparten. Vale la pena acordar el primer día lo básico: horarios de baño de la mañana y quién compra qué.', t:'mover', tip:'Para trabajar, lo importante es tener un rincón con mesa y enchufe que sea mío en horario de oficina. Si no lo hay, los cafés de la sección de trabajo lo resuelven. Y confirmar antes de viajar con el anfitrión la velocidad real de la wifi y si hay lavarropas, que en una semana hace falta.'},
    {nota:1, n:'El supermercado y los horarios', d:'Mercadona y Lidl son los baratos y hay varios en el centro. Los negocios chicos cierran de 14:00 a 17:00 y los domingos no abre casi nada, ni siquiera los supermercados grandes.', t:'mover', tip:'La compra grande se hace el sábado. Y hay que acostumbrarse a que a las tres de la tarde la ciudad se apaga: no es que esté todo cerrado para siempre, vuelve a las cinco.'},
    {nota:1, n:'El calor de octubre', d:'Veintisiete de máxima al mediodía y catorce de madrugada. Sevilla en octubre todavía tiene sol fuerte entre las dos y las cinco, y a esa hora la ciudad se vacía por algo.', t:'mover', tip:'Las visitas al aire libre van temprano o después de las seis. Botella de agua siempre, y una campera fina para la noche, porque la diferencia de trece grados entre el mediodía y la madrugada se siente.'}
  ]},

  {s:'Trabajar desde Sevilla', k:'cafe', items:[
    {nota:1, n:'La ventaja del huso horario', d:'Sevilla está cinco horas adelante de Montevideo. La mañana española, de 9 a 13, es tiempo sin interrupciones porque allá todavía no arrancó nadie. Las reuniones caen recién de tarde.', t:'cafe', tip:'Sirve para hacer el trabajo que necesita concentración a la mañana y dejar la tarde para llamadas. Y si algún día se puede cerrar temprano, esa es la tarde para salir con Vale cuando termina en la universidad.'},
    {nota:1, n:'Cómo se usa un café para trabajar acá', d:'En un bar de barrio, ocupar la mesa cuatro horas con un café queda mal. En un café de especialidad es exactamente para lo que están, y muchos tienen enchufes y wifi buena.', t:'cafe', tip:'La regla no escrita: consumir cada hora y media más o menos, y liberar la mesa si el lugar se llena a la hora del almuerzo. Con eso nadie dice nada.'},
    {n:'Virgen Coffee', d:'Café de especialidad en el centro, chico y con gente que sabe lo que hace. De los primeros en traer el buen café a Sevilla.', t:'cafe', p:'€', serv:'mostrador', res:'no', tip:'Es de los mejores para una mañana de trabajo, pero es chico: conviene ir temprano y no al mediodía.'},
    {n:'Torch Coffee Roasters', d:'Tostadores propios, café filtrado bien hecho y espacio para sentarse un rato con la computadora.', t:'cafe', p:'€', serv:'mostrador', res:'no', tip:'De los que mejor funcionan para pasar dos horas trabajando sin sentirse de más.'},
    {n:'Ofelia Bakery', d:'Panadería y café, con masa madre, bollería buena y desayunos de verdad. Es el lugar para arrancar el día bien.', t:'cafe', p:'€', serv:'mostrador', res:'no', tip:'Se llena a media mañana los fines de semana. Entre semana a las nueve está tranquilo.'},
    {nota:1, n:'Si hace falta un coworking', d:'Sevilla tiene varios espacios de coworking que venden pases por día o por semana, sin contrato ni permanencia, con escritorio, wifi buena y sala para llamadas.', t:'cafe', tip:'No hace falta reservarlos desde acá: se busca "coworking Sevilla pase día" ya estando allá, se elige uno cerca del apartamento y se va. Un pase semanal cuesta poco y resuelve el problema de las llamadas largas, que es lo que peor funciona en una casa compartida.'}
  ]},

  {s:'Sentarse a comer', k:'comer', items:[
    {nota:1, n:'Apenas nos sentamos preguntan qué vamos a tomar', d:'En España el camarero llega a la mesa antes de que abramos la carta, y esa primera pregunta es por la bebida. Cuanto más de bar sea el sitio, más rápido llega.', t:'comer', tip:'La respuesta que salva es corta: una caña, una copa de vino, un fino o agua. Con eso ganamos los cinco minutos que necesitamos para leer la carta tranquilos.'},
    {nota:1, n:'Tapear no es cenar en un lugar', d:'El tapeo es un recorrido: se entra a un bar, se toma algo con una o dos tapas de pie en la barra, se paga y se sigue al siguiente. Tres o cuatro bares es una cena completa.', t:'comer', tip:'Por eso no hay que pedir de más en el primero. Y hay tres tamaños: tapa, que es una porción chica, media ración y ración. Entre dos, dos tapas por bar está bien.'},
    {nota:1, n:'La cuenta, a veces en la barra', d:'En un restaurante se pide y la traen a la mesa. En un bar de barrio, muchas veces se paga en la barra al salir, y quien atendió lleva la cuenta de memoria sin haber anotado nada.', t:'comer', tip:'Ante la duda se pregunta al pedir. Y para llamar al camarero, un "perdona" o un "cuando puedas" cuando pasa cerca es lo normal y no tiene nada de maleducado: acá no vienen cada diez minutos a preguntar si está todo bien.'},
    {nota:1, n:'Los horarios, que son los más tarde de Europa', d:'Se almuerza de 14:00 a 16:00 y se cena de 21:00 a 23:00. Si vamos a cenar a las 20:00 nos vamos a encontrar el sitio vacío, y no porque sea malo.', t:'comer', tip:'Entre las 16:30 y las 20:30 casi ninguna cocina de restaurante trabaja, pero los bares de tapas sirven todo el tiempo y eso cubre el hueco perfectamente. Es, de hecho, la mejor manera de comer en Sevilla.'},
    {nota:1, n:'Barra, mesa y terraza no cuestan lo mismo', d:'El mismo plato y la misma caña tienen tres precios según dónde se consuman, y es legal siempre que esté avisado en la carta.', t:'comer', tip:'La barra es la más barata y es donde está la conversación. En un bar de tapas es directamente la mejor mesa, y donde salen las cosas primero.'},
    {nota:1, n:'Dónde hace falta reservar', d:'Los bares de tapas no se reservan: se cae, se espera un rato de pie si hace falta y listo. Los restaurantes con nombre sí, y los muy conocidos con días.', t:'comer', tip:'De los de acá, Eslava y La Brunilda no toman reserva para la barra y hay cola: hay que estar cuando abren, sobre las 20:00, o resignarse a esperar. Los demás son de caer.'}
  ]},

  {s:'Tapas y comida', k:'comer', items:[
    {n:'Bodeguita Casablanca', d:'Cerca del Alcázar, una barra clásica donde comen sevillanos y no solo turistas. Los huevos rotos y el cazón en adobo son los que hay que pedir.', t:'comer', p:'€€', serv:'barra', res:'no', tip:'Queda a pasos de la salida del Alcázar, así que cierra bien el viernes.'},
    {n:'Eslava', d:'En el barrio de San Lorenzo, y para muchos el mejor tapeo de Sevilla. El huevo sobre bizcocho de boletus con vino de Oporto ganó premios y es lo que hay que pedir sí o sí.', t:'comer', p:'€€', serv:'barra', res:'cola', tip:'No reservan para la barra y se llena apenas abre. Estar en la puerta a las 20:00 o esperar bastante. El restaurante de al lado, del mismo dueño, sí toma reserva y sirve lo mismo.'},
    {n:'El Rinconcillo', d:'De 1670 y el bar más antiguo de Sevilla, con azulejos, jamones colgados y camareros que todavía anotan la cuenta con tiza sobre la barra de madera.', t:'comer', p:'€€', serv:'barra', res:'no', tip:'Las espinacas con garbanzos son el plato de la casa y son de origen árabe. Vale ir aunque sea una vez por el lugar, aunque esté lleno de gente.'},
    {n:'La Brunilda', d:'Cocina de tapas más moderna, en una calle chica cerca del Museo de Bellas Artes. Producto bueno y platos que no son los de siempre.', t:'comer', p:'€€', serv:'mesa', res:'cola', tip:'No reservan y es diminuto. Se anota uno en la lista al llegar y se espera con una caña en la puerta. Vale la espera.'},
    {n:'Bar Las Teresas', d:'En pleno Santa Cruz, angosto y con los jamones colgando del techo. Sobrevivió a la turistificación del barrio sin bajar la calidad.', t:'comer', p:'€€', serv:'barra', res:'no', tip:'Es la excepción a la regla de no comer en Santa Cruz. El jamón ibérico cortado a cuchillo, con una copa de manzanilla, de pie en la barra.'},
    {n:'Casa Morales', d:'De 1850, con las tinajas de vino enormes todavía apoyadas contra la pared del fondo. Tapas simples, baratas y honestas.', t:'comer', p:'€', serv:'barra', res:'no', tip:'Está a un minuto de la Catedral y es donde toman los sevillanos cuando salen del trabajo. Se pide en la barra de adelante.'},
    {a:'Triana, Sevilla', n:'Las Golondrinas', d:'En el corazón de Triana, con azulejos hasta el techo y dos plantas. El punta de solomillo y las setas al ajillo son los clásicos.', t:'comer', p:'€', serv:'barra', res:'no', tip:'Es la parada del martes cruzando el río. Está a pasos del Mercado de Triana, así que se combinan.'},
    {m:'Mercado de Triana, Sevilla', n:'Mercado de Triana', d:'El mercado de abastos construido sobre los restos del castillo de la Inquisición, con puestos de pescado, jamón y verdura, y varias barras donde se come ahí mismo.', t:'comer', p:'€', serv:'puesto', res:'no', tip:'De mañana está en su mejor momento. Abajo hay una parte donde se ven los cimientos del castillo, que se visita gratis.'},
    {nota:1, n:'Qué pedir en Sevilla', d:'El pescado frito, sobre todo el cazón en adobo y las puntillitas. El salmorejo, que es como el gazpacho pero espeso y con jamón picado encima. Las espinacas con garbanzos. Y la carne mechada.', t:'comer', tip:'Para tomar, lo de acá es la manzanilla o el fino, que son vinos secos de Jerez y Sanlúcar, servidos fríos en copa chica. Con pescado frito es la combinación local y cuesta muy poco. En verano se toma rebujito, que es fino con gaseosa de lima.'}
  ]},

  {s:'Café, dulce y merienda', k:'cafe', items:[
    {n:'Confitería La Campana', d:'Desde 1885, en la esquina más céntrica de Sevilla. Pastelería clásica con mostrador de mármol y salón atrás.', t:'cafe', p:'€', serv:'mostrador', res:'no', tip:'Es el punto de encuentro de toda la ciudad: "quedamos en La Campana" se entiende sin más explicación. Las yemas y los pestiños son lo clásico.'},
    {nota:1, n:'Los dulces de convento', d:'Varios conventos de clausura de Sevilla venden dulces hechos por las monjas, y en algunos la venta se hace por un torno giratorio de madera para no verse las caras: uno pone el dinero, gira el torno y vuelve con la caja.', t:'cafe', tip:'El más conocido es el del convento de San Leandro, con sus yemas. Es una experiencia rarísima y muy sevillana, y los horarios son cortos y de mañana. Vale la pena buscarlo una mañana entre semana.'},
    {nota:1, n:'El desayuno sevillano', d:'Tostada de pan con aceite de oliva y tomate rallado, o con manteca colorá, que es manteca de cerdo con especias, y un café con leche. Cuesta muy poco y se toma de pie en la barra.', t:'cafe', tip:'Se pide como "media tostada mixta" o "con aceite y tomate". Es lo que desayuna todo el mundo y es mejor que cualquier desayuno de hotel.'}
  ]},

  {s:'Lo que hay que ver', k:'visita', items:[
    {n:'Catedral y Giralda', d:'La catedral gótica más grande del mundo, construida sobre la mezquita mayor, con la tumba de Colón sostenida por cuatro figuras. La Giralda era el alminar de la mezquita y arriba le pusieron un campanario cristiano.', t:'visita', p:'€€', w:'https://www.catedraldesevilla.es/', tip:'Ya tenemos entrada para el jueves 22 a las 17:20, que es buena hora: hay menos gente y la luz de la tarde entra por los vitrales. A la Giralda no se sube por escalera sino por treinta y cinco rampas, hechas para subir a caballo, así que es mucho más fácil de lo que parece.'},
    {n:'Real Alcázar', d:'El palacio real en uso más antiguo de Europa, con siglos de capas encima: musulmán, mudéjar, gótico y renacentista. El Patio de las Doncellas y el Salón de Embajadores son lo mejor, y los jardines son enormes.', t:'visita', p:'€€', w:'https://www.alcazarsevilla.org/', tip:'Ya tenemos entrada para el viernes 23 a las 16:30. Con eso quedan dos horas largas hasta el cierre, que alcanzan bien. Los Baños de María de Padilla, la galería subterránea con el agua quieta, son el rincón más impresionante y el que sale en Juego de Tronos. Entrar directo a los jardines primero, mientras hay luz, y dejar los salones para el final.'},
    {n:'Plaza de España', d:'Un semicírculo enorme de ladrillo y azulejos con un canal navegable delante, construido para la Exposición Iberoamericana de 1929. Cada provincia de España tiene su banco de azulejos pintados.', t:'visita', tip:'Es gratis y está siempre abierta. La mejor hora es el atardecer, cuando el ladrillo se pone naranja, o a las nueve de la mañana, cuando no hay nadie. Se puede remar en una barquita por el canal por poca plata. Buscar el banco de Uruguay no tiene sentido, son solo provincias españolas, pero buscar el de la provincia de algún apellido de la familia sí.'},
    {ruta:['Barrio de Santa Cruz, Sevilla','Plaza de Doña Elvira, Sevilla','Calle Agua, Sevilla','Jardines de Murillo, Sevilla'], n:'Barrio de Santa Cruz', d:'La antigua judería, con callejones de dos metros, patios llenos de plantas y naranjos por todos lados. Está pegado a la Catedral y al Alcázar.', t:'visita', tip:'De día es un desfile de turistas; a las nueve de la noche, con las luces amarillas prendidas, es otro barrio y es cuando hay que caminarlo. Las naranjas de los árboles son amargas y no se comen: se exportan para hacer mermelada inglesa.'},
    {n:'Las Setas de la Encarnación', d:'La estructura de madera más grande del mundo, una especie de hongos gigantes en el medio de una plaza del casco antiguo. Arriba tiene una pasarela que serpentea entre las cúpulas con vista de toda la ciudad.', t:'visita', p:'€', tip:'La entrada a la pasarela cuesta poco e incluye una bebida. Es el mejor mirador de Sevilla y hay que subir al atardecer. Abajo, en el sótano, están las ruinas romanas que aparecieron al excavar.'},
    {ruta:['Puente de Isabel II, Sevilla','Calle Betis, Sevilla','Capilla de los Marineros, Sevilla'], n:'Triana', d:'El barrio del otro lado del río, de ceramistas, marineros y flamencos. La calle Betis, sobre la orilla, tiene la mejor vista de Sevilla: la Torre del Oro y la Giralda al fondo.', t:'visita', tip:'Es el paseo del martes. Cruzar por el puente de Isabel II al atardecer y volver de noche por la orilla. Los talleres de cerámica de la calle Alfarería y de San Jorge siguen funcionando y se puede entrar a mirar.'},
    {n:'Casa de Pilatos', d:'Un palacio del siglo XVI que mezcla mudéjar, gótico y renacentista, con un patio central de azulejos y estatuas romanas, y jardines interiores. Es de las cosas más lindas de Sevilla y casi nadie la visita.', t:'visita', p:'€', tip:'Es la alternativa perfecta para el sábado si nos quedamos. Se ve en una hora y está a diez minutos del centro. La planta alta se visita con guía y vale la pena.'},
    {n:'Parque de María Luisa', d:'El parque grande de la ciudad, pegado a la Plaza de España, con glorietas, estanques, fuentes y una sombra que en Sevilla se agradece.', t:'visita', tip:'La glorieta de Bécquer, con el árbol enorme y las tres figuras que representan las edades del amor, es el rincón más bonito. Se recorre bien en bicicleta.'},
    {n:'Torre del Oro y el río', d:'La torre almohade del siglo XIII a la orilla del Guadalquivir, que servía para cerrar el puerto con una cadena que cruzaba hasta la otra orilla.', t:'visita', tip:'Los paseos en barco por el río salen de acá al lado, duran una hora y son la manera más tranquila de ver la ciudad. Al atardecer es cuando mejor está.'},
    {n:'Hospital de los Venerables', d:'Un antiguo hospital para sacerdotes ancianos, con un patio hundido precioso y una iglesia cubierta de frescos. Alberga el Centro Velázquez, con obras del pintor, que era sevillano.', t:'visita', p:'€', tip:'Está en pleno Santa Cruz y es el sitio más tranquilo del barrio. Media hora y se sale con la sensación de haber encontrado algo que los demás no vieron.'}
  ]},

  {s:'Flamenco y noche', k:'evento', items:[
    {n:'Casa de la Memoria', d:'Un patio con cincuenta sillas, sin cena, sin micrófono y sin puesta en escena: cante, guitarra y baile a un metro de distancia. Es el que recomiendan los sevillanos.', t:'evento', p:'€€', serv:'mesa', res:'si', tip:'Se reserva online con días de anticipación porque entra muy poca gente. Hay dos o tres pases por noche y el espectáculo dura una hora. Es lo que hay que hacer el viernes saliendo del Alcázar.'},
    {n:'La Casa del Flamenco', d:'En un patio mudéjar del barrio de Santa Cruz, con la misma idea: espectáculo corto, íntimo y sin cena.', t:'evento', p:'€€', serv:'mesa', res:'si', tip:'Es la alternativa si la Casa de la Memoria está agotada. La acústica del patio de piedra es parte del asunto.'},
    {nota:1, n:'Qué flamenco evitar', d:'Los tablaos grandes con cena incluida son caros, la comida es mala y el espectáculo está armado para autobuses. El flamenco bueno es corto, incómodo y no tiene menú.', t:'evento', tip:'La otra punta son las peñas flamencas de barrio, donde toca gente de la zona para gente de la zona. No tienen horario fijo ni web, pero preguntando en un bar de Triana un viernes se averigua si hay algo esa noche.'},
    {nota:1, n:'La noche sevillana', d:'La cena arranca a las 21:30 y la noche recién a partir de las doce. La zona de la Alameda de Hércules es donde sale la gente de la ciudad, y es el barrio más suelto y menos turístico para tomar algo.', t:'evento', tip:'Es la zona para una noche con las compañeras de Vale, si sale el plan. Está a quince minutos caminando del centro y llena de bares con mesas afuera.'}
  ]},

  {s:'El sábado: quedarse o salir', k:'aire', items:[
    {m:'Mezquita-Catedral de Córdoba', n:'Córdoba en el día', d:'Cuarenta y cinco minutos en AVE desde Santa Justa. La Mezquita, con su bosque de ochocientas columnas y arcos de dos colores, es de las cosas más impresionantes que hay en Europa, y alrededor está la judería y el puente romano.', t:'aire', p:'€€', tip:'Es la excursión ambiciosa del sábado. Comprar el tren con anticipación en la web de Renfe, que sale mucho más barato. La Mezquita se puede visitar gratis muy temprano de mañana, entre las 8:30 y las 9:30 de lunes a sábado, sin acceso a algunas partes: vale la pena confirmarlo, porque encaja perfecto con llegar en el primer tren.'},
    {m:'Conjunto Arqueologico de Italica, Santiponce', n:'Itálica', d:'La primera ciudad romana fuera de Italia, a media hora de Sevilla, donde nacieron los emperadores Trajano y Adriano. Tiene un anfiteatro enorme, calles empedradas y mosaicos en el piso de las casas.', t:'aire', p:'€', tip:'Es la escapada corta: media mañana y de vuelta. Se llega en bus desde la estación de Plaza de Armas. El anfiteatro se usó como escenario en Juego de Tronos.'},
    {m:'Cadiz, Espana', n:'Cádiz', d:'Hora y media en tren. La ciudad habitada más antigua de Europa occidental, rodeada de mar por los tres lados, con playa urbana, un casco antiguo blanco y la mejor fritura de pescado de España.', t:'aire', tip:'Es la opción de sábado si lo que queremos es mar y no monumentos. En octubre la playa de la Caleta todavía se disfruta. La catedral tiene una torre con vista de toda la bahía.'},
    {nota:1, n:'Mi recomendación para el sábado', d:'Si la semana viene liviana, Córdoba, sin dudarlo: la Mezquita justifica el día entero y el tren lo hace fácil. Si la semana de Vale fue intensa, quedarse en Sevilla es mejor decisión que forzar una excursión.', t:'aire', tip:'La versión de quedarse tiene lo suyo: Casa de Pilatos a la mañana, el paseo en barco por el río a media tarde, el Parque de María Luisa con calma y una cena larga. Es la única noche del viaje sin nada al otro día.'}
  ]}
  ]
},
