{
  id:'lon', nav:'Londres', name:'Londres', plate:'Underground', accent:'#A83A5B', lt:'#F2A3BA', maps:'London',
  lede:'Se camina mucho mejor de lo que una se imagina. Covent Garden, Soho, Piccadilly, Trafalgar y Westminster están todos a menos de media hora a pie entre sí. Y los parques son gigantes: en noviembre quedan dorados y no hay nadie.',
  quick:[
    ['Se cena','Temprano: 18:30 a 20:00'],
    ['Tope diario','£8,90 zonas 1-2'],
    ['Cómo se paga','Tarjeta o celular, sin Oyster'],
    ['Noviembre','11° / 6°, llovizna'],
    ['Diciembre','8° / 4°, anochece 15:55']
  ],
  sections:[
  {s:'Cómo moverse', k:'mover', items:[
    {ruta:['Covent Garden, London','Soho Square, London','Piccadilly Circus, London','Trafalgar Square, London','Palace of Westminster, London'], n:'Caminen el centro', d:'Covent Garden → Soho → Piccadilly → Trafalgar → Westminster son 25 minutos en total. Casi todo lo que van a querer ver está en ese rectángulo.', t:'mover', tip:'Regla práctica: si Citymapper dice menos de 25 minutos a pie, caminen. El metro tarda lo mismo contando escaleras y esperas.'},
    {nota:1, n:'Metro (Tube)', d:'Para distancias largas y cuando llueve. Se paga apoyando la tarjeta bancaria o el celular: no hace falta comprar Oyster.', t:'mover', tip:'Cada una tiene que usar su propia tarjeta, siempre la misma, tocando al entrar y al salir. Si comparten una, el tope diario no se aplica bien y pagan de más.'},
    {nota:1, n:'Tope diario y semanal', d:'Una vez que gastaste £8,90 en un día dentro de las zonas 1-2, el resto del día es gratis. El tope semanal (lunes a domingo) es de £44,70.', t:'mover', tip:'Los topes de zonas 1-2 están congelados hasta marzo de 2027, así que estos son los números del viaje.'},
    {nota:1, n:'Autobús rojo', d:'£1,75 el viaje, con transbordo gratis dentro de la hora siguiente. Lento, pero desde el piso de arriba es un tour barato.', t:'mover', tip:'Las rutas 11, 15 y 24 pasan por casi todo lo turístico. Sentarse adelante arriba.'},
    {nota:1, n:'Uber Boat by Thames Clippers', d:'Catamaranes por el Támesis como transporte regular. Westminster a Greenwich es transporte y paseo a la vez.', t:'mover', w:'https://www.thamesclippers.com/', tip:'Tarifa aparte del metro, no entra en el tope diario. Aun así, vale la pena una vez.'},
    {nota:1, n:'Uber, Bolt y black cabs', d:'Guardalos para la noche tarde o para la lluvia con bolsas. El tráfico del centro y el peaje del centro hacen que casi siempre el metro gane.', t:'mover', tip:'El black cab acepta contactless y sabe llegar a cualquier lado sin GPS. Sale más caro pero de madrugada es lo más rápido.'},
    {nota:1, n:'Las horas pico, para esquivarlas', d:'De 8:00 a 9:30 y de 17:00 a 18:30 el metro va lleno y las tarifas suben. Ajusten los planes media hora y viajan sentadas y más barato.', t:'mover'}
  ]},
  {s:'Comer', k:'comer', items:[
    {nota:1, n:'Los horarios de comida en Londres', d:'Se cena temprano, y conviene tomárselo en serio. El límite práctico es sentarse <em>antes</em> de las 21:00: a esa hora ya cuesta bastante conseguir mesa, aunque la cocina siga abierta un rato más, y en los pubs se corta antes todavía. Si salen a buscar lugar a las 22:00, como se hace acá, terminan en una cadena.', t:'comer', tip:'Ayuda que en esos meses oscurece entre las 16:00 y las 17:00: el día se siente terminado mucho antes y sentarse a las 19:00 sale solo. El almuerzo va de 12:00 a 14:30, y los domingos el plato es el Sunday roast, que se come al mediodía y no de noche.'},
    {n:'Gordon Ramsay Street Burger', d:'Ramsay en versión accesible, sobre Maiden Lane, en pleno Covent Garden. Hamburguesa, papas y refresco con recarga por unas £15.', t:'comer', p:'€', a:'Maiden Lane, Covent Garden', w:'https://www.gordonramsayrestaurants.com/street-burger/', tip:'Está a tres minutos del mercado de Covent Garden. Se almuerza rápido y les queda la tarde entera.'},
    {n:'Five Guys Covent Garden', d:'En Long Acre. Papas ilimitadas en el vaso, toppings gratis y refrescos de máquina.', t:'comer', p:'€', a:'Long Acre', w:'https://www.fiveguys.co.uk/'},
    {n:'Five Guys Tower Bridge', d:'El de More London Riverside, sobre la orilla sur. Es la misma hamburguesa de siempre, pero desde la planta de arriba se come con el Tower Bridge enfrente de la ventana.', t:'comer', p:'€', a:'Unit 2, 2 More London Riverside, SE1', w:'https://www.fiveguys.co.uk/', tip:'Las mesas de arriba son las que tienen la vista y se ocupan primero. Si están llenas, se puede llevar y comer en Potters Fields Park, que es justo desde donde sale la foto del puente.'},
    {n:'Borough Market', d:'Acá se come lo mejor de Londres. Bread Ahead (donuts rellenos), Kappacasein (el toastie de queso), Padella (pasta fresca), ostras, quesos, todo para picar de pie.', t:'comer', p:'€', tip:'Martes a jueves está lleno pero se puede. Sábado es imposible. Cierra temprano: ir antes de las 16:00.'},
    {n:'Dishoom Covent Garden', d:'Café iraní de Bombay recreado con una obsesión por el detalle. El bacon naan roll del desayuno es de culto; el black daal se cocina 24 horas.', t:'comer', p:'€€', w:'https://www.dishoom.com/', tip:'No reservan mesa para dos en horario pico. Sobre las 17:30 todavía se entra; más tarde conviene anotarse y esperar en el bar del sótano con un chai.'},
    {n:'Flat Iron', d:'Un solo corte de carne a precio fijo, con ensalada y papas aparte. Sale la mitad que cualquier steakhouse del centro.', t:'comer', p:'€€', w:'https://flatironsteak.co.uk/'},
    {n:'The Churchill Arms', d:'El pub más florido de Londres, en Kensington. Por fuera es una explosión de macetas; por dentro sirven comida tailandesa desde 1990.', t:'comer', p:'€€', tip:'En diciembre lo cubren de árboles de Navidad. Es una de las fachadas más fotografiadas de la ciudad.'},
    {n:'Tattu London', d:'Cocina china contemporánea en The Now Building, junto a Tottenham Court Road. El cerezo en flor que atraviesa el salón es el motivo por el que la gente reserva.', t:'comer', p:'€€€', a:'The Now Building, Denmark Street', w:'https://tattu.co.uk/locations/tattu-london/', tip:'Pidan mesa cerca del cerezo al reservar. Los postres están pensados para la foto tanto como para comerse.'},
    {m:'Sketch, Conduit Street, London', n:'Sketch, The Gallery', d:'El salón rosa con las orejas de conejo, uno de los interiores más fotografiados de Londres. Precio alto, pero la experiencia es el lugar.', t:'comer', p:'€€€', w:'https://sketch.london/', tip:'Si el precio de la cena asusta, el afternoon tea sale menos y se accede al mismo salón. Los baños con forma de huevo son parte de la visita.'},
    {n:'Duck & Waffle', d:'Piso 40, abierto 24 horas, con vista al río. El plato que le da nombre (pato confitado sobre waffle con huevo y jarabe de arce) es el motivo.', t:'comer', p:'€€€', w:'https://duckandwaffle.com/', tip:'La mejor jugada: desayunar ahí a las 8:00. Sale mucho menos que la cena y la vista es la misma.'}
  ]},
  {s:'Café y hora del té', k:'cafe', items:[
    {m:'Fortnum & Mason, Piccadilly, London', n:'Fortnum & Mason, Diamond Jubilee Tea Salon', d:'El afternoon tea clásico, en la tienda de ultramarinos de la reina desde 1707. Pianista, scones calientes y té servido por alguien que sabe.', t:'cafe', p:'€€€', w:'https://www.fortnumandmason.com/', tip:'Reservar con semanas. En diciembre la tienda entera se decora y vale la pena bajar al sótano de los dulces.'},
    {n:'The Wolseley', d:'Gran café al estilo vienés en Piccadilly. Desayuno, té o cena en un salón que parece de otra época, sin el precio del hotel de lujo.', t:'cafe', p:'€€', w:'https://www.thewolseley.com/'},
    {n:'Pret A Manger', d:'La red de rescate. Café decente, sándwiches frescos y sopa caliente en cada esquina, por una fracción de lo que cuesta sentarse.', t:'cafe', p:'€', w:'https://www.pret.co.uk/', tip:'Tienen suscripción mensual de café con varias bebidas por día. Si toman tres cafés diarios entre las dos, se paga solo en cuatro días.'},
    {n:'Monmouth Coffee', d:'El tostador que enseñó a Londres a tomar café. El local de Borough, junto al mercado, es diminuto y siempre tiene cola.', t:'cafe', p:'€', w:'https://www.monmouthcoffee.co.uk/'},
    {n:'Bar Italia', d:'Soho, abierto casi 24 horas desde 1949. Espresso de pie en la barra, fórmica y fotos de boxeadores en la pared.', t:'cafe', p:'€', a:'Frith Street, Soho'},
    {n:'Maison Bertaux', d:'La pastelería más vieja de Londres, de 1871, en Greek Street. Desordenada, sin pretensiones y con los mejores hojaldres del barrio.', t:'cafe', p:'€'}
  ]},
  {s:'Cócteles', k:'coctel', items:[
    {n:'Connaught Bar', d:'Mayfair. El carrito del martini se acerca a la mesa y lo preparan delante de ustedes, eligiendo los bitters uno a uno. Es de los mejores bares del mundo, y se nota en la cuenta.', t:'coctel', p:'€€€', w:'https://www.the-connaught.co.uk/'},
    {n:'Nightjar', d:'Speakeasy en Shoreditch con jazz en vivo y una carta de cócteles que parece un libro ilustrado. Se baja por una puerta sin cartel.', t:'coctel', p:'€€', w:'https://barnightjar.com/', tip:'Reservar. Sin reserva no entran, y con música en vivo hay recargo por cubierto.'},
    {n:'Lyaness', d:'En el Sea Containers, sobre el South Bank, con ventanales al Támesis. Ryan Chetiyawardana reinventa la carta entera cada año.', t:'coctel', p:'€€', w:'https://lyaness.com/'},
    {n:'Swift', d:'Soho. Arriba, cócteles cortos y rápidos antes de cenar; abajo, un sótano oscuro con 250 whiskies y música en vivo.', t:'coctel', p:'€€'},
    {m:'The Savoy, London', n:'The American Bar at The Savoy', d:'El bar de hotel más antiguo de Londres en servicio continuo. Pianista, chaquetas blancas y clásicos hechos como corresponde.', t:'coctel', p:'€€€', w:'https://www.thesavoylondon.com/'}
  ]},
  {s:'Al aire libre', k:'aire', items:[
    {ruta:['Italian Gardens, Hyde Park, London','The Serpentine, Hyde Park, London','Kensington Palace, London'], n:'Hyde Park y Kensington Gardens', d:'350 hectáreas en el centro. El paseo bueno: Italian Gardens al norte, borde de la Serpentine, Kensington Palace y salida por Kensington Gardens.', t:'aire', tip:'En noviembre los plátanos están amarillos y hay muy poca gente entre semana.'},
    {n:'St James’s Park', d:'De los parques reales, el más lindo. Desde el puente del lago sale la mejor foto del Palacio de Buckingham, con el London Eye asomando detrás.', t:'aire', tip:'Los pelícanos comen a las 14:30 cerca de Duck Island. Están ahí desde 1664.'},
    {n:'Primrose Hill', d:'Una loma justo detrás de Regent’s Park. Todo el skyline de Londres de un vistazo, gratis y sin cola.', t:'aire', tip:'Ir 40 minutos antes del atardecer y combinar con un paseo por Regent’s Park.'},
    {m:'Royal Observatory Greenwich, London', n:'Greenwich Park y Royal Observatory', d:'El meridiano cero, la vista sobre Canary Wharf y el Old Royal Naval College abajo. Media jornada completa.', t:'aire', tip:'Ir en el Uber Boat by Thames Clippers desde Westminster: el trayecto por el río es el paseo.'},
    {m:'Parliament Hill, Hampstead Heath, London', n:'Hampstead Heath y Parliament Hill', d:'Bosque de verdad dentro de la ciudad, con la panorámica más amplia. Menos turística que Primrose Hill.', t:'aire', tip:'Terminar en el pueblo de Hampstead o en el Spaniards Inn, un pub de 1585.'},
    {ruta:['Westminster Bridge, London','Southbank Centre, London','Tate Modern, London','Borough Market, London'], n:'Paseo por el South Bank', d:'De Westminster a Borough Market por la orilla sur: London Eye, Southbank Centre, puestos de libros bajo Waterloo Bridge, Tate Modern y el Millennium Bridge. Una hora y media sin apurarse.', t:'aire', tip:'De noche es mejor: todo iluminado y con el mercado de invierno en el camino.'},
    {ruta:['Marble Arch, London','Oxford Circus, London','New Bond Street, London','Piccadilly Circus, London'], n:'Oxford, Regent y Bond Street', d:'Oxford Street es la calle comercial más transitada de Europa, Regent Street hace una curva enorme de fachadas de piedra, y entre las dos queda Bond Street, la del lujo: Cartier, Prada, Tiffany, Chanel, Louis Vuitton. En noviembre y diciembre las tres están iluminadas y el paseo no cuesta nada.', t:'aire', tip:'El recorrido que funciona: empezar en Marble Arch, bajar Oxford Street, doblar por New Bond Street hasta salir a Piccadilly. Ahí está la Burlington Arcade, una galería de 1819 con vidrieras de joyerías que en Navidad se llena de guirnaldas.'},
    {n:'Belgravia y Chelsea', d:'Fachadas blancas, columnas y puertas negras: el Londres más elegante y más silencioso. Elizabeth Street y Motcomb Street tienen tiendas chicas y floristerías, y montan las decoraciones navideñas más cuidadas de la ciudad. Bajando hacia Chelsea está Bywater Street, la de las casitas de colores.', t:'aire', tip:'Está a diez minutos a pie de la estación de Victoria, así que entra en cualquier tarde suelta. De noche, con las luces de Elizabeth Street prendidas, no hay casi nadie.'},
    {ruta:['Little Venice, London','Camden Market, London'], n:'Regent’s Canal: Little Venice a Camden', d:'45 minutos de camino de sirga entre casas flotantes, sauces y el zoo. Termina en Camden Market.', t:'aire'},
    {n:'Columbia Road Flower Market', d:'Solo los domingos, de 8:00 a 15:00. Una calle victoriana entera de flores, con cafés y tiendas chicas alrededor.', t:'aire', tip:'La mejor hora es antes de las 10:00, o después de las 14:00, que es cuando rematan a precio de saldo.'},
    {n:'Sky Garden', d:'Jardín tropical en el piso 35, con vista de 360°. Es gratis, pero hay que reservar horario con semanas de antelación.', t:'aire', w:'https://skygarden.london/', tip:'Los horarios se liberan los lunes. Si no lo consiguen, prueben reservando en el bar en vez de la entrada general.'}
  ]},
  {s:'Imprescindibles y dónde sacar la foto', k:'visita', items:[
    {n:'Tower Bridge', d:'El puente más fotografiado de la ciudad. Se puede subir a la pasarela de vidrio, pero la foto está abajo.', t:'visita', tip:'Foto: desde Shad Thames y Butler’s Wharf, en la orilla sur, o desde Potters Fields Park. Desde el propio puente no se ve el puente.'},
    {m:'Big Ben, London', n:'Big Ben, la torre del reloj', d:'La Torre Isabel, restaurada y otra vez dorada, con las campanadas cada hora. Subir los 334 escalones está reservado a residentes en el Reino Unido, que lo piden por su diputado, así que para ustedes es visita de afuera. Tampoco importa: por fuera es donde está la foto.', t:'visita', tip:'El mejor ángulo no es desde el puente. Bajando la escalera del lado sur, el de St Thomas, hay un pasaje que cruza por debajo del puente: al salir, la torre queda enmarcada por el arco, con el río delante y casi nadie alrededor. La luz de ahí funciona de mañana. Desde la mitad sur del puente sale el clásico abierto con el Parlamento entero, y la cabina roja en primer plano está en Great George Street con Parliament Square.'},
    {n:'Abadía de Westminster', d:'Mil años de coronaciones, bodas y tumbas reales bajo un gótico altísimo, con Newton, Darwin y el Rincón de los Poetas adentro. Abre de lunes a viernes de 9:30 a 15:30 y los sábados hasta las 15:00. Los domingos está cerrada al turismo, porque ese día funciona como iglesia. Hora y media larga de visita.', t:'visita', p:'€€', a:'20 Deans Yard', w:'https://www.westminster-abbey.org/', tip:'Hay una forma de entrar sin pagar: el <em>Evensong</em>, el oficio cantado por el coro al final de la tarde entre semana. No se recorre la abadía, pero se entra y se escucha el coro bajo esa bóveda. Para la visita normal, la mejor hora es la de apertura. Y conviene confirmar en la web el día antes: al ser una iglesia en uso, cierra sin aviso por servicios especiales.'},
    {m:'Palace of Westminster, London', n:'Parlamento, el Palacio de Westminster', d:'El palacio por dentro, que es visita aparte de la abadía y de la torre: el Westminster Hall con su techo de madera del siglo XIV, el Central Lobby y las dos cámaras, la de los Comunes en verde y la de los Lores en rojo. Recorrido guiado de 90 minutos, en inglés.', t:'visita', p:'€€', w:'https://www.parliament.uk/visiting/', tip:'Los sábados hay visitas todo el año, de 9:30 a 16:30, y cuando el Parlamento entra en receso se suman días entre semana. En noviembre y en diciembre suele haber receso, así que vale mirar el calendario en tickets.parliament.uk cerca de la fecha. Se reserva online y hay que llegar 20 minutos antes por el control de seguridad. Es un edificio en funcionamiento: a veces cancelan con poco aviso.'},
    {n:'London Eye', d:'30 minutos de vuelta. Vale más de noche, con la ciudad encendida.', t:'visita', p:'€€', w:'https://www.londoneye.com/', tip:'Foto: desde el Golden Jubilee Bridge, con el río abajo. Reservar online sale bastante más barato que en taquilla.'},
    {n:'Covent Garden', d:'El mercado cubierto, el Apple Market, los músicos clásicos del patio bajo y las tiendas alrededor. En diciembre, el árbol de 17 metros y las campanas doradas colgando.', t:'visita', tip:'Neal’s Yard, a cinco minutos, es un patio diminuto de fachadas de colores. Entrada por un pasaje entre Monmouth Street y Shorts Gardens.'},
    {ruta:['Piccadilly Circus, London','Carnaby Street, London','Soho Square, London'], n:'Piccadilly Circus, Soho y Carnaby Street', d:'Las pantallas de Piccadilly, los callejones de Soho y las luces de Carnaby, que cada año monta una instalación distinta sobre la calle.', t:'visita'},
    {m:'Leicester Square, London', n:'Leicester Square: las estatuas y M&M’s World', d:'La plaza tiene un circuito de estatuas de cine repartidas entre los bancos: Harry Potter sobre la escoba, Paddington en su banquito, Mary Poppins, Mr. Bean, Bugs Bunny, Wonder Woman, Gene Kelly. En una esquina está M&M’s World, cuatro plantas con un muro entero de dispensadores por color y las banderas en la fachada. Siempre hay un gentío.', t:'visita', tip:'Las estatuas son gratis y hay un plano en la plaza que las ubica. Enfrente está la tienda de LEGO, con un Big Ben de piezas de tamaño absurdo y un vagón de metro armado.'},
    {n:'Trafalgar Square', d:'La National Gallery de fondo y, desde principios de diciembre, el abeto que Noruega regala a Londres cada año desde 1947.', t:'visita', tip:'Hay villancicos casi todas las tardes de diciembre al pie del árbol.'},
    {n:'St Paul’s Cathedral', d:'La cúpula de Wren. Se puede subir a la Whispering Gallery y a la linterna.', t:'visita', p:'€€', w:'https://www.stpauls.co.uk/', tip:'Foto gratis y mejor: la terraza del último piso de One New Change, justo enfrente. La cúpula queda a la altura de los ojos.'},
    {m:'Portobello Road Market, London', n:'Notting Hill y Portobello Road', d:'Las casas de colores pastel y el mercado. Los sábados es el día grande del mercado; el resto de la semana, la calle está tranquila para caminarla.', t:'visita', tip:'Las fachadas más fotogénicas están en Lancaster Road y en St Luke’s Mews.'},
    {ruta:['280 Westbourne Park Road, London','The Notting Hill Bookshop, London'], n:'Notting Hill de película: la puerta azul y la librería', d:'La casa de la puerta azul donde vivía el personaje de Hugh Grant está sobre Westbourne Park Road. Es una casa particular y vive gente adentro, así que la foto se saca desde la vereda de enfrente. La librería de viajes de la película no existe como tal, pero The Notting Hill Bookshop, en Blenheim Crescent, es la que la inspiró y sigue abierta.', t:'visita', tip:'Las dos están a diez minutos de Portobello Road, así que entran en el mismo paseo. La puerta pasó por varios colores desde la película y hoy vuelve a ser azul.'},
    {n:'Leadenhall Market', d:'Mercado victoriano de hierro y vidrio verde y burdeos, en plena City. Se usó como Callejón Diagon en Harry Potter.', t:'visita', tip:'Entre semana a la hora del almuerzo está lleno de gente de traje; el domingo está vacío y lo tienen para ustedes.'},
    {m:'Platform 9 3/4, Kings Cross Station, London', n:'Andén 9¾, King’s Cross', d:'Medio carrito de equipaje empotrado en la pared de la estación, con bufanda de la casa que elijan y un fotógrafo oficial. Al lado está la tienda de la película.', t:'visita', tip:'La cola puede ser larga. Se puede sacar la foto con el celular gratis mientras se espera: la del fotógrafo se paga aparte y no hace falta.'},
    {m:'Warner Bros. Studio Tour London', n:'Warner Bros. Studio Tour: la fábrica de Harry Potter', d:'En Leavesden, a las afueras. No es un parque de atracciones: son los decorados originales, el Gran Comedor, el Callejón Diagon, la sala común de Gryffindor, el bosque y el Expreso de Hogwarts de verdad. Entre tres y cuatro horas adentro.', t:'visita', p:'€€€', w:'https://www.wbstudiotour.co.uk/', tip:'Solo se entra con entrada reservada con fecha y hora, y se agota con meses. Se llega en tren desde Euston hasta Watford Junction, unos 20 minutos, y de ahí sale un micro. De noviembre a enero montan Hogwarts in the Snow, con el castillo nevado y el Gran Comedor puesto para el banquete de Navidad, así que las fechas del viaje caen bien.'},
    {ruta:['British Museum, London','National Gallery, London'], n:'British Museum y National Gallery', d:'Los dos son gratis y los dos son enormes. En un día de lluvia salvan la jornada.', t:'visita', w:'https://www.britishmuseum.org/', tip:'No intenten verlo todo. Elijan tres salas y salgan a tomar algo.'},
    {nota:1, n:'Museos: cuáles valen la pena y cuáles se pueden saltar', d:'Casi todos los museos grandes de Londres son gratis, así que la pregunta no es la plata sino el tiempo. Los que rinden en una visita corta son la National Gallery, donde Van Gogh, Turner y Vermeer están casi en salas seguidas, y el British Museum, yendo derecho a la piedra Rosetta, los mármoles del Partenón y Egipto. El de Historia Natural vale más por el edificio que por lo que hay adentro, y suele tener cola larga.', t:'visita', tip:'Si el tiempo aprieta, el que menos se extraña es el Victoria & Albert, que es enorme y muy específico. Y una que casi nadie visita: la Wallace Collection, un palacete con cuadros y armaduras y un patio vidriado para tomar el té. Gratis y se ve en media hora.'},
    {m:'Buckingham Palace, London', n:'Cambio de guardia, Buckingham Palace', d:'A las 11:00, en días alternos en invierno. Dura 45 minutos y se llena.', t:'visita', tip:'Mejor plan: pararse en el Victoria Memorial o sobre The Mall para ver pasar la tropa, en vez de pelear por la reja.'}
  ]},
  {s:'Navidad en Londres', k:'navidad', items:[
    {n:'Hyde Park Winter Wonderland', d:'Del 19 de noviembre de 2026 al 3 de enero de 2027, todos los días salvo el 25 de diciembre. Más de 150 atracciones, pista de hielo, norias, cervecería bávara y el recorrido de esculturas de hielo.', t:'navidad', w:'https://hydeparkwinterwonderland.com/', tip:'Hace falta entrada con horario reservado. De lunes a jueves durante noviembre la entrada sale £1: ese es el momento de ir.'},
    {m:'Southbank Centre, London', n:'Southbank Centre Winter Market', d:'Desde el 3 de noviembre, sobre la orilla del Támesis bajo el Hungerford Bridge. Casetas de madera, vino caliente y comida callejera. Entrar es gratis.', t:'navidad', tip:'Es el mejor combinado con un paseo nocturno por el South Bank. Está abierto hasta tarde.'},
    {m:'Covent Garden, London', n:'Luces de Covent Garden', d:'Un abeto de casi 17 metros, 40 campanas doradas gigantes con moños y bolas de espejos girando sobre el mercado.', t:'navidad', tip:'El encendido suele ser a mediados de noviembre. Es de los conjuntos mejor montados de la ciudad.'},
    {ruta:['Oxford Circus, London','Regent Street, London','Carnaby Street, London'], n:'Luces de Oxford, Regent y Carnaby Street', d:'El encendido de Oxford Street abre la temporada a principios de noviembre. Regent Street pone sus ángeles gigantes y Carnaby, una instalación distinta cada año.', t:'navidad', tip:'Se encienden alrededor de las 15:00 y quedan hasta las 23:00. En diciembre anochece a las 16:00, así que hay luces casi toda la tarde.'},
    {m:'Somerset House, London', n:'Patinaje en Somerset House', d:'La pista más elegante de Londres, en el patio neoclásico de Somerset House, con un árbol enorme en el centro y DJ algunas noches.', t:'navidad', p:'€€', w:'https://www.somersethouse.org.uk/', tip:'Alternativas igual de lindas: la pista del Natural History Museum y la de Hampton Court Palace.'},
    {m:'Kew Gardens, London', n:'Christmas at Kew', d:'Recorrido nocturno de más de tres kilómetros por los Kew Gardens iluminados, con instalaciones de luz, fuego y música.', t:'navidad', p:'€€', w:'https://www.kew.org/', tip:'Se agota con mucha antelación y está lejos del centro (Kew Gardens, línea District). Reservar antes de viajar.'}
  ]},
  {s:'Compras y mercadillos', k:'compra', items:[
    {n:'Bicester Village', d:'El outlet de firmas más famoso del Reino Unido, con más de 150 tiendas. Chiltern Railways llega directo desde Marylebone en unos 54 minutos.', t:'compra', w:'https://www.bicestervillage.com/', tip:'Ida y vuelta desde unas £31,60 en horario valle. Salen trenes cada media hora. Si van, que sea la semana del Black Friday: el descuento se suma al del outlet.'},
    {n:'Portobello Road Market', d:'Los sábados, de 9:00 a 19:00. Antigüedades en el tramo sur, ropa vintage y comida hacia el norte, bajo el Westway.', t:'compra', tip:'La parte buena de vintage está pasando el paso bajo nivel, donde ya casi no llega el turista.'},
    {m:'Old Spitalfields Market, London', n:'Brick Lane y Spitalfields', d:'Domingo. Brick Lane es vintage por kilo, discos y curry; Spitalfields, un mercado cubierto con diseño independiente. Están a cinco minutos uno del otro.', t:'compra'},
    {n:'Camden Market', d:'Abierto todos los días. Ropa alternativa, cuero, discos y una zona de comida callejera enorme junto al canal.', t:'compra', tip:'Llegar caminando por el Regent’s Canal desde Little Venice convierte la compra en un paseo.'},
    {ruta:['Daunt Books, Marylebone High Street, London','Hatchards, Piccadilly, London'], n:'Librerías que son visita: Daunt y Hatchards', d:'Daunt, en Marylebone High Street, es una galería eduardiana de roble con claraboya y balcones, con los libros ordenados por país. Hatchards, en Piccadilly, abrió en 1797 y es la librería más antigua del Reino Unido: escalera de caracol y cinco plantas.', t:'compra', tip:'Las dos venden bolsas de tela que salen baratas y son mejor recuerdo que un imán. Hatchards está pegada a Fortnum & Mason, así que se hacen juntas.'},
    {nota:1, n:'Charity shops de Marylebone y Notting Hill', d:'Las tiendas benéficas de los barrios ricos reciben ropa de marca a precios de nada. Marylebone High Street y Notting Hill son las mejores zonas.', t:'compra', p:'€', tip:'Es la forma más barata de comprar bien en Londres, y nadie se la cuenta a los turistas.'},
    {n:'Primark Marble Arch', d:'Cinco plantas para básicos de invierno a precio mínimo: térmicas, medias de lana, gorros, guantes.', t:'compra', p:'€', tip:'Si el frío las agarra desprevenidas el primer día, esto resuelve por menos de £30 entre las dos.'},
    {ruta:['Selfridges, Oxford Street, London','Liberty London'], n:'Selfridges y Liberty', d:'Aunque no compren: los escaparates navideños de Selfridges (Oxford Street) y el edificio Tudor de Liberty son visita en sí mismos.', t:'compra', tip:'La sección de Navidad de Selfridges abre en agosto. En noviembre está en su esplendor.'}
  ]},
  {s:'Espectáculos de noviembre y diciembre', k:'evento', items:[
    {nota:1, n:'West End: la temporada', d:'Avenue Q vuelve al Shaftesbury desde el 21 de noviembre, Jesus Christ Superstar sigue en el Theatre Royal Drury Lane, Paddington The Musical en el Savoy y Kinky Boots en el London Coliseum. Más los fijos: El Rey León, Hamilton, Los Miserables, Wicked.', t:'evento', p:'€€', w:'https://www.londontheatre.co.uk/', tip:'Consultar la cartelera cerca de la fecha: los elencos y los títulos rotan.'},
    {m:'TKTS Leicester Square, London', n:'TKTS en Leicester Square', d:'La caseta oficial de entradas de último minuto. Descuentos reales para funciones del mismo día.', t:'evento', w:'https://officiallondontheatre.com/tkts/', tip:'Abre a las 10:00 y esa primera hora es la que tiene mejor oferta para las funciones de esa noche. La app TodayTix hace lo mismo desde el celular y sortea entradas baratas.'},
    {nota:1, n:'Pantomime', d:'La tradición navideña británica: cuento infantil, humor de doble sentido para adultos, actores travestidos y el público gritando. Rarísimo y muy divertido.', t:'evento', p:'€€', tip:'El del Lyric Hammersmith y el del London Palladium son los que valen la pena.'},
    {m:'Royal Albert Hall, London', n:'Conciertos de Navidad en el Royal Albert Hall', d:'Carols by Candlelight, el Mesías de Händel y la banda sonora de películas con orquesta en vivo, durante todo diciembre.', t:'evento', p:'€€', w:'https://www.royalalberthall.com/'},
    {nota:1, n:'Cartelera de conciertos', d:'Para lo que se anuncie más cerca de la fecha: Songkick y See Tickets listan todo lo que pasa por O2, Roundhouse, Brixton Academy y las salas chicas.', t:'evento', w:'https://www.songkick.com/metro-areas/24426-uk-london'}
  ]}
  ]
},
