{
  id:'par', nav:'París', name:'París', plate:'Métropolitain', accent:'#6B5B95', lt:'#C0B2E2', maps:'Paris',
  lede:'Es la que mejor se camina del viaje. En noviembre los jardines están amarillos, las terrazas tienen estufa y las colas de los museos se parten al medio. Y desde enero de 2026 se terminaron las zonas: un billete las lleva a cualquier lado.',
  quick:[
    ['Se cena','19:30 a 22:00'],
    ['Billete sencillo','€2,55, todas las zonas'],
    ['Tarjeta','Navigo Easy €2, o el celular'],
    ['Noviembre','11° / 6°, gris'],
    ['Diciembre','8° / 3°, anochece 16:55']
  ],
  sections:[
  {s:'Cómo moverse', k:'mover', items:[
    {nota:1, n:'El billete, desde 2026', d:'Desde el 1 de enero de 2026 desaparecieron las zonas: €2,55 lleva a cualquier lado dentro de las cinco zonas, aeropuertos aparte.', t:'mover', tip:'Cargarlo en el celular con la app Île-de-France Mobilités o Bonjour RATP evita colas de máquina. Si no, la tarjeta Navigo Easy cuesta €2 y se recarga.'},
    {nota:1, n:'Metro para casi todo', d:'Las líneas 1, 4, 6 y 9 cubren casi todo lo turístico. Las estaciones están tan juntas que rara vez se camina más de cinco minutos hasta una.', t:'mover', tip:'La línea 6 va elevada en buena parte del recorrido y cruza el Sena por el Pont de Bir-Hakeim con la Torre Eiffel a la vista. Es un mirador por €2,55.'},
    {ruta:['Musée du Louvre, Paris','Jardin des Tuileries, Paris','Place de la Concorde, Paris','Arc de Triomphe, Paris'], n:'Caminen el eje central', d:'Louvre → Tuileries → Concorde → Champs-Élysées → Arco de Triunfo son unos 45 minutos, todo en línea recta y todo iluminado en diciembre.', t:'mover'},
    {nota:1, n:'Aeropuertos', d:'RER B directo a Charles de Gaulle; Orlyval o el Orlybus para Orly. La línea 14 del metro también llega a Orly.', t:'mover', tip:'El RER B a CDG tarda 35 minutos y sale mucho más barato que un taxi, pero con equipaje grande y en hora punta es incómodo.'},
    {nota:1, n:'Uber, Bolt y G7', d:'Útiles de noche tarde (el metro cierra sobre la 1:15, y las 2:15 viernes y sábados) o con lluvia y bolsas. El tráfico de París es denso: en el centro el metro casi siempre gana.', t:'mover'},
    {nota:1, n:'Huelgas: comprobar antes de salir', d:'Las huelgas puntuales de transporte son parte de la vida parisina. Nunca cancelan el viaje, pero sí pueden dejar una línea sin servicio media jornada.', t:'mover', tip:'Mirar la app antes de salir del hotel cada mañana. Diez segundos que evitan una hora perdida.'}
  ]},
  {s:'Comer', k:'comer', items:[
    {nota:1, n:'Los horarios de comida en París', d:'El almuerzo va de 12:00 a 14:00 y la cena arranca sobre las 19:30 o 20:00, con el último pedido cerca de las 22:00. Entre las 14:30 y las 19:00 la mayoría de las cocinas cierran del todo.', t:'comer', tip:'Si les agarra hambre en ese hueco, las brasseries con <em>service continu</em> sirven a cualquier hora, y siempre quedan las panaderías y las creperías. Vale la pena reservar para la cena: los bistrós buenos son chicos y se llenan.'},
    {n:'Bouillon Chartier', d:'Comedor de 1896 con techos altos, camareros de chaleco que anotan en el mantel y platos franceses clásicos entre €10 y €14. Se comparte mesa con desconocidos.', t:'comer', p:'€', w:'https://www.bouillon-chartier.com/', tip:'No reservan: hay cola, pero avanza rápido porque la rotación es brutal. El de Pigalle suele tener menos espera que el de Montmartre.'},
    {nota:1, n:'Crêperie de barrio', d:'La calle Montparnasse (entre Odessa y Vandamme) es el pequeño barrio bretón de París: una crepería detrás de otra. Galette salada de trigo sarraceno primero, crepe dulce después, y sidra en tazón.', t:'comer', p:'€', tip:'La regla bretona: la galette salada va con sidra, no con vino. En el Marais, Breizh Café es la versión más cuidada y también más cara.'},
    {n:'L’As du Fallafel', d:'Rue des Rosiers, en el Marais. El falafel más famoso de París, para llevar por la ventanilla y comer caminando.', t:'comer', p:'€', tip:'Cierra los sábados por el shabat. La cola de la ventanilla va mucho más rápido que la mesa.'},
    {nota:1, n:'Crepes de la calle en Montmartre', d:'Alrededor de la Place du Tertre y bajando por la Rue Norvins hay puestos y ventanillas de crepes hechas en el momento: azúcar y limón, Nutella, o saladas de jamón y queso. Se comen calientes caminando, que en noviembre es medio el punto.', t:'comer', p:'€', tip:'Los de la plaza son los más caros. Bajando una cuadra por cualquier calle lateral cuestan la mitad y están igual de buenos.'},
    {n:'Le Saint-Gervais', d:'96 rue Vieille du Temple, en el Marais. Una hamburguesa jugosa de verdad en un bistró de esquina, sin la puesta en escena de las cadenas.', t:'comer', p:'€€', a:'96 rue Vieille du Temple', tip:'Es un bistró de barrio, no un templo gastronómico: la gracia es sentarse en la terraza con estufa y ver pasar el Marais.'},
    {n:'Brasserie Le Bourbon', d:'1 Place du Palais Bourbon, detrás de la Asamblea Nacional. Abierta desde 1854, con terraza orientada al oeste. Cocina francesa correcta a precio razonable, y la crème brûlée por la que van.', t:'comer', p:'€€', a:'1 Place du Palais Bourbon, 7e', w:'https://www.brasserie-bourbon.fr/', tip:'Está a diez minutos de los Inválidos: combina perfecto con AURA. Reservar mesa en la terraza si hay sol.'},
    {n:'Le Comptoir du Relais', d:'Bistró de Yves Camdeborde en Odéon. A mediodía se come a la carta sin reserva; de noche es menú fijo y hay que reservar con meses.', t:'comer', p:'€€'},
    {n:'Le Train Bleu', d:'Dentro de la Gare de Lyon, en el primer piso del Hall 1. Un comedor de 1901 construido para la Exposición Universal, con 41 pinturas en paredes y techos y dos salas declaradas monumento histórico.', t:'comer', p:'€€€', a:'Gare de Lyon, Hall 1, 1er piso', w:'https://www.le-train-bleu.com/', tip:'Abre todos los días de 11:15 a 14:30 y de 19:00 a 22:30; el bar, de 7:30 a 22:30. Solo se reserva por su web o TheFork. Si el menú asusta, tomar algo en el bar da acceso al mismo salón por mucho menos.'},
    {n:'Girafe', d:'En el Palais de Chaillot, con la Torre Eiffel enmarcada en el ventanal. Pescado y mariscos en un art déco impecable.', t:'comer', p:'€€€', tip:'Pedir mesa junto a la ventana al reservar, o la vista se la queda otro.'}
  ]},
  {s:'Café, macarons y chocolate', k:'cafe', items:[
    {n:'Ladurée', d:'Los macarons de siempre y un salón de té de terciopelo verde y dorado. El de la Rue Bonaparte, en Saint-Germain, es más bonito y menos turístico que el de los Campos Elíseos.', t:'cafe', p:'€€', w:'https://www.laduree.fr/', tip:'La caja de macarons surtida aguanta el viaje en el bolso toda la tarde. Los clásicos: pistacho, rosa y caramelo con sal.'},
    {n:'Angelina', d:'226 rue de Rivoli, frente a las Tuileries. El chocolate caliente "l’Africain" es tan espeso que viene con un jarrito de crema aparte. El pastel Mont-Blanc es el otro motivo.', t:'cafe', p:'€€', a:'226 rue de Rivoli', w:'https://angelina-paris.fr/', tip:'La cola de la mañana es larga. Se puede comprar el chocolate para llevar en el mostrador, o ir al local del Musée du Luxembourg, que casi nadie conoce.'},
    {n:'Carette', d:'Dos locales, los dos perfectos: uno en la Place du Trocadéro y otro en la Place des Vosges. Pastelería clásica, chocolate caliente y terraza con estufa.', t:'cafe', p:'€€', tip:'El del Trocadéro es la parada natural después de fotografiar la Torre Eiffel.'},
    {n:'Pierre Hermé', d:'El otro gran nombre del macaron, más audaz que Ladurée. El Ispahan (rosa, lichi y frambuesa) es su clásico.', t:'cafe', p:'€€', w:'https://www.pierreherme.com/'},
    {m:'Café de Flore, Paris', n:'Café de Flore y Les Deux Magots', d:'Los dos cafés literarios de Saint-Germain, uno al lado del otro. Caros y llenos de turistas, pero sentarse en la terraza acristalada con estufa una tarde de noviembre tiene su sentido.', t:'cafe', p:'€€'},
    {n:'Du Pain et des Idées', d:'Panadería junto al Canal Saint-Martin, con el interior de 1889 intacto. El escargot de pistacho y chocolate es lo que hay que pedir.', t:'cafe', p:'€', tip:'Cierra los fines de semana. Ir entre semana por la mañana, temprano.'}
  ]},
  {s:'Cócteles', k:'coctel', items:[
    {n:'Little Red Door', d:'En el Marais, entre los mejores bares del mundo. Cada carta se construye alrededor de un concepto y viene ilustrada por artistas.', t:'coctel', p:'€€', w:'https://www.lrdparis.com/'},
    {n:'Danico', d:'Al fondo de la Galerie Vivienne, uno de los pasajes cubiertos del siglo XIX. Coctelería seria en un sitio precioso.', t:'coctel', p:'€€', tip:'Combinar con un paseo por los pasajes cubiertos (Vivienne, Galerie Véro-Dodat, Passage des Panoramas): es el mejor plan de París para un día de lluvia.'},
    {m:'Ritz Paris', n:'Bar Hemingway, Ritz Paris', d:'Colin Field lleva décadas detrás de esta barra diminuta. Caro, ceremonioso y memorable.', t:'coctel', p:'€€€', tip:'Abre a las 18:00 y hay pocas mesas. Llegar a la apertura o quedarse sin sitio.'},
    {n:'Le Syndicat', d:'Cócteles hechos solo con destilados franceses, en un local con la fachada tapada de carteles pegados. Nada pretencioso, todo bueno.', t:'coctel', p:'€€'},
    {n:'Moonshiner', d:'Se entra por la cámara frigorífica del fondo de una pizzería de Bastille. Detrás hay un bar de los años 20 con sillones de cuero.', t:'coctel', p:'€€', tip:'La pizzería se llama Da Vito. Hay que entrar, cruzar y abrir la puerta de la cámara.'},
    {n:'Le Perchoir Marais', d:'Azotea sobre el BHV con vista al Ayuntamiento y a Notre-Dame. En invierno montan cabañas de madera con mantas.', t:'coctel', p:'€€'}
  ]},
  {s:'Al aire libre', k:'aire', items:[
    {n:'Jardin du Luxembourg', d:'El jardín favorito de los parisinos. Sillas verdes que se mueven donde uno quiera, el estanque con veleros y el Palacio del Senado al fondo.', t:'aire', tip:'En noviembre lo dejan lleno de hojas y sillas vacías. Es el mejor lugar de París para no hacer nada.'},
    {n:'Jardin des Tuileries', d:'Del Louvre a la Concorde en línea recta. En invierno se llena con el mercado de Navidad y la noria gigante.', t:'aire'},
    {ruta:['Place des Abbesses, Paris','Place du Tertre, Paris','Rue de l’Abreuvoir, Paris','Basilique du Sacré-Coeur, Paris'], n:'Montmartre a pie', d:'Subir por Abbesses, pasar por la Place du Tertre, bajar por la Rue de l’Abreuvoir hasta La Maison Rose y terminar en el Sacré-Cœur al atardecer.', t:'aire', tip:'Evitar el funicular y las escaleras principales: las callecitas laterales son el paseo, y ahí no hay nadie.'},
    {n:"Le Mur des Je t'aime", d:'Un muro de lava esmaltada con "te quiero" escrito 311 veces en 250 idiomas, en el Square Jehan Rictus, junto al metro Abbesses.', t:'aire', tip:'Está el "te quiero" en castellano y en varias lenguas más. Es chiquito y gratis: cinco minutos, de camino a Montmartre.'},
    {n:'Canal Saint-Martin', d:'Puentes de hierro, esclusas y plátanos, con cafés y tiendas de barrio a los costados. El París que no sale en las postales.', t:'aire'},
    {n:'Parc des Buttes-Chaumont', d:'El parque más dramático de la ciudad: un acantilado con un templete arriba, un lago y puentes colgantes. Casi sin turistas.', t:'aire'},
    {ruta:['Pont Neuf, Paris','Notre-Dame de Paris','Pont Saint-Louis, Paris'], n:'Île de la Cité e Île Saint-Louis', d:'Cruzar del Pont Neuf al Pont Saint-Louis caminando: Notre-Dame, la Conciergerie, librerías, y helado de Berthillon incluso en invierno.', t:'aire', tip:'En el Pont Saint-Louis casi siempre hay músicos. Es el mejor sitio para pararse a mirar el río.'},
    {n:'Pont Alexandre III', d:'El puente más recargado de París: faroles art nouveau, querubines, ninfas y cuatro columnas doradas en las puntas. Une los Inválidos con el Grand Palais y el Petit Palais.', t:'aire', tip:'Se combina con AURA Invalides y con el Petit Palais, que están uno a cada lado. De noche, con los faroles prendidos y la Torre Eiffel a la derecha, es de las fotos que mejor salen de París.'},
    {n:'Père Lachaise', d:'El cementerio más visitado del mundo, empedrado y arbolado. Chopin, Piaf, Wilde, Morrison. Se camina como un parque.', t:'aire', tip:'Con las hojas de noviembre en el suelo es cuando mejor está. Pedir el mapa en la entrada principal.'},
    {n:'Bateaux Mouches', d:'El crucero clásico por el Sena, saliendo del Pont de l’Alma. Poco más de una hora, pasando por Notre-Dame, el Louvre y la Torre Eiffel.', t:'aire', p:'€€', w:'https://www.bateaux-mouches.fr/', tip:'Subir al atardecer: se sale con luz y se vuelve con la ciudad encendida y la Torre centelleando. Abrigarse: en cubierta hace mucho más frío que en tierra.'}
  ]},
  {s:'Imprescindibles y dónde sacar la foto', k:'visita', items:[
    {n:'Torre Eiffel', d:'Centellea cinco minutos al comienzo de cada hora, desde el anochecer hasta la 1:00.', t:'visita', p:'€€', w:'https://www.toureiffel.paris/', tip:'Los cinco mejores ángulos: el Trocadéro (llegar temprano), el Champ de Mars, el número 5 de la Rue de l’Université, el Pont de Bir-Hakeim con sus arcos de hierro y la Avenue de Camoëns, que casi nadie conoce.'},
    {n:'Notre-Dame de París', d:'Reabierta en diciembre de 2024, con la piedra clara recién limpiada. La entrada a la catedral es gratuita.', t:'visita', w:'https://www.notredamedeparis.fr/', tip:'Reservar horario gratuito en la web o la app evita una cola de una hora. Se libera con dos días de antelación.'},
    {n:'Shakespeare and Company', d:'Enfrente de Notre-Dame, cruzando el río. Librería en inglés desde 1951, con pasillos angostos, libros hasta el techo, un piano al fondo y camas entre los estantes donde todavía duermen escritores de paso a cambio de trabajar unas horas. Sellan los libros con el retrato de Shakespeare.', t:'visita', a:'37 rue de la Bûcherie', w:'https://shakespeareandcompany.com/', tip:'Adentro no se puede sacar fotos, y está bien que sea así. Al lado tienen un café con vista a la catedral. Se combina con Notre-Dame y la Île Saint-Louis en el mismo paseo.'},
    {m:'Basilique du Sacré-Coeur, Paris', n:'Sacré-Cœur', d:'Blanca, arriba de todo Montmartre. Entrar es gratis; subir al domo cuesta y son 300 escalones, pero la panorámica es la más alta de París después de la Torre.', t:'visita'},
    {m:'Musée de Montmartre, Paris', n:'Musée de Montmartre y los jardines Renoir', d:'La casa más antigua de Montmartre, donde vivieron Renoir, Suzanne Valadon y su hijo Utrillo. El taller de Valadon está reconstruido tal cual era, y los jardines de atrás miran a la única viña que queda en París.', t:'visita', p:'€€', w:'https://museedemontmartre.fr/', tip:'Está a tres minutos de la Place du Tertre y casi nadie sube. Los jardines tienen bancos y una vista de los techos del norte de París que no se consigue desde ningún otro lado.'},
    {n:'Arco de Triunfo', d:'Se sube a la azotea. Desde arriba se ven las doce avenidas saliendo en estrella y los Campos Elíseos iluminados de punta a punta.', t:'visita', p:'€€', tip:'Es la mejor vista nocturna de París, porque es la única desde la que se ve la Torre Eiffel centelleando. Se cruza por el paso subterráneo, nunca por la calle.'},
    {n:'Musée d’Orsay', d:'Una estación de tren de 1900 reconvertida en museo del impresionismo. Van Gogh, Monet, Degas, Renoir.', t:'visita', p:'€€', w:'https://www.musee-orsay.fr/', tip:'La foto es a través del gran reloj del quinto piso, con Montmartre detrás. Está en la sala del café.'},
    {n:'Musée de l’Orangerie', d:'Dos salas ovaladas con los Nenúfares de Monet montados como él los pensó, en curva y con luz natural. Se ve en una hora.', t:'visita', p:'€€', w:'https://www.musee-orangerie.fr/', tip:'Está en el borde de las Tuileries. Es el museo perfecto para un día de lluvia sin comerse la tarde entera.'},
    {nota:1, n:'Museos: cuáles valen la pena y cuáles no hacen falta', d:'El Louvre es enorme y agotador: con dos horas de cola se ve un dos por ciento. Si no les tira especialmente, se puede saltar sin culpa. El Orsay se ve entero en dos horas y tiene los cuadros que uno reconoce, y de la Orangerie se sale en una hora con los Nenúfares metidos en la cabeza.', t:'visita', tip:'Si igual quieren el Louvre, la jugada es entrar los viernes, que abren de noche, e ir derecho a tres salas. Y hay museos municipales con la colección permanente gratis: el Petit Palais, el Carnavalet, que cuenta la historia de la ciudad en dos palacetes del Marais, y la Maison de Victor Hugo.'},
    {nota:1, n:'Casas museo: los museos distintos', d:'Los mejores museos chicos de París son casas donde vivió alguien. La Maison de Victor Hugo, en la Place des Vosges, es el departamento donde escribió buena parte de Los Miserables, con su salón chino intacto y entrada gratis. El Musée Rodin es un palacete del siglo XVIII con jardín, y ahí están El Pensador y El Beso. El Musée Jacquemart-André es la casa de un matrimonio de coleccionistas del XIX, con salón de té en el comedor original.', t:'visita', tip:'El Rodin y el Jacquemart-André son los dos que mejor funcionan en pareja: se ven en hora y media y terminan sentadas tomando algo. En el Rodin, la entrada solo al jardín cuesta poco y ya vale la pena.'},
    {n:'Musée national de la Marine', d:'En el Palais de Chaillot, en el Trocadéro, reabierto en 2023 después de seis años de obra. Maquetas enormes de barcos, la falúa imperial de Napoleón, instrumentos de navegación y mascarones de proa tallados. El montaje es moderno y se ve en hora y media.', t:'visita', p:'€€', w:'https://www.musee-marine.fr/', tip:'Está en el mismo edificio desde donde se saca la foto clásica de la Torre Eiffel, así que se hacen juntos. Es poco turístico: casi nunca hay cola.'},
    {n:'Atelier des Lumières', d:'Una fundición de hierro del siglo XIX convertida en sala de proyección: los cuadros se proyectan sobre las paredes, el piso y el techo de diez metros, con música. Cambian de artista cada temporada.', t:'visita', p:'€€', w:'https://www.atelier-lumieres.com/', tip:'Mirar qué exposición está en cartel antes de comprar. Es buen plan para un día de lluvia y para descansar de los museos de sala en sala.'},
    {n:'Ópera Garnier', d:'Se visita por libre. La Gran Escalera de mármol, el salón de los espejos y el techo pintado por Chagall sobre la sala roja y dorada.', t:'visita', p:'€€', w:'https://www.operadeparis.fr/', tip:'Verificar antes: si hay ensayo, no dejan entrar a la sala y solo se ven los salones.'},
    {n:'Galeries Lafayette Haussmann', d:'La cúpula de vidrio de 1912 y la terraza de la azotea, ambas gratis. En Navidad, el árbol de 25 metros colgando bajo la cúpula y los escaparates animados.', t:'visita', w:'https://haussmann.galerieslafayette.com/', tip:'La terraza es una de las mejores vistas gratuitas de París: Ópera, Torre Eiffel y Sacré-Cœur de una sola pasada.'},
    {n:'AURA Invalides', d:'Espectáculo de luz y música bajo la cúpula de los Inválidos: música orquestal, sonido envolvente y proyecciones sobre las seis capillas y la tumba de Napoleón. Unos 50 minutos.', t:'visita', p:'€€', w:'https://aura-invalides.com/', tip:'Adulto €22. Se entra por la Place Vauban, del lado del Dôme, no por la Explanada: hay 12 minutos de caminata entre una entrada y otra.'},
    {n:'Sainte-Chapelle', d:'Quince vidrieras del siglo XIII de suelo a techo. Con día gris pierde fuerza, así que conviene un día de sol.', t:'visita', p:'€€', tip:'Está dentro del recinto de la Conciergerie: hay control de seguridad y la cola puede ser larga. Entrada conjunta con la Conciergerie, que sale a cuenta.'},
    {n:'Le Marais', d:'La Place des Vosges (la plaza más antigua de París, con arcadas), la Rue des Rosiers y sus falafels, tiendas independientes y galerías. Muchos comercios abren los domingos, cosa rara en París.', t:'visita', tip:'Es el mejor barrio para un domingo, justo cuando el resto de la ciudad baja la persiana.'}
  ]},
  {s:'Navidad en París', k:'navidad', items:[
    {m:'Jardin des Tuileries, Paris', n:'Marché de Noël du Jardin des Tuileries', d:'De mediados de noviembre a principios de enero. El más grande del centro: casetas, feria con calesitas y una noria de 70 metros con vista al Louvre y a la Concorde.', t:'navidad', tip:'Es el más familiar y el más céntrico. De noche, con la noria iluminada y la Concorde de fondo, es de las mejores fotos del viaje.'},
    {m:'La Défense, Paris', n:'Marché de Noël de La Défense', d:'Del 12 de noviembre al 31 de diciembre de 2026. El mayor de la región, con cientos de chalets artesanales, gastronomía y pista de hielo.', t:'navidad', w:'https://www.parisladefense.com/', tip:'Está a 15 minutos en RER A desde el centro. Vale la pena si quieren mercado de verdad, con más artesanía y menos souvenir.'},
    {m:'Parvis Notre-Dame, Paris', n:'Marché de Noël Notre-Dame', d:'Del 26 de noviembre al 27 de diciembre de 2026, en el distrito 5, a pasos de la catedral recién reabierta.', t:'navidad', tip:'Es chico. Combinarlo con la visita a Notre-Dame y un paseo por la Île Saint-Louis.'},
    {m:'Galeries Lafayette Haussmann, Paris', n:'Escaparates de Galeries Lafayette y Printemps', d:'Desde mediados de noviembre. Escenas animadas montadas por artesanos, gratis y desde la vereda. Dentro, el árbol de 25 metros colgando bajo la cúpula.', t:'navidad', tip:'Hay una tarima pensada para que los chicos vean los escaparates; sirve igual para sacar la foto por encima de la gente.'},
    {m:'Avenue des Champs-Élysées, Paris', n:'Iluminación de los Campos Elíseos', d:'400 árboles con guirnaldas, encendidos cada noche hasta medianoche desde finales de noviembre. El 24 y el 31 quedan encendidos toda la noche.', t:'navidad', tip:'La foto: pararse en el centro de la avenida en el paso de peatones a la altura del número 100, mirando hacia el Arco.'},
    {m:'Galeries Lafayette Haussmann, Paris', n:'Patinaje en la azotea de Galeries Lafayette', d:'Pista de hielo sobre el tejado, con París entero de fondo. Suele ser gratis con reserva previa.', t:'navidad', tip:'Los horarios se agotan rápido. Reservar en la web de Galeries Lafayette apenas abran.'},
    {m:'Grand Palais, Paris', n:'Le Grand Palais des Glaces', d:'La pista de hielo cubierta más grande del mundo: 2.700 m² bajo la bóveda de vidrio del Grand Palais, con DJ y juegos de luces por la noche.', t:'navidad', p:'€€', w:'https://www.grandpalais.fr/', tip:'Atención con las fechas: la edición anterior fue del 13 de diciembre al 7 de enero. Si vuelven a abrir sobre esa fecha, puede caer justo al filo del viaje o quedar fuera. Confirmar en grandpalais.fr antes de contar con ello.'}
  ]},
  {s:'Compras y mercadillos', k:'compra', items:[
    {n:'La Vallée Village', d:'Outlet de firmas a 40 minutos, en RER A hasta Val d’Europe. Descuentos del 30 al 60 % durante todo el año, más el extra del Black Friday.', t:'compra', w:'https://www.lavalleevillage.com/', tip:'Se combina con Disneyland Paris, que está en la misma línea, si tuvieran ganas.'},
    {n:'Marché aux Puces de Saint-Ouen', d:'El mercado de pulgas más grande de Europa, en Clignancourt. Viernes, sábados y domingos. Quince mercados encadenados, de antigüedades serias a ropa vintage.', t:'compra', tip:'Los primeros puestos que se cruzan al bajar del metro son ropa barata sin interés. Hay que seguir caminando hasta los mercados con nombre (Vernaison, Dauphine, Paul Bert Serpette): ahí empieza lo bueno.'},
    {m:'Kilo Shop, Le Marais, Paris', n:'Kilo Shop y Guerrisol', d:'Vintage al peso en el Marais (Kilo Shop) y ropa de segunda mano baratísima en Guerrisol, que tiene varias sucursales por Barbès y Pigalle.', t:'compra', p:'€', tip:'Guerrisol es donde compran los estudiantes de moda parisinos. Hay que revolver, pero salen cosas increíbles por €5.'},
    {nota:1, n:'Souvenirs y láminas en Montmartre', d:'La zona entre el Sacré-Cœur y la Place du Tertre está llena de puestos de imanes, postales y láminas. En la plaza los pintores hacen retratos y venden acuarelas y grabados de París, que enmarcados quedan mucho mejor que cualquier souvenir de tienda.', t:'compra', p:'€', tip:'En los puestos de la calle los precios se pueden hablar, sobre todo si llevan más de una lámina. La Rue de Steinkerque, la de bajada hacia el metro Anvers, es la más turística y la más cara de todas.'},
    {ruta:['Rue des Francs-Bourgeois, Paris','Rue Vieille du Temple, Paris','Place des Vosges, Paris'], n:'Las calles de tiendas del Marais', d:'La Rue des Francs-Bourgeois es la principal, con moda, joyerías chicas y vidrieras muy cuidadas, y termina en la Place des Vosges. La cruzan la Rue Vieille du Temple y la Rue des Archives, más independientes, y la Rue de Turenne, donde están las firmas grandes.', t:'compra', tip:'Es de las pocas zonas de París donde casi todo abre los domingos. En diciembre están iluminadas y se caminan bien, porque son angostas y sin tráfico.'},
    {ruta:['Avenue Montaigne, Paris','Rue Saint-Honoré, Paris','Place Vendôme, Paris'], n:'El triángulo del lujo: Montaigne, Saint-Honoré y Vendôme', d:'La Avenue Montaigne sube desde el Sena hasta los Campos Elíseos con Dior, Chanel y Louis Vuitton, y en diciembre se ilumina entera. La Rue Saint-Honoré y su continuación, el Faubourg Saint-Honoré, son la otra calle de firmas, y terminan en la Place Vendôme, la de las joyerías, con las luces montadas alrededor de la columna.', t:'compra', tip:'No hace falta entrar a ninguna tienda: el paseo es mirar vidrieras. Montaigne después de cenar está vacía y perfectamente iluminada.'},
    {n:'Marché d’Aligre', d:'Mercado de barrio del distrito 12, con puestos de comida, brocante al aire libre y un mercado cubierto. Cierra los lunes.', t:'compra', tip:'Terminar en Le Baron Rouge, el bar de vinos de al lado donde sirven directo del barril.'},
    {n:'Le Bon Marché', d:'Los grandes almacenes más elegantes de París, en la orilla izquierda. La Grande Épicerie de al lado es el mejor sitio para comprar comestibles de regalo.', t:'compra', tip:'Mucho menos agobiante que Galeries Lafayette y con mejor curaduría.'},
    {nota:1, n:'Black Friday y soldes', d:'El Black Friday del 27 de noviembre sí se hace, pero en Francia los descuentos fuertes son los soldes d’hiver de enero, fuera del viaje. Los outlets son la excepción.', t:'compra'}
  ]},
  {s:'Espectáculos de noviembre y diciembre', k:'evento', items:[
    {nota:1, n:'Conciertos a la luz de las velas', d:'Sainte-Chapelle y La Madeleine programan clásicos (Vivaldi, Mozart, réquiems) casi todas las noches de diciembre, con las vidrieras iluminadas por dentro.', t:'evento', p:'€€', tip:'El de la Sainte-Chapelle es la experiencia: la sala es tan chica que se oye todo, y de noche las vidrieras se ven desde adentro con luz artificial.'},
    {m:'Palais Garnier, Paris', n:'Ópera Garnier y Ópera Bastille', d:'La temporada de ópera y ballet está en pleno diciembre. Ver un ballet en el Palais Garnier es distinto a visitarlo de día.', t:'evento', p:'€€€', w:'https://www.operadeparis.fr/', tip:'Las entradas más baratas son de visibilidad parcial, pero en el Garnier eso significa estar dentro del edificio igual.'},
    {n:'Philharmonie de Paris', d:'La sala de conciertos de Jean Nouvel en La Villette. Programación de primer nivel y acústica excepcional.', t:'evento', p:'€€', w:'https://philharmoniedeparis.fr/'},
    {nota:1, n:'Cabaret', d:'Moulin Rouge, Crazy Horse y Lido siguen funcionando. Turístico, sí, pero el Crazy Horse es el más artístico de los tres y el que mejor funciona en pareja.', t:'evento', p:'€€€'},
    {nota:1, n:'Cartelera', d:'Sortiraparis y Fnac Spectacles listan todo lo que se anuncia: conciertos, exposiciones temporales y eventos de temporada.', t:'evento', w:'https://www.sortiraparis.com/'}
  ]}
  ]
},
