{
  id:'mad', nav:'Madrid', name:'Madrid', plate:'Metro', accent:'#B54B36', lt:'#F0A78F', maps:'Madrid',
  lede:'Soleada, barata y hecha para caminar de noche. Se cena a las diez y nadie las mira raro. Si llegan para el 22 de noviembre agarran el encendido de luces, que convierte el centro entero en un paseo.',
  quick:[
    ['Sencillo','€1,50 a €2,00'],
    ['Abono turístico','€8,40 / 1 día · €18,40 / 3'],
    ['Noviembre','15° / 6°, seco y soleado'],
    ['Se cena','21:00 a 22:30']
  ],
  sections:[
  {s:'Cómo moverse', k:'mover', items:[
    {ruta:['Puerta del Sol, Madrid','Gran Vía, Madrid','Palacio Real, Madrid','Parque del Retiro, Madrid'], n:'Madrid se camina', d:'Sol a Gran Vía son 5 minutos; Sol al Palacio Real, 12; Sol al Retiro, 20; Gran Vía al Templo de Debod, 15. Casi todo el plan del día entra caminando.', t:'mover', tip:'Es la ciudad donde menos falta hace el transporte. Usen el metro solo para el aeropuerto y para el Bernabéu.'},
    {nota:1, n:'Metro', d:'Rápido, limpio y de los más baratos de Europa. Las líneas 1, 2, 3 y 5 cubren todo el centro.', t:'mover', tip:'La tarjeta Multi cuesta €2,50 y se comparte entre varias personas para viajes sencillos. El Metrobús de 10 viajes sale €12,20 y es lo más eficiente si van a usarlo poco.'},
    {nota:1, n:'Abono turístico', d:'Transporte ilimitado en toda la red por días: €8,40 (1 día), €14,20 (2), €18,40 (3), €26,80 (5). Es personal: no se puede prestar.', t:'mover', tip:'Solo compensa si van a hacer más de tres viajes por día. Con lo poco que hace falta el transporte en Madrid, muchas veces no sale a cuenta.'},
    {nota:1, n:'Aeropuerto de Barajas', d:'Metro línea 8 desde Nuevos Ministerios (con un suplemento de €3) o Cercanías C-1. En taxi hay tarifa fija de €33 entre el aeropuerto y el interior de la M-30.', t:'mover', tip:'La tarifa fija de €33 es por trayecto, no por persona, e incluye equipaje. Con dos personas y valijas suele ser lo más cómodo.'},
    {nota:1, n:'Taxi, Uber y Cabify', d:'Las tres funcionan bien y son notablemente más baratas que en Londres o París. El taxi es blanco con una franja roja en diagonal.', t:'mover', tip:'A la salida de una cena tarde, un Uber al hotel cuesta poco más que dos billetes de metro.'},
    {nota:1, n:'Cercanías para las escapadas', d:'Renfe Cercanías y el AVE de media distancia llegan a Toledo, Segovia, El Escorial y Alcalá de Henares en menos de una hora.', t:'mover', tip:'Comprar el AVE a Toledo o Segovia con antelación en renfe.com: sale bastante más barato que en taquilla.'}
  ]},
  {s:'Comer', k:'comer', items:[
    {nota:1, n:'Los horarios de comida en Madrid', d:'Es el más tarde de todos, con diferencia. Se almuerza de 14:00 a 16:00 y se cena de 21:00 a 23:00. Si van a cenar a las 20:00 se van a encontrar el restaurante vacío, y no porque sea malo.', t:'comer', tip:'Entre las 16:30 y las 20:30 casi ninguna cocina de restaurante trabaja, pero los bares de tapas sirven todo el tiempo y eso cubre el hueco perfectamente. Es, de hecho, la mejor manera de comer en Madrid.'},
    {n:'Chocolatería San Ginés', d:'Pasadizo de San Ginés 5, abierta desde 1894 y prácticamente 24 horas. Seis churros y una taza de chocolate espeso: el desayuno, la merienda o el cierre de la noche.', t:'comer', p:'€', a:'Pasadizo de San Ginés 5', w:'https://chocolateriasangines.com/', tip:'A las 6 de la mañana está llena de gente saliendo de fiesta. A las 9 de la mañana está vacía y es igual de buena.'},
    {n:'Mercado de San Ildefonso', d:'Fuencarral 57, en Malasaña. Tres plantas de puestos de comida callejera con terraza arriba. Se pica de todo sin comprometerse con un restaurante.', t:'comer', p:'€', a:'Calle Fuencarral 57', tip:'Mucho más barato y más local que San Miguel, y con mejor ambiente de noche.'},
    {nota:1, n:'Bocadillo de calamares', d:'El plato más madrileño que existe: calamares rebozados en un bollo, sin nada más. En los bares de las calles que salen de la Plaza Mayor.', t:'comer', p:'€', tip:'La Campana y Bar Postas son los clásicos. Se come de pie, con una caña, y cuesta menos de €5.'},
    {n:'El Tigre', d:'Chueca. Piden una caña y les ponen delante un plato de tapas del tamaño de una cena, gratis. Ruidoso, apretado y una institución.', t:'comer', p:'€', tip:'No es sitio para una cena romántica: es sitio para cenar por €8 entre las dos y reírse.'},
    {n:'Mercado de San Miguel', d:'El mercado de hierro de 1916 junto a la Plaza Mayor, reconvertido en barra gourmet: jamón, ostras, croquetas, vermut.', t:'comer', p:'€€', a:'Plaza de San Miguel', w:'https://mercadodesanmiguel.es/', tip:'Es caro para lo que es y está siempre lleno, pero hay que ir una vez. Entre semana a las 12:30 se consigue sitio en la barra.'},
    {n:'La Mallorquina', d:'Puerta del Sol, desde 1894. La napolitana de crema o chocolate, recién salida y todavía caliente, es lo que hay que pedir.', t:'comer', p:'€', a:'Puerta del Sol 8', tip:'La cola del mostrador de abajo (para llevar) va rápida. El salón de arriba, con vista a Sol, es otro plan.'},
    {n:'Cafetería Don Jamón', d:'Bocadillos de jamón, tortilla y raciones sin pretensiones, a precio de barrio y en pleno centro.', t:'comer', p:'€', tip:'Es el tipo de sitio donde se desayuna bien y barato antes de arrancar el día.'},
    {n:'Casa Lucio', d:'Cava Baja. Los huevos rotos con patatas son el plato: huevo frito sobre patatas, roto en la mesa. Simple y perfecto.', t:'comer', p:'€€', tip:'Reservar con antelación. La Cava Baja entera es la calle de tabernas de Madrid: se puede hacer ruta de una a otra.'},
    {n:'Sobrino de Botín', d:'El restaurante más antiguo del mundo en funcionamiento continuo, desde 1725, con el horno de leña original. Cochinillo y cordero asado.', t:'comer', p:'€€€', w:'https://botin.es/', tip:'Pedir mesa en el sótano de ladrillo, no en la planta alta. Reservar con semanas.'},
    {m:'Hotel Mayorazgo, Gran Vía 61, Madrid', n:'GastroVía 61, Hotel Mayorazgo', d:'En Gran Vía 61, dentro del Hotel Mayorazgo. Salón tranquilo con aire de Madrid antiguo, lejos del ruido de la calle. El solomillo Wellington es el motivo para ir.', t:'comer', p:'€€€', a:'Gran Vía 61', w:'https://www.hotelmayorazgo.com/es/gastronomia/', tip:'Confirmar el Wellington al reservar: no siempre está en carta y a veces hay que pedirlo con antelación.'},
    {m:'Four Seasons Hotel Madrid', n:'Dani Brasserie, Four Seasons', d:'La azotea del Four Seasons, con Dani García en la cocina y los tejados del centro alrededor. Terraza climatizada en invierno.', t:'comer', p:'€€€', tip:'Si la cena se pasa de presupuesto, subir solo a tomar algo al atardecer resuelve la vista.'}
  ]},
  {s:'Café y merienda', k:'cafe', items:[
    {m:'La Mallorquina, Puerta del Sol, Madrid', n:'La Mallorquina, salón de arriba', d:'Además de la napolitana del mostrador, arriba hay un salón donde se merienda mirando la Puerta del Sol desde la ventana. La merienda madrileña de toda la vida.', t:'cafe', p:'€'},
    {n:'Café Gijón', d:'Paseo de Recoletos, desde 1888. El café de las tertulias literarias, con camareros de chaqueta blanca y espejos.', t:'cafe', p:'€€'},
    {n:'Café Comercial', d:'Glorieta de Bilbao, de 1887 y reabierto tras años cerrado. Columnas de mármol, espejos enormes y buena carta a cualquier hora.', t:'cafe', p:'€€'},
    {m:'Toma Café, Malasaña, Madrid', n:'Toma Café y HanSo Café', d:'Los dos pilares del café de especialidad en Malasaña. Tueste propio, sin postureo y con la mejor taza de la ciudad.', t:'cafe', p:'€'},
    {n:'Casa Mira', d:'Carrera de San Jerónimo, desde 1842. Turrón artesanal de temporada, cortado a mano delante de ustedes. En noviembre y diciembre está en su momento.', t:'cafe', p:'€€', tip:'El turrón de Jijona es el clásico. Se lleva bien en la valija y es el mejor regalo comestible de Madrid.'},
    {n:'El Riojano', d:'Calle Mayor 10, pastelería de 1855 fundada por una repostera de la reina. Suspiros, pastas de té y bartolillos.', t:'cafe', p:'€'}
  ]},
  {s:'Cócteles y azoteas', k:'coctel', items:[
    {n:'Ginkgo Sky Bar', d:'Planta 12 del VP Plaza España Design, con 360° sobre la Plaza de España, el Palacio Real y el Templo de Debod. Cocina española con vueltas modernas y coctelería seria.', t:'coctel', p:'€€', a:'Plaza de España 5, planta 12', w:'https://www.ginkgoskybarmadrid.com/', tip:'Abre de 13:00 a 02:00 (hasta las 02:30 viernes y sábados). Jazz en vivo los miércoles a las 21:30 y sesiones de DJ de jueves a sábado desde las 23:00. Reservar mesa junto al ventanal.'},
    {m:'Hotel Riu Plaza España, Madrid', n:'360º Rooftop Bar, Hotel Riu Plaza España', d:'Planta 27, 570 m² de terraza con vuelta completa a la ciudad y un palco superior al que se sube por una escalera. La vista más alta del centro.', t:'coctel', p:'€', a:'Plaza de España 18, planta 27', w:'https://www.riu.com/', tip:'La entrada al mirador cuesta €5 de 11:00 a 17:00 y €10 a partir de las 17:00; los fines de semana y festivos, €10 todo el día. No se puede reservar la entrada, se compra en el momento. Truco: reservando mesa en el gastrobar de la planta 26 se evita la cola.'},
    {n:'Salmon Guru', d:'Barrio de las Letras. Uno de los mejores bares del mundo, con una estética de cómic y cócteles que llegan en vasos imposibles.', t:'coctel', p:'€€', w:'https://salmonguru.es/', tip:'No reservan para grupos chicos: llegar temprano o esperar. Vale la espera.'},
    {n:'Museo Chicote', d:'Gran Vía 12, abierto en 1931. Pasaron Hemingway, Ava Gardner y Sinatra. Art déco original y una barra que no cambió.', t:'coctel', p:'€€'},
    {n:'1862 Dry Bar', d:'Malasaña. Coctelería clásica bien hecha, sin música alta, en un local chico de dos plantas. El mejor sitio de Madrid para hablar mientras se toma algo.', t:'coctel', p:'€€'},
    {n:'Picalagartos Sky Bar', d:'Azotea sobre Gran Vía, con la avenida a los pies y el cartel de Schweppes a un brazo de distancia.', t:'coctel', p:'€€'}
  ]},
  {s:'Al aire libre', k:'aire', items:[
    {n:'Parque del Retiro', d:'125 hectáreas en el centro. El Palacio de Cristal (gratis, con exposiciones), el estanque con barcas de remo, la Rosaleda y el Bosque del Recuerdo.', t:'aire', tip:'Entrar por la Puerta de Alcalá, cruzar hasta el estanque, seguir al Palacio de Cristal y salir por la Cuesta de Moyano, la calle de las casetas de libros de viejo.'},
    {n:'Templo de Debod', d:'Un templo egipcio del siglo II a.C. que Egipto regaló a España, montado sobre una loma con vistas abiertas al oeste. El mejor atardecer de Madrid, y es gratis.', t:'aire', tip:'Llegar 40 minutos antes de la puesta del sol y ponerse del lado del estanque, para que el templo se refleje. En diciembre el sol se pone sobre las 17:50.'},
    {n:'Campo del Moro', d:'Los jardines del Palacio Real vistos desde abajo, con el palacio recortado en lo alto. Casi vacíos porque poca gente sabe entrar.', t:'aire', tip:'La entrada está en el Paseo de la Virgen del Puerto, no por el palacio. Cierra al atardecer.'},
    {ruta:['Parque del Oeste, Madrid','Teleférico de Madrid'], n:'Parque del Oeste y teleférico', d:'Pinos, la Rosaleda y el teleférico que cruza hasta la Casa de Campo por encima del río. Once minutos de vista aérea de Madrid.', t:'aire', p:'€', tip:'Se combina con el Templo de Debod, que está justo al lado.'},
    {n:'Madrid Río', d:'La ribera del Manzanares reconvertida en parque lineal, con el Puente de Toledo y el Matadero al final. Bueno para caminar sin turistas.', t:'aire'},
    {n:'Jardines de Sabatini', d:'Jardín geométrico en el flanco norte del Palacio Real, con setos recortados y una fuente central. Chico y perfecto para el atardecer.', t:'aire'},
    {ruta:['La Latina, Madrid','Barrio de las Letras, Madrid','Chueca, Madrid','Malasaña, Madrid'], n:'Barrios a pie', d:'La Latina (tabernas y el Rastro), Malasaña (moderno y joven), Chueca (bares y diseño) y el Barrio de las Letras (donde vivieron Cervantes y Lope de Vega, con versos escritos en el suelo).', t:'aire', tip:'El Barrio de las Letras a la hora del vermut, un domingo, es lo más madrileño que hay.'},
    {nota:1, n:'Escapada a Toledo o Segovia', d:'Media hora en AVE desde Atocha o Chamartín. Toledo es la ciudad de las tres culturas amurallada; Segovia tiene el acueducto romano y el mejor cochinillo.', t:'aire', tip:'Un día entero. Si eligen Segovia, comer cochinillo en el Mesón de Cándido, al pie del acueducto.'}
  ]},
  {s:'Imprescindibles y dónde sacar la foto', k:'visita', items:[
    {n:'Palacio Real', d:'Por superficie es el palacio real más grande de Europa occidental, con 3.400 salas. Se visita una parte, pero esa parte impresiona.', t:'visita', p:'€€', w:'https://www.patrimonionacional.es/', tip:'Entrada gratuita para ciudadanos de la UE y de Latinoamérica en las últimas dos horas, de lunes a jueves. Hay cola, así que llegar con margen.'},
    {n:'Catedral de la Almudena', d:'Justo enfrente del palacio. Se puede subir a la cúpula y al museo, con una vista distinta del palacio y de la sierra.', t:'visita', p:'€', tip:'La foto buena del palacio se saca desde la explanada de la catedral, no desde la Plaza de Oriente.'},
    {ruta:['Plaza de Cibeles, Madrid','Puerta de Alcalá, Madrid'], n:'Fuente de Cibeles y Puerta de Alcalá', d:'El símbolo de Madrid y el arco de Carlos III, a cinco minutos uno del otro sobre el Paseo del Prado.', t:'visita', tip:'La mejor vista es desde la azotea de CentroCentro, en el Palacio de Cibeles: se sube gratis hasta el mirador de la planta 6 y la vista de Gran Vía y Alcalá es la mejor de la ciudad.'},
    {n:'Gran Vía', d:'Una avenida de los años 20 con los edificios más fotografiados de Madrid: el Metrópolis, el Carrión con el cartel de Schweppes, el Telefónica.', t:'visita', tip:'La foto clásica del Metrópolis se saca desde la esquina de Alcalá con Gran Vía. La otra, desde el mirador del Círculo de Bellas Artes.'},
    {m:'Círculo de Bellas Artes, Madrid', n:'Azotea del Círculo de Bellas Artes', d:'Siete plantas sobre Alcalá, con la mejor panorámica del centro: Gran Vía entera, Cibeles, el Retiro y la sierra al fondo.', t:'visita', p:'€', w:'https://www.circulobellasartes.com/', tip:'Unos €6 la entrada al mirador. Ir al atardecer y quedarse a tomar algo cuando se encienden las luces.'},
    {ruta:['Plaza Mayor, Madrid','Puerta del Sol, Madrid'], n:'Plaza Mayor y Puerta del Sol', d:'La plaza porticada de 1619 y el kilómetro cero de España. En diciembre, la Plaza Mayor se llena entera con el mercado navideño.', t:'visita', tip:'El Arco de Cuchilleros, en la esquina sureste de la Plaza Mayor, baja a la zona de tabernas centenarias.'},
    {ruta:['Puerta del Sol, Madrid','Plaza Mayor, Madrid','Barrio de las Letras, Madrid'], n:'Detalles del centro que se pasan por alto', d:'El Oso y el Madroño en Sol, que es el escudo de la ciudad hecho estatua y el punto de encuentro de todo Madrid. El kilómetro cero, una placa en el piso frente a la Casa de Correos desde donde se miden todas las rutas de España. La Casa de la Panadería, con la fachada entera pintada, en la Plaza Mayor. Y los versos de Cervantes y de Quevedo grabados en el suelo del Barrio de las Letras.', t:'visita', tip:'Los cuatro están a menos de diez minutos caminando entre sí. Es el paseo que hace todo el mundo sin darse cuenta de que lo está haciendo.'},
    {n:'Museo del Prado', d:'Velázquez, Goya, El Bosco. Las Meninas y las Pinturas Negras justifican el viaje solas.', t:'visita', p:'€€', w:'https://www.museodelprado.es/', tip:'Gratis de lunes a sábado de 18:00 a 20:00 y los domingos de 17:00 a 19:00. Se llena, pero dos horas bien elegidas alcanzan.'},
    {n:'Museo Reina Sofía', d:'El Guernica de Picasso, con sus bocetos alrededor. También Dalí y Miró.', t:'visita', p:'€€', w:'https://www.museoreinasofia.es/', tip:'Gratis de lunes a sábado desde las 19:00 y los domingos desde las 12:30. Está cerrado los martes.'},
    {nota:1, n:'Museos: cuáles valen la pena y cuáles se pueden saltar', d:'El Prado sí, pero con criterio: dos horas eligiendo a Velázquez, a Goya y a El Bosco valen más que cuatro intentando verlo todo. El Reina Sofía se justifica por el Guernica y poco más si no les tira el arte contemporáneo. Y el Thyssen es el más fácil de los tres, porque recorre la historia de la pintura en orden y se ve completo en dos horas.', t:'visita', tip:'Los tres están sobre el mismo paseo, a diez minutos entre sí, y los tres tienen un rato gratis al final del día. Hacer dos en la misma jornada es demasiado: se sale saturado y no se disfruta ninguno.'},
    {m:'Museo Sorolla, Madrid', n:'Museo Sorolla: la casa del pintor', d:'La casa y el taller de Joaquín Sorolla tal cual los dejó, con su jardín andaluz de fuentes y azulejos, en pleno Chamberí. Los cuadros de la playa colgados en las paredes de su propia casa.', t:'visita', p:'€', w:'https://www.cultura.gob.es/msorolla/', tip:'Es de los museos más lindos de Madrid y casi nadie lo conoce. Se ve en una hora y el jardín se recorre sin apuro. Entrada gratuita los sábados por la tarde y los domingos.'},
    {nota:1, n:'Casa Museo Lope de Vega y Museo Cerralbo', d:'La casa de Lope de Vega, en el Barrio de las Letras, es la casa de un escritor del Siglo de Oro con su huerta reconstruida, y se visita con guía en grupos chicos. El Museo Cerralbo es un palacio del XIX que quedó congelado tal como vivía el marqués: los muebles, los cuadros y hasta la mesa puesta.', t:'visita', p:'€', tip:'La de Lope es gratis pero hay que reservar la visita guiada con antelación, porque son pocos lugares por día. El Cerralbo cuesta unos €3 y es de esos sitios que una termina recordando más que el Prado.'},
    {m:'Galería Canalejas, Madrid', n:'Galería Canalejas y Four Seasons', d:'El complejo de lujo del centro, con la galería comercial y el Dani Brasserie en la azotea, con vista sobre los tejados del Madrid de los Austrias.', t:'visita', tip:'Se puede subir a tomar algo sin cenar. La terraza está cubierta y climatizada en invierno.'},
    {n:'Estadio Santiago Bernabéu', d:'El tour del estadio recién reformado, con el techo retráctil y el museo de trofeos.', t:'visita', p:'€€', w:'https://www.realmadrid.com/', tip:'Si hay partido, la entrada más barata cuesta parecido al tour y la experiencia no tiene comparación.'}
  ]},
  {s:'Navidad en Madrid', k:'navidad', items:[
    {m:'Plaza de Cibeles, Madrid', n:'Encendido de las luces', d:'El 22 de noviembre a las 19:00, con ceremonia en la Plaza de Cibeles: cuenta atrás, proyecciones sobre los edificios y música en vivo. Las luces quedan hasta el 6 de enero, en más de 240 emplazamientos por toda la ciudad.', t:'navidad', tip:'Si el viaje empieza a mediados de noviembre, esta es la noche. Cibeles se llena, así que llegar con una hora de antelación o verlo desde Alcalá.'},
    {m:'Plaza Mayor, Madrid', n:'Mercado navideño de la Plaza Mayor', d:'Del 27 de noviembre al 31 de diciembre. 104 casetas con figuras de belén, adornos, musgo y árboles. Es un mercado de Navidad español, no centroeuropeo: menos vino caliente, más belenes.', t:'navidad', tip:'La tradición local: comprar peluca y nariz de plástico para Nochevieja. Se venden en la mitad de las casetas.'},
    {m:'El Corte Inglés Callao, Madrid', n:'Cortylandia', d:'El escaparate animado de El Corte Inglés de Callao, con muñecos gigantes y canción propia. Un clásico madrileño desde 1979.', t:'navidad', tip:'Las funciones son a horas fijas varias veces al día. Es kitsch y absolutamente entrañable.'},
    {m:'Real Jardín Botánico, Madrid', n:'Naturaleza Encendida en el Real Jardín Botánico', d:'Recorrido nocturno de luz y sonido entre los árboles del jardín botánico, junto al Prado.', t:'navidad', p:'€€', tip:'Se agotan las entradas. Comprarlas online con antelación y elegir un horario temprano, cuando hay menos gente.'},
    {ruta:['Puerta del Sol, Madrid','Calle de Preciados, Madrid','Plaza de Callao, Madrid','Gran Vía, Madrid'], n:'Belenes y calles iluminadas', d:'El belén monumental de la Casa de Correos en Sol, y las luces de Preciados, Fuencarral, Gran Vía, Serrano y la Puerta de Alcalá.', t:'navidad', tip:'Preciados y Carmen se peatonalizan y se llenan. Un paseo nocturno de Sol a Callao y de ahí a Gran Vía es plan de una hora, gratis y precioso.'}
  ]},
  {s:'Compras y mercadillos', k:'compra', items:[
    {n:'El Rastro', d:'Domingos y festivos, de 9:00 a 15:00, en La Latina. El rastro clásico de Madrid: ropa, antigüedades, discos, cachivaches y mucha gente.', t:'compra', p:'€', tip:'Ir temprano. Al terminar, la tradición es el vermut en las tabernas de la Cava Baja o en la Plaza de Cascorro. Cuidado con el bolsillo: hay carteristas.'},
    {n:'Las Rozas Village', d:'Outlet de firmas a media hora del centro, con autobús directo desde Moncloa. Descuentos permanentes más el extra del Black Friday.', t:'compra', w:'https://www.lasrozasvillage.com/', tip:'Hay shuttle desde el centro. Consultar horarios en su web antes de ir.'},
    {ruta:['Gran Vía, Madrid','Calle de Preciados, Madrid','Calle de Fuencarral, Madrid'], n:'Gran Vía, Preciados y Fuencarral', d:'La zona comercial del centro: cadenas grandes en Gran Vía y Preciados, moda joven e independiente en Fuencarral y sus alrededores.', t:'compra', tip:'Zara, Mango y Massimo Dutti son españolas y en España están más baratas que en el resto de Europa. La flagship de Zara en Gran Vía es enorme.'},
    {n:'Mercado de Motores', d:'Un fin de semana al mes, dentro del Museo del Ferrocarril, entre locomotoras antiguas. Vintage, diseño, discos y comida.', t:'compra', tip:'Confirmar la fecha del mes en su web antes de contar con él.'},
    {n:'Vintage en Malasaña', d:'Magpie, Biba y Williamsburg concentran la mejor selección de segunda mano de la ciudad, en unas pocas calles.', t:'compra', p:'€'},
    {ruta:['Calle de Serrano, Madrid','Calle de José Ortega y Gasset, Madrid','Calle de Claudio Coello, Madrid'], n:'La milla de oro: Serrano y Ortega y Gasset', d:'Serrano, José Ortega y Gasset y Claudio Coello concentran el lujo madrileño: Loewe, Cartier, Prada, Dior y las joyerías españolas de siempre. Es la zona más señorial de la ciudad y las veredas son anchas, así que se pasea bien aunque no se compre nada.', t:'compra', tip:'En diciembre Serrano se ilumina entera y es de los paseos navideños más lindos de Madrid, con mucha menos gente que Preciados. Loewe es española y su tienda de Serrano es una visita en sí misma.'}
  ]},
  {s:'Espectáculos de noviembre y diciembre', k:'evento', items:[
    {nota:1, n:'Flamenco en tablao', d:'Corral de la Morería es el más prestigioso del mundo (y tiene estrella Michelin en su restaurante); Cardamomo y Villa Rosa son más accesibles y muy buenos.', t:'evento', p:'€€', tip:'Reservar el pase de la noche, no el de la cena, si quieren gastar menos: el espectáculo es el mismo.'},
    {n:'Teatro Real', d:'La ópera de Madrid, frente al Palacio Real. Temporada completa en noviembre y diciembre.', t:'evento', p:'€€€', w:'https://www.teatroreal.es/'},
    {nota:1, n:'Musicales de Gran Vía', d:'El "Broadway madrileño": media docena de musicales grandes en cartel simultáneamente, en teatros de los años 20.', t:'evento', p:'€€', tip:'Entradas mucho más baratas que en Londres para producciones de nivel parecido.'},
    {nota:1, n:'Conciertos de Navidad', d:'El Auditorio Nacional y el Teatro Monumental programan zarzuela, villancicos y clásicos durante todo diciembre.', t:'evento', p:'€€'},
    {nota:1, n:'Movistar Arena y WiZink', d:'Los grandes conciertos internacionales que pasan por Madrid. Consultar la cartelera cerca de la fecha.', t:'evento', w:'https://www.entradas.com/'}
  ]}
  ]
},
