{
  id:'rom', nav:'Roma', name:'Roma', plate:'ATAC', accent:'#8F6A28', lt:'#DFBE78', maps:'Rome',
  lede:'La más templada del viaje, y la que más premia caminar: el metro ni siquiera pasa por el centro barroco, así que todo se hace a pie. En noviembre todavía se puede almorzar afuera al sol, y en diciembre la Piazza Navona se llena de puestos.',
  quick:[
    ['Se cena','20:30 a 22:30'],
    ['Billete BIT','€1,50, 100 minutos'],
    ['Abonos','24 h €8,50 · 48 h €12,50 · 72 h €18'],
    ['Noviembre','17° / 9°, la más templada'],
    ['Taxi aeropuerto','Fiumicino €55 fijo']
  ],
  sections:[
  {s:'Cómo moverse', k:'mover', items:[
    {nota:1, n:'Roma se camina, y no es opcional', d:'El metro no pasa por el centro barroco: no hay estación cerca del Panteón, de Piazza Navona ni de la Fontana di Trevi. Todo eso se hace a pie, y está todo a 20 o 30 minutos entre sí.', t:'mover', tip:'Zapatos planos con suela de goma. Los sampietrini (adoquines de basalto) están pulidos por los siglos y resbalan mucho cuando llueve.'},
    {nota:1, n:'Metro A y B', d:'Solo dos líneas útiles. La A pasa por el Vaticano (Ottaviano), Piazza di Spagna y Barberini; la B, por el Coliseo y el Testaccio. Sirven para trayectos largos.', t:'mover'},
    {nota:1, n:'Tranvía 8', d:'Va de la Piazza Venezia al Trastevere en pocos minutos. Es la forma más rápida y agradable de cruzar el río.', t:'mover'},
    {nota:1, n:'Autobuses: con paciencia', d:'La red es amplia pero lenta e impredecible, y las huelgas son frecuentes. Sirven, pero no cuenten con horarios.', t:'mover', tip:'Comprobar avisos de huelga en atac.roma.it o en Moovit antes de organizar el día alrededor de un autobús.'},
    {nota:1, n:'Taxis', d:'Se toman en las paradas oficiales o por app (FreeNow, itTaxi): en Roma no se paran en la calle. Tarifa fija de €55 entre Fiumicino y el centro histórico, y €40 desde Ciampino.', t:'mover', tip:'Exigir el taxímetro en trayectos urbanos. En el aeropuerto, ignorar a quien se acerque a ofrecer viaje: los taxis legales están en la parada con cartel TAXI a la salida de llegadas.'},
    {nota:1, n:'Uber en Roma', d:'Solo opera como Uber Black, con coches de alta gama. Funciona bien pero cuesta bastante más que un taxi normal.', t:'mover'},
    {nota:1, n:'Leonardo Express', d:'Tren directo entre Fiumicino y Termini en 32 minutos, cada 15 o 30 minutos.', t:'mover', tip:'Validar el billete antes de subir si es de papel. La multa por no validarlo es alta y la controlan.'}
  ]},
  {s:'Comer', k:'comer', items:[
    {nota:1, n:'Los horarios de comida en Roma', d:'Almuerzo de 12:30 a 15:00 y cena desde las 19:30 o 20:00, con las cocinas trabajando hasta cerca de las 23:00. Muchas trattorias cierran entre una cosa y la otra, así que a las 17:00 cuesta encontrar algo más que un bar.', t:'comer', tip:'Los romanos cenan sobre las 20:30 o 21:00. Sentarse a las 19:30 suele significar conseguir mesa sin reserva en sitios que después se llenan.'},
    {n:'Pizzarium Bonci', d:'Junto a los Museos Vaticanos. Pizza al taglio de masa fermentada muchas horas, cortada con tijera y pesada. Gabriele Bonci cambió la forma en que Roma come pizza.', t:'comer', p:'€', tip:'Se come de pie en la calle. Ideal antes o después del Vaticano, que está a diez minutos.'},
    {n:'Trapizzino', d:'Un triángulo de pizza bianca abierto y relleno con guisos romanos: pollo alla cacciatora, lengua en salsa verde, albóndigas. Inventado en el Testaccio.', t:'comer', p:'€', tip:'Dos por persona y una cerveza es una cena completa por menos de €12 cada una.'},
    {n:'Forno Campo de’ Fiori', d:'En la plaza del mercado. La pizza bianca con aceite y sal es el snack romano por excelencia, y sale por poco más de un euro.', t:'comer', p:'€', tip:'Pedirla "con la mortazza" (con mortadela dentro) es como la comen los romanos.'},
    {n:'Da Enzo al 29', d:'Trastevere. Trattoria diminuta con los cuatro clásicos romanos hechos como corresponde: cacio e pepe, carbonara, amatriciana y gricia.', t:'comer', p:'€€', tip:'No aceptan reservas para cenar y la cola empieza antes de que abran. Sentarse a las 19:00 en punto suele funcionar; si no, pasar a almorzar.'},
    {n:'Tonnarello', d:'También en Trastevere, más grande y con menos espera que Da Enzo. Buena relación calidad-precio y terraza con estufas.', t:'comer', p:'€€'},
    {n:'Armando al Pantheon', d:'A cincuenta metros del Panteón, en manos de la misma familia desde 1961. Cocina romana clásica, sin concesiones al turista pese a la ubicación.', t:'comer', p:'€€', w:'https://www.armandoalpantheon.it/', tip:'Reservar con semanas de antelación. Es de los pocos sitios buenos que quedan en pleno centro turístico.'},
    {n:'Roscioli Salumeria con Cucina', d:'Mitad charcutería, mitad restaurante. Una de las mejores carbonaras de Roma y una carta de vinos enorme.', t:'comer', p:'€€', tip:'Reservar. Sentarse en la barra, entre los jamones colgados, es mejor que en el salón.'},
    {m:'Palazzo Manfredi, Roma', n:'Aroma, Palazzo Manfredi', d:'Una estrella Michelin y una terraza con el Coliseo a cincuenta metros, tan cerca que parece decorado. Si van a hacer una sola cena cara en Roma, que sea esta.', t:'comer', p:'€€€', w:'https://www.aromarestaurant.it/', tip:'Pedir mesa en la terraza al reservar, aunque en diciembre esté acristalada y con calefacción. Reservar con mucha antelación.'},
    {n:'Pierluigi', d:'Piazza de’ Ricci, cerca de Campo de’ Fiori. Pescado y marisco en una plaza chica, con terraza climatizada. Un clásico romano de los caros.', t:'comer', p:'€€€'}
  ]},
  {s:'Café y gelato', k:'cafe', items:[
    {n:"Sant'Eustachio Il Caffè", d:'A dos calles del Panteón. Para muchos, el mejor espresso de Roma. Lo preparan tapando la máquina con un paño para que no se vea el método.', t:'cafe', p:'€', tip:'El "gran caffè" viene ya azucarado por defecto. Si lo quieren sin azúcar, hay que pedirlo "senza zucchero" al pagar, antes de que lo hagan.'},
    {n:'Tazza d’Oro', d:'Junto al Panteón, desde 1944. La granita di caffè con panna (café granizado con crema arriba y abajo) es lo que hay que pedir, incluso en invierno.', t:'cafe', p:'€'},
    {nota:1, n:'La regla del café en Italia', d:'Tomado de pie en la barra cuesta la mitad o menos que sentadas en la mesa. En zonas turísticas la diferencia puede ser de €1,20 a €5.', t:'cafe', tip:'Se paga primero en la caja, se lleva el ticket a la barra y se pide. Y después de las 11 de la mañana, ningún italiano toma cappuccino.'},
    {n:'Giolitti', d:'Heladería de 1900 cerca del Panteón. Gelato clásico, con nata montada gratis por encima si se pide.', t:'cafe', p:'€', tip:'Alternativas más artesanales y menos turísticas: Fatamorgana y Otaleg, en el Trastevere.'},
    {n:'Roscioli Caffè', d:'El café de la familia Roscioli. Bollería excelente, café serio y sitio para sentarse sin agobio.', t:'cafe', p:'€'}
  ]},
  {s:'Cócteles', k:'coctel', items:[
    {n:'Drink Kong', d:'En Monti. Estética Blade Runner con neones y luz baja, y coctelería de las mejores del mundo, de la mano de Patrick Pistolesi.', t:'coctel', p:'€€', w:'https://www.drinkkong.com/', tip:'Está entre los 50 mejores bares del mundo. Sobre las 19:00 todavía se consigue sitio y se puede hablar sin gritar.'},
    {n:'Freni e Frizioni', d:'Trastevere. Un antiguo taller mecánico ("frenos y embragues") convertido en bar. Aperitivo con buffet incluido y terraza sobre el Tíber.', t:'coctel', p:'€', tip:'El aperitivo de 19:00 a 22:00 incluye buffet libre con el precio de la bebida. Es la mejor relación precio-diversión de Roma.'},
    {n:'Jerry Thomas Speakeasy', d:'Bar clandestino de verdad: hay que buscar la contraseña en su web y llamar a una puerta sin cartel. Coctelería clásica de los años 20.', t:'coctel', p:'€€', tip:'Hay que hacerse socio online (cuesta poco) y reservar. Parte de la gracia es el trámite.'},
    {n:'Salotto42', d:'Piazza di Pietra, frente a las columnas del templo de Adriano. Un salón con libros de arte y sillones, con una de las vistas más bonitas para tomar algo.', t:'coctel', p:'€€'},
    {n:'Terrazza Borromini', d:'Azotea con vista directa sobre la Piazza Navona y las cúpulas de Borromini. Caro, pero la vista no la tiene nadie más.', t:'coctel', p:'€€€', tip:'Ir al atardecer y quedarse una copa. En diciembre, con el mercado de Navidad abajo iluminado, es otro nivel.'}
  ]},
  {s:'Al aire libre', k:'aire', items:[
    {m:'Terrazza del Pincio, Roma', n:'Villa Borghese y la Terrazza del Pincio', d:'Un parque enorme en el centro, con lago, y una terraza que da directo sobre la Piazza del Popolo con las cúpulas de Roma detrás.', t:'aire', tip:'Es el mejor atardecer de Roma junto con el Gianicolo, y se llega andando desde Piazza di Spagna subiendo por la escalinata.'},
    {n:'Gianicolo', d:'La colina sobre el Trastevere. La panorámica completa de Roma, con todas las cúpulas alineadas. Todos los días a mediodía disparan un cañonazo.', t:'aire', tip:'Subir a pie desde el Trastevere por la Via Garibaldi (20 minutos de cuesta) y bajar al atardecer. La fuente del Acqua Paola, a mitad de camino, es la de la primera escena de La Grande Bellezza.'},
    {ruta:['Giardino degli Aranci, Roma','Piazza dei Cavalieri di Malta, Roma'], n:'Giardino degli Aranci y el ojo de la cerradura', d:'Un jardín de naranjos en el Aventino con vista al Tíber y a San Pedro. A cincuenta metros, la puerta de la Orden de Malta: por el ojo de la cerradura se ve la cúpula de San Pedro perfectamente centrada al final de un seto.', t:'aire', tip:'Suele haber cola de dos o tres personas para mirar por la cerradura. Vale los cinco minutos. Es gratis y es de las cosas más raras y bonitas de Roma.'},
    {m:'Piazza di Santa Maria in Trastevere, Roma', n:'Trastevere de noche', d:'Calles empedradas, ropa tendida, hiedra y trattorias. Es el barrio más bonito de Roma para caminar sin plan después de cenar.', t:'aire', tip:'Cruzar por el Ponte Sisto desde el centro y perderse. La Piazza di Santa Maria in Trastevere, con la basílica iluminada, es el centro de todo.'},
    {n:'Via Appia Antica', d:'Calzada romana original, con losas de basalto de hace 2.300 años, tumbas y catacumbas. Los domingos se cierra al tráfico.', t:'aire', tip:'Alquilar bicicletas en el centro de visitantes del parque. Es medio día distinto a todo lo demás, y en noviembre está vacío.'},
    {ruta:['Piazza del Popolo, Roma','Fontana di Trevi, Roma','Pantheon, Roma','Piazza Navona, Roma','Campo de Fiori, Roma'], n:'El paseo del centro barroco', d:'Piazza del Popolo → Via del Corso → Fontana di Trevi → Panteón → Piazza Navona → Campo de’ Fiori. Una hora larga a pie, sin subir a ningún transporte, y es media Roma.', t:'aire', tip:'Hacerlo dos veces: una de mañana temprano y otra de noche. Son dos ciudades distintas.'},
    {n:'Ponte Sant’Angelo', d:'El puente de los diez ángeles de Bernini, con el Castel Sant’Angelo enfrente y la cúpula de San Pedro al fondo.', t:'aire', tip:'Al atardecer, con el río y las luces encendiéndose, es una de las mejores fotos de la ciudad.'}
  ]},
  {s:'Imprescindibles y dónde sacar la foto', k:'visita', items:[
    {ruta:['Colosseo, Roma','Foro Romano, Roma','Palatino, Roma'], n:'Coliseo, Foro Romano y Palatino', d:'Entrada conjunta a los tres. El Foro se recorre en dos horas y el Palatino tiene la mejor vista del Foro desde arriba.', t:'visita', p:'€€', w:'https://parcocolosseo.it/', tip:'Reservar horario en coopculture.it con antelación: sin reserva la cola es de horas. Entrar por el Palatino (Via di San Gregorio) suele tener menos gente que por el Coliseo.'},
    {n:'Panteón', d:'El edificio antiguo mejor conservado del mundo, con el óculo abierto al cielo. Entrada de €5.', t:'visita', p:'€', tip:'Si llueve, entrar: se ve caer el agua por el óculo y drenar por el suelo original. Es una de las cosas más impresionantes de Roma y casi nadie la ve.'},
    {n:'Fontana di Trevi', d:'Enorme y siempre rodeada. Se tira una moneda con la mano derecha por encima del hombro izquierdo.', t:'visita', tip:'A las 7 de la mañana está prácticamente vacía y con luz dorada. A cualquier otra hora es una multitud.'},
    {ruta:['Bocca della Verita, Roma','Piazza di Spagna, Roma','Fontana di Trevi, Roma'], n:'Roma de película', d:'La Bocca della Verità está en el pórtico de Santa Maria in Cosmedin: la máscara de mármol que muerde la mano al que miente, la de Vacaciones en Roma. La escalinata de la Piazza di Spagna es de la misma película. Y la Fontana di Trevi es la de La Dolce Vita, aunque hoy meterse al agua sale una multa considerable.', t:'visita', tip:'La Bocca es gratis pero tiene cola para la foto. Adentro, la iglesia es una de las más lindas y silenciosas del centro, y ahí no entra casi nadie.'},
    {m:'Basilica di San Pietro, Vaticano', n:'Vaticano: Basílica de San Pedro', d:'Entrar es gratis. Subir a la cúpula cuesta €10 y son 551 escalones (o ascensor hasta la terraza y 320 a pie).', t:'visita', p:'€', tip:'Abre a las 7:00 y esa primera hora es la más tranquila del día. Hay control de seguridad y código de vestimenta: hombros y rodillas cubiertos, para las dos.'},
    {m:'Musei Vaticani, Roma', n:'Museos Vaticanos y Capilla Sixtina', d:'Cuatro horas si se hace completo. La Capilla Sixtina está al final del recorrido y no se puede saltar la fila.', t:'visita', p:'€€', w:'https://www.museivaticani.va/', tip:'Reservar sí o sí, con semanas de antelación. Los miércoles por la mañana hay audiencia papal y la plaza está cortada.'},
    {n:'Castel Sant’Angelo', d:'Un mausoleo romano que los papas convirtieron en fortaleza. La terraza de arriba tiene una de las mejores vistas de Roma.', t:'visita', p:'€€'},
    {n:'Galleria Borghese', d:'Bernini y Caravaggio en un palacio del siglo XVII dentro de Villa Borghese. El Rapto de Proserpina y el Apolo y Dafne están ahí.', t:'visita', p:'€€', w:'https://galleriaborghese.beniculturali.it/', tip:'Hay que reservar, se entra por turnos de dos horas y dejan pasar poca gente por vez. Se agota con semanas. Es el museo más agradable de Roma justamente por eso.'},
    {nota:1, n:'Museos: cuáles valen la pena y cuáles se pueden saltar', d:'Los Museos Vaticanos y la Galleria Borghese son los dos que justifican reservar con semanas. Los Museos Capitolinos, en el Campidoglio, tienen la loba, el Marco Aurelio a caballo y una terraza con vista al Foro, y casi nunca hay cola. Si el tiempo no da para todo, el que se puede dejar afuera es el Vaticano: son cuatro horas de multitud, y Roma tiene iglesias con Caravaggios colgados gratis.', t:'visita', tip:'Los Caravaggios gratuitos están en San Luigi dei Francesi, a dos calles de Piazza Navona, y en Santa Maria del Popolo. Conviene llevar monedas de un euro, que son las que encienden la luz del cuadro.'},
    {n:'Galleria Doria Pamphilj', d:'Un palacio sobre Via del Corso que sigue siendo de la familia. Salones dorados con los cuadros colgados de arriba abajo como en el siglo XVII, y el retrato de Inocencio X de Velázquez en una salita para él solo. La audioguía la narra el propio príncipe de la casa, contando anécdotas familiares.', t:'visita', p:'€€', w:'https://www.doriapamphilj.it/', tip:'Está a cinco minutos del Panteón y de la Fontana di Trevi, y casi nadie entra. Es el mejor museo poco visitado de Roma.'},
    {nota:1, n:'Museos distintos: Montemartini y la casa de Keats', d:'Centrale Montemartini es una usina eléctrica de principios del siglo XX con las estatuas romanas puestas entre las turbinas y los motores. El contraste es rarísimo y funciona. La Keats-Shelley House está al pie de la escalinata de la Piazza di Spagna: es el cuarto donde murió el poeta Keats a los 25 años, con su biblioteca intacta.', t:'visita', p:'€', tip:'Montemartini está a un par de paradas de metro del centro y no hay nadie nunca. La casa de Keats se ve en media hora y está justo donde de todas formas van a estar.'},
    {n:'Basilica di San Clemente', d:'Tres niveles superpuestos: una basílica del siglo XII sobre una del siglo IV sobre un templo pagano y una casa romana del siglo I. Se baja por escaleras.', t:'visita', p:'€', tip:'Está a cinco minutos del Coliseo y casi no tiene cola. Es la mejor manera de entender cómo se construyó Roma encima de sí misma.'},
    {m:'Piazza di Spagna, Roma', n:'Piazza di Spagna y la escalinata', d:'Las 135 escaleras y la fuente de la Barcaccia abajo. No se puede sentar en los escalones: hay multa.', t:'visita', tip:'Desde arriba, junto a la iglesia de Trinità dei Monti, se ve toda la Via Condotti en línea recta. En diciembre está iluminada.'}
  ]},
  {s:'Navidad en Roma', k:'navidad', items:[
    {m:'Piazza Navona, Roma', n:'Mercatino di Piazza Navona', d:'Previsto del 1 al 31 de diciembre de 2026. Puestos de dulces, juguetes y adornos alrededor de las fuentes de Bernini, con calesita y la figura de la Befana.', t:'navidad', tip:'Abre hasta la una de la madrugada entre semana y hasta las dos los fines de semana. De noche, con las fuentes iluminadas, es cuando vale la pena.'},
    {m:'Piazza San Pietro, Vaticano', n:'Árbol y belén de la Plaza de San Pedro', d:'Se inauguran a principios de diciembre, con el belén a tamaño real montado junto al obelisco.', t:'navidad', tip:'La plaza iluminada de noche, casi vacía, es una de las mejores estampas del viaje.'},
    {ruta:['Via del Corso, Roma','Via dei Condotti, Roma','Via del Babuino, Roma'], n:'Luces del centro', d:'Via del Corso, Via Condotti y Via del Babuino se iluminan de punta a punta. Condotti pone su instalación de luces sobre la calle de las firmas.', t:'navidad'},
    {nota:1, n:'8 de diciembre: la Inmaculada', d:'Festivo nacional. El Papa acude a la columna de la Inmaculada en la Piazza di Spagna por la tarde. Muchísima gente y buena parte del comercio cerrado.', t:'navidad', tip:'Si caen en Roma ese día, planificarlo como día de paseo y comida, no de museos ni compras.'},
    {nota:1, n:'Conciertos de Navidad en las basílicas', d:'Santa Maria in Aracoeli, Sant’Ignazio y otras basílicas programan coros y música sacra durante todo diciembre, muchos gratuitos.', t:'navidad'}
  ]},
  {s:'Compras y mercadillos', k:'compra', items:[
    {n:'Porta Portese', d:'Domingos de 7:00 a 14:00, en el Trastevere. El mercado de pulgas más grande de Roma: ropa, antigüedades, discos, libros y de todo.', t:'compra', p:'€', tip:'Ir temprano y con el bolso adelante. Es enorme: dos horas y se ve solo una parte.'},
    {n:'Castel Romano Designer Outlet', d:'Outlet de firmas a media hora, con shuttle desde Termini. El descuento del Black Friday se suma al de outlet.', t:'compra', w:'https://www.mcarthurglen.com/it/outlets/it/designer-outlet-castel-romano/', tip:'Reservar el shuttle online. Sale de la zona de Termini varias veces al día.'},
    {n:'Via Cola di Rienzo', d:'En Prati, cruzando el río. Las mismas tiendas que Via del Corso pero sin la multitud, con veredas anchas.', t:'compra', tip:'Es donde compran los romanos. Mucho más agradable que el Corso un sábado.'},
    {ruta:['Via dei Condotti, Roma','Via Borgognona, Roma','Via del Babuino, Roma'], n:'Via Condotti y las calles de firmas', d:'Condotti sale de la Piazza di Spagna en línea recta: Bulgari, Prada, Gucci, Valentino, Cartier, y el Caffè Greco de 1760 en el medio. Alrededor, Via Borgognona, Via Frattina y Via del Babuino hacen el mismo recorrido con menos gente.', t:'compra', tip:'En diciembre las luces de Condotti son las mejores de Roma. Se camina de noche, después de cenar, cuando ya cerraron las tiendas y no queda nadie.'},
    {n:'Mercato Monti', d:'Fines de semana, en el barrio de Monti. Diseño independiente, vintage seleccionado y artesanía joven.', t:'compra', tip:'Monti entero (Via del Boschetto, Via Panisperna) es el mejor barrio de Roma para tiendas chicas.'},
    {n:'Via Sannio', d:'Mercado de ropa junto a San Giovanni, de lunes a sábado por la mañana. Ropa nueva barata y una zona grande de segunda mano.', t:'compra', p:'€'},
    {nota:1, n:'Saldi y Black Friday', d:'Las rebajas de invierno italianas (saldi invernali) empiezan a principios de enero, después del viaje. El Black Friday del 27 de noviembre sí se hace, sobre todo en outlets y cadenas.', t:'compra'}
  ]},
  {s:'Espectáculos de noviembre y diciembre', k:'evento', items:[
    {n:'Teatro dell’Opera di Roma', d:'Temporada de ópera y ballet en el teatro histórico de Via Firenze.', t:'evento', p:'€€', w:'https://www.operaroma.it/'},
    {n:'Auditorium Parco della Musica', d:'El complejo de Renzo Piano, con tres salas y programación constante: clásica, jazz, pop y conferencias.', t:'evento', p:'€€', w:'https://www.auditorium.com/'},
    {nota:1, n:'Roma Jazz Festival', d:'Se celebra en noviembre, sobre todo en el Auditorium. Una de las citas grandes del jazz europeo.', t:'evento', p:'€€', tip:'Confirmar el cartel y las fechas exactas cerca del viaje.'},
    {nota:1, n:'Cartelera oficial', d:'060608.it es el portal oficial de eventos de Roma, con todo lo que pasa día por día. TicketOne vende la mayoría de las entradas.', t:'evento', w:'https://www.060608.it/'}
  ]}
  ]
},
