{
  id:'rom', nav:'Roma', name:'Roma', plate:'ATAC', accent:'#8F6A28', lt:'#DFBE78', maps:'Rome',
  lede:'La más templada del viaje, y la que más premia caminar: el metro ni siquiera pasa por el centro barroco, así que todo se hace a pie. En noviembre todavía se puede almorzar afuera al sol, y en diciembre la Piazza Navona se llena de puestos.',
  quick:[
    ['Se cena','20:30 a 22:30'],
    ['Billete BIT','€1,50, 100 minutos'],
    ['Abonos','24 h €8,50 · 48 h €12,50 · 72 h €18'],
    ['Noviembre','17° / 9°, la más templada'],
    ['Taxi aeropuerto','Fiumicino €55 fijo']
  ],
  sections:[
  {s:'Cómo moverse', k:'mover', items:[
    {nota:1, n:'Roma se camina, y no es opcional', d:'El metro no pasa por el centro barroco: no hay estación cerca del Panteón, de Piazza Navona ni de la Fontana di Trevi. Todo eso se hace a pie, y está todo a 20 o 30 minutos entre sí.', t:'mover', tip:'Zapatos planos con suela de goma. Los sampietrini (adoquines de basalto) están pulidos por los siglos y resbalan mucho cuando llueve.'},
    {nota:1, n:'Metro A y B', d:'Solo dos líneas útiles. La A pasa por el Vaticano (Ottaviano), Piazza di Spagna y Barberini; la B, por el Coliseo y el Testaccio. Sirven para trayectos largos.', t:'mover'},
    {nota:1, n:'Tranvía 8', d:'Va de la Piazza Venezia al Trastevere en pocos minutos. Es la forma más rápida y agradable de cruzar el río.', t:'mover'},
    {nota:1, n:'Autobuses: con paciencia', d:'La red es amplia pero lenta e impredecible, y las huelgas son frecuentes. Sirven, pero no cuenten con horarios.', t:'mover', tip:'Comprobar avisos de huelga en atac.roma.it o en Moovit antes de organizar el día alrededor de un autobús.'},
    {nota:1, n:'Taxis', d:'Se toman en las paradas oficiales o por app (FreeNow, itTaxi): en Roma no se paran en la calle. Tarifa fija de €55 entre Fiumicino y el centro histórico, y €40 desde Ciampino.', t:'mover', tip:'Exigir el taxímetro en trayectos urbanos. En el aeropuerto, ignorar a quien se acerque a ofrecer viaje: los taxis legales están en la parada con cartel TAXI a la salida de llegadas.'},
    {nota:1, n:'Uber en Roma', d:'Solo opera como Uber Black, con coches de alta gama. Funciona bien pero cuesta bastante más que un taxi normal.', t:'mover'},
    {nota:1, n:'Leonardo Express', d:'Tren directo entre Fiumicino y Termini en 32 minutos, cada 15 o 30 minutos.', t:'mover', tip:'Validar el billete antes de subir si es de papel. La multa por no validarlo es alta y la controlan.'}
  ]},
  {s:'Comer parada: pizza al corte, supplì y refuerzos', k:'comer', items:[
    {nota:1, n:'Cómo se come en la calle en Roma', d:'Roma tiene una comida callejera propia y buenísima, y casi toda cuesta pocos euros: la pizza al taglio se pide señalando y se paga por peso, los supplì se comen de dos mordiscos y los refuerzos se piden en el mostrador de una panadería.', t:'comer', tip:'Es la mejor manera de almorzar barato para tener plata para una cena buena. Y a media tarde, cuando las trattorias cerraron cocina, es lo único que queda abierto.'},
    {n:'Pizzarium Bonci', d:'Junto a los Museos Vaticanos. Pizza al taglio de masa fermentada muchas horas, cortada con tijera y pesada. Gabriele Bonci cambió la forma en que Roma come pizza.', t:'comer', p:'€', tip:'Se come de pie en la calle. Ideal antes o después del Vaticano, que está a diez minutos.'},
    {n:'Trapizzino', d:'Un triángulo de pizza bianca abierto y relleno con guisos romanos: pollo alla cacciatora, lengua en salsa verde, albóndigas. Inventado en el Testaccio.', t:'comer', p:'€', tip:'Dos por persona y una cerveza es una cena completa por menos de €12 cada una. Los supplì de acá también son de los mejores de la ciudad.'},
    {n:'Forno Campo de’ Fiori', d:'En la plaza del mercado. La pizza bianca con aceite y sal es el snack romano por excelencia, y sale por poco más de un euro.', t:'comer', p:'€', tip:'Pedirla "con la mortazza" (con mortadela dentro) es como la comen los romanos.'},
    {n:'Antico Forno Roscioli', d:'La panadería de la familia Roscioli, en Via dei Chiavari. Pizza al corte, pan y una vitrina de refuerzos armados con los mismos fiambres y quesos que venden en la charcutería de al lado.', t:'comer', p:'€', tip:'A mediodía hay cola de oficinistas y avanza rápido. Es de lo mejor que se puede comer en Roma por menos de diez euros.'},
    {n:'Supplizio', d:'El supplì es la croqueta romana: una bola de arroz al ragú con mozzarella adentro, empanada y frita, que se estira como un hilo de teléfono al abrirla. Acá los hace Arcangelo Dandini, que los llevó a otra categoría sin dejar de cobrarlos como comida de calle.', t:'comer', p:'€', tip:'Está entre Campo de’ Fiori y el río, y es local chico de mostrador. Además del clásico hacen versiones con carbonara o con amatriciana adentro.'},
    {m:'Supplì Roma, Via di San Francesco a Ripa, Trastevere', n:'I Supplì, en el Trastevere', d:'Un agujero en la pared abierto desde 1979, con la freidora a la vista y una cola de gente del barrio. La versión sin pretensiones y la referencia contra la que se miden las demás.', t:'comer', p:'€', tip:'Se come parada en la vereda, sin más. Llevar algo de efectivo por las dudas.'},
    {m:'Mordi e Vai, Mercato Testaccio, Roma', n:'Mordi e Vai', d:'Un puesto adentro del mercado del Testaccio donde hacen refuerzos con guisos romanos: el de allesso con salsa verde, carne hervida con perejil y anchoa, es el famoso, y también hay de salchicha con brócoli o de albóndiga.', t:'comer', p:'€', tip:'Cierra a media tarde porque el mercado cierra. Es de las mejores cosas baratas de Roma y está al lado de las trattorias del Testaccio, así que sirve para armar el día entero por ahí.'},
    {n:'Zia Rosetta', d:'En Monti. Refuerzos hechos con una rosetta, el pan romano hueco, en versión chica: se piden tres distintos y se comparten.', t:'comer', p:'€', tip:'Monti está a cinco minutos del Coliseo y es donde conviene comer si andan por esa zona, porque alrededor del Coliseo mismo no hay nada bueno.'},
    {nota:1, n:'Los otros fritos romanos', d:'Además del supplì, en Roma se fríen las flores de zapallo rellenas con mozzarella y anchoa, y el filete de bacalao rebozado, que se come de pie con las manos.', t:'comer', tip:'El sitio del filete de bacalao es Dar Filettaro, en Largo dei Librari, una placita escondida a media cuadra de Campo de’ Fiori. Abre solo de noche y hace una sola cosa desde hace décadas.'}
  ]},
  {s:'Comer sentadas', k:'comer', items:[
    {nota:1, n:'Los horarios de comida en Roma', d:'Almuerzo de 12:30 a 15:00 y cena desde las 19:30 o 20:00, con las cocinas trabajando hasta cerca de las 23:00. Muchas trattorias cierran entre una cosa y la otra, así que a las 17:00 cuesta encontrar algo más que un bar.', t:'comer', tip:'Los romanos cenan sobre las 20:30 o 21:00. Sentarse a las 19:30 suele significar conseguir mesa sin reserva en sitios que después se llenan.'},
    {nota:1, n:'Las cuatro pastas romanas', d:'Cacio e pepe es queso pecorino y pimienta; gricia suma guanciale, que es cachete de cerdo curado; amatriciana suma tomate a la gricia; y carbonara suma huevo en vez de tomate. Son variaciones de lo mismo y conviene probar más de una.', t:'comer', tip:'Ninguna lleva crema, y la carbonara tampoco lleva panceta ni cebolla. Si en la carta aparece con crema, es un lugar hecho para turistas.'},
    {n:'Da Enzo al 29', d:'Trastevere. Trattoria diminuta con los cuatro clásicos romanos hechos como corresponde: cacio e pepe, carbonara, amatriciana y gricia.', t:'comer', p:'€€', tip:'No aceptan reservas para cenar y la cola empieza antes de que abran. Sentarse a las 19:00 en punto suele funcionar; si no, pasar a almorzar.'},
    {n:'Tonnarello', d:'También en Trastevere, más grande y con menos espera que Da Enzo. Buena relación calidad-precio y terraza con estufas.', t:'comer', p:'€€'},
    {n:'Felice a Testaccio', d:'La cacio e pepe se termina en la mesa: traen el queso, la pasta y la pimienta y la mantecan adelante de ustedes hasta que emulsiona. Abierta desde 1936 en el barrio del matadero, que es donde nació la cocina romana popular.', t:'comer', p:'€€', tip:'Reservar sí o sí, y con días. Está lejos del centro turístico y por eso sigue siendo lo que es.'},
    {n:'Santo Palato', d:'La versión joven de la trattoria romana, de Sarah Cicolini. Los clásicos hechos con técnica y algunos platos de casquería que suenan raros y salen muy bien.', t:'comer', p:'€€', tip:'Está en San Giovanni, fuera del circuito. Reservar. Si quieren una sola cena romana que no sea la de siempre, esta.'},
    {n:'Armando al Pantheon', d:'A cincuenta metros del Panteón, en manos de la misma familia desde 1961. Cocina romana clásica, sin concesiones al turista pese a la ubicación.', t:'comer', p:'€€', w:'https://www.armandoalpantheon.it/', tip:'Reservar con semanas de antelación. Es de los pocos sitios buenos que quedan en pleno centro turístico.'},
    {n:'Roscioli Salumeria con Cucina', d:'Mitad charcutería, mitad restaurante. Una de las mejores carbonaras de Roma y una carta de vinos enorme.', t:'comer', p:'€€', tip:'Reservar. Sentarse en la barra, entre los jamones colgados, es mejor que en el salón.'},
    {n:'Il Sorpasso', d:'En Prati, a diez minutos del Vaticano. Mitad bar, mitad restaurante, abierto todo el día sin cerrar la cocina, con embutidos, trapizzini y platos del día.', t:'comer', p:'€€', tip:'Justamente porque no cierra a media tarde, es la solución cuando salen del Vaticano a las 16:00 muertas de hambre y todo lo demás está cerrado.'},
    {m:'Palazzo Manfredi, Roma', n:'Aroma, Palazzo Manfredi', d:'Una estrella Michelin y una terraza con el Coliseo a cincuenta metros, tan cerca que parece decorado. Si van a hacer una sola cena cara en Roma, que sea esta.', t:'comer', p:'€€€', w:'https://www.aromarestaurant.it/', tip:'Pedir mesa en la terraza al reservar, aunque en diciembre esté acristalada y con calefacción. Reservar con mucha antelación.'},
    {n:'Pierluigi', d:'Piazza de’ Ricci, cerca de Campo de’ Fiori. Pescado y marisco en una plaza chica, con terraza climatizada. Un clásico romano de los caros.', t:'comer', p:'€€€'}
  ]},
  {s:'Café y gelato', k:'cafe', items:[
    {n:"Sant'Eustachio Il Caffè", d:'A dos calles del Panteón. Para muchos, el mejor espresso de Roma. Lo preparan tapando la máquina con un paño para que no se vea el método.', t:'cafe', p:'€', tip:'El "gran caffè" viene ya azucarado por defecto. Si lo quieren sin azúcar, hay que pedirlo "senza zucchero" al pagar, antes de que lo hagan.'},
    {n:'Tazza d’Oro', d:'Junto al Panteón, desde 1944. La granita di caffè con panna (café granizado con crema arriba y abajo) es lo que hay que pedir, incluso en invierno.', t:'cafe', p:'€'},
    {nota:1, n:'La regla del café en Italia', d:'Tomado de pie en la barra cuesta la mitad o menos que sentadas en la mesa. En zonas turísticas la diferencia puede ser de €1,20 a €5.', t:'cafe', tip:'Se paga primero en la caja, se lleva el ticket a la barra y se pide. Y después de las 11 de la mañana, ningún italiano toma cappuccino.'},
    {n:'Giolitti', d:'Heladería de 1900 cerca del Panteón. Gelato clásico y muy bueno, con crema batida gratis por encima si se pide.', t:'cafe', p:'€', tip:'Es la más famosa y la más turística de las buenas. Se paga primero en la caja y se lleva el ticket al mostrador, como en todos lados.'},
    {n:'Fatamorgana', d:'Sabores que no existen en ningún otro lado, todos naturales y sin colorantes: pera con gorgonzola, chocolate con tabaco de Kentucky, ricota con higo. Hay locales en Monti, en el Trastevere y en el centro.', t:'cafe', p:'€', tip:'Si quieren ir a lo seguro igual tienen los clásicos impecables. Es de las mejores de Roma y siempre hay uno cerca de donde estén.'},
    {m:'Otaleg, Via di San Cosimato, Trastevere, Roma', n:'Otaleg', d:'Gelato al revés, que es lo que dice el nombre leído de atrás para adelante. Marco Radicioni cambia la carta todo el tiempo y trabaja los sorbetes de fruta de estación como nadie.', t:'cafe', p:'€'},
    {m:'Gelateria dei Gracchi, Via dei Gracchi, Prati, Roma', n:'Gelateria dei Gracchi', d:'En Prati, a pocas cuadras del Vaticano. Materia prima obsesiva y clásicos hechos muy bien, sin inventar nada.', t:'cafe', p:'€', tip:'Es la respuesta al problema de que alrededor de los Museos Vaticanos casi todo lo que se vende es malo.'},
    {m:'Palazzo del Freddo Giovanni Fassi, Roma', n:'Palazzo del Freddo Fassi', d:'De 1880, en un salón enorme con máquinas antiguas y mesas de mármol. Es más una institución que una heladería de barrio.', t:'cafe', p:'€', tip:'Está en Esquilino, lejos de todo, así que solo si les queda de paso. El sanpietrino, un cubo de gelato bañado en chocolate, es la especialidad.'},
    {nota:1, n:'Cómo se reconoce un gelato bueno', d:'Si está apilado en montañas brillantes y el pistacho es verde flúor, es industrial y va a estar lleno de aire. El bueno está al ras de la cubeta o tapado, y tiene colores apagados: el pistacho de verdad es marrón grisáceo y la banana es gris, no amarilla.', t:'cafe', tip:'Sirve para toda Italia. Y una seña más: si en pleno noviembre tienen sabores de fruta de verano, es que no la usan fresca.'},
    {n:'Roscioli Caffè', d:'El café de la familia Roscioli. Bollería excelente, café serio y sitio para sentarse sin agobio.', t:'cafe', p:'€'}
  ]},
  {s:'Cócteles', k:'coctel', items:[
    {n:'Drink Kong', d:'En Monti. Estética Blade Runner con neones y luz baja, y coctelería de las mejores del mundo, de la mano de Patrick Pistolesi.', t:'coctel', p:'€€', w:'https://www.drinkkong.com/', tip:'Está entre los 50 mejores bares del mundo. Sobre las 19:00 todavía se consigue sitio y se puede hablar sin gritar.'},
    {n:'Freni e Frizioni', d:'Trastevere. Un antiguo taller mecánico ("frenos y embragues") convertido en bar. Aperitivo con buffet incluido y terraza sobre el Tíber.', t:'coctel', p:'€', tip:'El aperitivo de 19:00 a 22:00 incluye buffet libre con el precio de la bebida. Es la mejor relación precio-diversión de Roma.'},
    {n:'Jerry Thomas Speakeasy', d:'Bar clandestino de verdad: hay que buscar la contraseña en su web y llamar a una puerta sin cartel. Coctelería clásica de los años 20.', t:'coctel', p:'€€', tip:'Hay que hacerse socio online (cuesta poco) y reservar. Parte de la gracia es el trámite.'},
    {n:'Salotto42', d:'Piazza di Pietra, frente a las columnas del templo de Adriano. Un salón con libros de arte y sillones, con una de las vistas más bonitas para tomar algo.', t:'coctel', p:'€€'},
    {n:'Terrazza Borromini', d:'Azotea con vista directa sobre la Piazza Navona y las cúpulas de Borromini. Caro, pero la vista no la tiene nadie más.', t:'coctel', p:'€€€', tip:'Ir al atardecer y quedarse una copa. En diciembre, con el mercado de Navidad abajo iluminado, es otro nivel.'}
  ]},
  {s:'Al aire libre', k:'aire', items:[
    {m:'Terrazza del Pincio, Roma', n:'Villa Borghese y la Terrazza del Pincio', d:'Un parque enorme en el centro, con lago, y una terraza que da directo sobre la Piazza del Popolo con las cúpulas de Roma detrás.', t:'aire', tip:'Es el mejor atardecer de Roma junto con el Gianicolo, y se llega andando desde Piazza di Spagna subiendo por la escalinata.'},
    {n:'Gianicolo', d:'La colina sobre el Trastevere. La panorámica completa de Roma, con todas las cúpulas alineadas. Todos los días a mediodía disparan un cañonazo.', t:'aire', tip:'Subir a pie desde el Trastevere por la Via Garibaldi (20 minutos de cuesta) y bajar al atardecer. La fuente del Acqua Paola, a mitad de camino, es la de la primera escena de La Grande Bellezza.'},
    {ruta:['Giardino degli Aranci, Roma','Piazza dei Cavalieri di Malta, Roma'], n:'Giardino degli Aranci y el ojo de la cerradura', d:'Un jardín de naranjos en el Aventino con vista al Tíber y a San Pedro. A cincuenta metros, la puerta de la Orden de Malta: por el ojo de la cerradura se ve la cúpula de San Pedro perfectamente centrada al final de un seto.', t:'aire', tip:'Suele haber cola de dos o tres personas para mirar por la cerradura. Vale los cinco minutos. Es gratis y es de las cosas más raras y bonitas de Roma.'},
    {m:'Piazza di Santa Maria in Trastevere, Roma', n:'Trastevere de noche', d:'Calles empedradas, ropa tendida, hiedra y trattorias. Es el barrio más bonito de Roma para caminar sin plan después de cenar.', t:'aire', tip:'Cruzar por el Ponte Sisto desde el centro y perderse. La Piazza di Santa Maria in Trastevere, con la basílica iluminada, es el centro de todo.'},
    {n:'Via Appia Antica', d:'Calzada romana original, con losas de basalto de hace 2.300 años, tumbas y catacumbas. Los domingos se cierra al tráfico.', t:'aire', tip:'Alquilar bicicletas en el centro de visitantes del parque. Es medio día distinto a todo lo demás, y en noviembre está vacío.'},
    {ruta:['Piazza del Popolo, Roma','Fontana di Trevi, Roma','Pantheon, Roma','Piazza Navona, Roma','Campo de Fiori, Roma'], n:'El paseo del centro barroco', d:'Piazza del Popolo → Via del Corso → Fontana di Trevi → Panteón → Piazza Navona → Campo de’ Fiori. Una hora larga a pie, sin subir a ningún transporte, y es media Roma.', t:'aire', tip:'Hacerlo dos veces: una de mañana temprano y otra de noche. Son dos ciudades distintas.'},
    {n:'Ponte Sant’Angelo', d:'El puente de los diez ángeles de Bernini, con el Castel Sant’Angelo enfrente y la cúpula de San Pedro al fondo.', t:'aire', tip:'Al atardecer, con el río y las luces encendiéndose, es una de las mejores fotos de la ciudad.'}
  ]},
  {s:'Imprescindibles y dónde sacar la foto', k:'visita', items:[
    {ruta:['Colosseo, Roma','Foro Romano, Roma','Palatino, Roma'], n:'Coliseo, Foro Romano y Palatino', d:'Entrada conjunta a los tres. El Foro se recorre en dos horas y el Palatino tiene la mejor vista del Foro desde arriba.', t:'visita', p:'€€', w:'https://parcocolosseo.it/', tip:'Reservar horario en coopculture.it con antelación: sin reserva la cola es de horas. Entrar por el Palatino (Via di San Gregorio) suele tener menos gente que por el Coliseo.'},
    {n:'Panteón', d:'El edificio antiguo mejor conservado del mundo, con el óculo abierto al cielo. Entrada de €5.', t:'visita', p:'€', tip:'Si llueve, entrar: se ve caer el agua por el óculo y drenar por el suelo original. Es una de las cosas más impresionantes de Roma y casi nadie la ve.'},
    {n:'Fontana di Trevi', d:'Enorme y siempre rodeada. Se tira una moneda con la mano derecha por encima del hombro izquierdo.', t:'visita', tip:'A las 7 de la mañana está prácticamente vacía y con luz dorada. A cualquier otra hora es una multitud.'},
    {ruta:['Bocca della Verita, Roma','Piazza di Spagna, Roma','Fontana di Trevi, Roma'], n:'Roma de película', d:'La Bocca della Verità está en el pórtico de Santa Maria in Cosmedin: la máscara de mármol que muerde la mano al que miente, la de Vacaciones en Roma. La escalinata de la Piazza di Spagna es de la misma película. Y la Fontana di Trevi es la de La Dolce Vita, aunque hoy meterse al agua sale una multa considerable.', t:'visita', tip:'La Bocca es gratis pero tiene cola para la foto. Adentro, la iglesia es una de las más lindas y silenciosas del centro, y ahí no entra casi nadie.'},
    {n:'Castel Sant’Angelo', d:'Un mausoleo romano que los papas convirtieron en fortaleza. La terraza de arriba tiene una de las mejores vistas de Roma.', t:'visita', p:'€€', tip:'Está a cinco minutos de la Plaza de San Pedro, así que se encadena bien con el día del Vaticano si les queda energía.'},
    {n:'Galleria Borghese', d:'Bernini y Caravaggio en un palacio del siglo XVII dentro de Villa Borghese. El Rapto de Proserpina y el Apolo y Dafne están ahí.', t:'visita', p:'€€', w:'https://galleriaborghese.beniculturali.it/', tip:'Hay que reservar, se entra por turnos de dos horas y dejan pasar poca gente por vez. Se agota con semanas. Es el museo más agradable de Roma justamente por eso.'},
    {nota:1, n:'Museos: cuáles valen la pena y cuáles se pueden saltar', d:'La Galleria Borghese es la que más justifica reservar con semanas. Los Museos Capitolinos, en el Campidoglio, tienen la loba, el Marco Aurelio a caballo y una terraza con vista al Foro, y casi nunca hay cola. Y lo mejor de Roma en cuanto a pintura no está en ningún museo: hay Caravaggios colgados gratis en las iglesias del centro.', t:'visita', tip:'Están en San Luigi dei Francesi, a dos calles de Piazza Navona, y en Santa Maria del Popolo. Conviene llevar monedas de un euro, que son las que encienden la luz del cuadro. Del Vaticano hay una sección aparte, que es un día en sí mismo.'},
    {n:'Galleria Doria Pamphilj', d:'Un palacio sobre Via del Corso que sigue siendo de la familia. Salones dorados con los cuadros colgados de arriba abajo como en el siglo XVII, y el retrato de Inocencio X de Velázquez en una salita para él solo. La audioguía la narra el propio príncipe de la casa, contando anécdotas familiares.', t:'visita', p:'€€', w:'https://www.doriapamphilj.it/', tip:'Está a cinco minutos del Panteón y de la Fontana di Trevi, y casi nadie entra. Es el mejor museo poco visitado de Roma.'},
    {nota:1, n:'Museos distintos: Montemartini y la casa de Keats', d:'Centrale Montemartini es una usina eléctrica de principios del siglo XX con las estatuas romanas puestas entre las turbinas y los motores. El contraste es rarísimo y funciona. La Keats-Shelley House está al pie de la escalinata de la Piazza di Spagna: es el cuarto donde murió el poeta Keats a los 25 años, con su biblioteca intacta.', t:'visita', p:'€', tip:'Montemartini está a un par de paradas de metro del centro y no hay nadie nunca. La casa de Keats se ve en media hora y está justo donde de todas formas van a estar.'},
    {n:'Basilica di San Clemente', d:'Tres niveles superpuestos: una basílica del siglo XII sobre una del siglo IV sobre un templo pagano y una casa romana del siglo I. Se baja por escaleras.', t:'visita', p:'€', tip:'Está a cinco minutos del Coliseo y casi no tiene cola. Es la mejor manera de entender cómo se construyó Roma encima de sí misma.'},
    {m:'Piazza di Spagna, Roma', n:'Piazza di Spagna y la escalinata', d:'Las 135 escaleras y la fuente de la Barcaccia abajo. No se puede sentar en los escalones: hay multa.', t:'visita', tip:'Desde arriba, junto a la iglesia de Trinità dei Monti, se ve toda la Via Condotti en línea recta. En diciembre está iluminada.'}
  ]},
  {s:'El Vaticano, que es un día aparte', k:'visita', items:[
    {nota:1, n:'Cuánto lleva y cómo armarlo', d:'Son dos visitas distintas y separadas, con entradas y entradas físicas distintas: los Museos Vaticanos con la Capilla Sixtina por un lado, y la Basílica de San Pedro por otro. Los museos son tres o cuatro horas, la basílica una, y la cúpula otra más. Todo junto es un día entero.', t:'visita', tip:'El orden que mejor funciona: museos a primera hora, salir, almorzar en Prati y hacer la basílica a la tarde. Al revés se llega a los museos con la energía justa cuando ya están llenos.'},
    {nota:1, n:'Cómo llegar', d:'La línea A del metro tiene dos estaciones útiles: Ottaviano, que deja a diez minutos de la Plaza de San Pedro, y Cipro, que queda más cerca de la puerta de los museos, que está del otro lado del muro y a un buen rato a pie de la plaza.', t:'visita', tip:'Si van a los museos primero, bajarse en Cipro. Y si el día está lindo, se puede llegar caminando desde el centro cruzando el Ponte Sant’Angelo, que es de los paseos más lindos de Roma.'},
    {nota:1, n:'Qué días conviene y qué días no', d:'Los museos cierran los domingos, salvo el último de cada mes, que abren gratis medio día. En 2026 ese domingo cae el 29 de noviembre, y gratis significa una cola de horas: es el peor día del viaje para intentarlo. Y el 8 de diciembre, por la Inmaculada, cierran del todo.', t:'visita', tip:'Los lunes son peores de lo que parecen, porque casi todos los museos de Roma cierran ese día y la gente termina acá. El sábado es el día más lleno de la semana. Martes y jueves son los más tranquilos.'},
    {nota:1, n:'Y qué horas', d:'La primera franja, a las 8 de la mañana, es la buena: se camina por salas prácticamente vacías durante la primera hora. La otra ventana razonable es a media tarde, cuando se van los grupos de excursión.', t:'visita', tip:'Los miércoles a la mañana hay audiencia papal y la zona de la plaza se complica, así que ese día conviene dejar la basílica para después del mediodía. Los domingos al mediodía pasa algo parecido con el Ángelus.'},
    {m:'Musei Vaticani, Roma', n:'Museos Vaticanos y Capilla Sixtina', d:'Siete kilómetros de salas que terminan en la Capilla Sixtina. El recorrido es de mano única: no se puede ir directo a la Sixtina, hay que atravesar todo lo demás para llegar.', t:'visita', p:'€€', w:'https://www.museivaticani.va/', tip:'Reservar franja horaria en la web oficial con semanas de anticipación, que además evita la cola de la vereda. Las entradas de reventa cuestan el doble y no dan nada que no dé la oficial.'},
    {nota:1, n:'Qué mirar adentro y qué pasar de largo', d:'Lo que no se puede saltear son tres cosas: la Galería de los Mapas, que es un pasillo largo con la Italia del siglo XVI pintada en las paredes y el techo dorado, las Estancias de Rafael y la Sixtina. La Pinacoteca, con el Caravaggio y el Rafael, está en un ala aparte y vale si les queda energía.', t:'visita', tip:'Lo que se puede cruzar rápido sin remordimiento: el museo egipcio, el etrusco, la sala de carruajes y el arte religioso moderno. Son buenos, pero después de tres horas de pie nadie los disfruta.'},
    {nota:1, n:'La Sixtina, cuando llegan', d:'No se puede sacar fotos ni hablar, y hay guardias que lo recuerdan cada pocos minutos. Se entra ya cansada de caminar, así que conviene sentarse en los bancos laterales un rato largo antes de mirar el techo.', t:'visita', tip:'Del fondo de la Sixtina sale una puerta a la derecha que va directo a la Basílica de San Pedro, pero es solo para los grupos con guía. Sin guía hay que volver por la escalera de caracol y rodear el muro, que son unos veinte minutos más.'},
    {m:'Basilica di San Pietro, Vaticano', n:'Basílica de San Pedro', d:'Entrar es gratis y no hace falta entrada. Lo que hay es una cola para el control de seguridad, que a media mañana da la vuelta a la plaza y a primera hora casi no existe. Abre a las 7.', t:'visita', p:'€', tip:'La Pietà de Miguel Ángel está a la derecha apenas entrando, detrás de un vidrio. La talló con veinticuatro años y es la única obra que firmó en su vida.'},
    {nota:1, n:'La vestimenta, que sí la controlan', d:'Para entrar a la basílica y a los museos hay que tener hombros y rodillas cubiertos, y no se entra con la cabeza cubierta. No es un cartel decorativo: en la puerta dan vuelta a la gente.', t:'visita', tip:'En noviembre y diciembre, con abrigo encima, esto se resuelve solo. El detalle a tener presente es el gorro de lana, que hay que sacarse.'},
    {m:'Cupola di San Pietro, Vaticano', n:'La cúpula de San Pedro', d:'Se sube aparte y se paga aparte, con dos opciones: todo a pie, que son 551 escalones, o ascensor hasta la terraza y 320 escalones desde ahí. El último tramo va inclinado, siguiendo la curva de la cúpula, con la pared torcida contra el hombro.', t:'visita', p:'€', tip:'Antes de salir al balcón exterior se pasa por adentro, al borde del anillo, y se ve la basílica desde arriba a plomo. Esa parte impresiona más que la vista de afuera.'},
    {nota:1, n:'La necrópolis de abajo, si quieren algo raro', d:'Debajo de la basílica hay una calle de tumbas romanas del siglo I, enterrada y excavada, que termina en lo que se considera la tumba de Pedro. Se visita en grupos muy chicos, con guía y en silencio.', t:'visita', tip:'No se compra: se pide por mail a la Oficina de Excavaciones con meses de anticipación y contestan si hay lugar. Si están organizando el viaje con tiempo, es la visita más difícil de conseguir de Roma y la que más se recuerda.'},
    {nota:1, n:'Dónde comer alrededor, y dónde no', d:'La avenida que rodea el muro del Vaticano, justo donde salen todos de los museos, es una hilera de lugares con fotos de los platos en la puerta. Ahí no.', t:'visita', tip:'Caminando cinco o diez minutos hacia Prati está todo lo bueno: Pizzarium Bonci para pizza al corte, Il Sorpasso si quieren sentarse y son las cuatro de la tarde, y la Gelateria dei Gracchi para el postre. Los tres están con ficha propia en las secciones de comer.'}
  ]},
  {s:'Navidad en Roma', k:'navidad', items:[
    {m:'Piazza Navona, Roma', n:'Mercatino di Piazza Navona', d:'Previsto del 1 al 31 de diciembre de 2026. Puestos de dulces, juguetes y adornos alrededor de las fuentes de Bernini, con calesita y la figura de la Befana.', t:'navidad', tip:'Abre hasta la una de la madrugada entre semana y hasta las dos los fines de semana. De noche, con las fuentes iluminadas, es cuando vale la pena.'},
    {m:'Piazza San Pietro, Vaticano', n:'Árbol y belén de la Plaza de San Pedro', d:'Se inauguran a principios de diciembre, con el belén a tamaño real montado junto al obelisco.', t:'navidad', tip:'La plaza iluminada de noche, casi vacía, es una de las mejores estampas del viaje.'},
    {ruta:['Via del Corso, Roma','Via dei Condotti, Roma','Via del Babuino, Roma'], n:'Luces del centro', d:'Via del Corso, Via Condotti y Via del Babuino se iluminan de punta a punta. Condotti pone su instalación de luces sobre la calle de las firmas.', t:'navidad'},
    {nota:1, n:'8 de diciembre: la Inmaculada', d:'Festivo nacional. El Papa acude a la columna de la Inmaculada en la Piazza di Spagna por la tarde. Muchísima gente y buena parte del comercio cerrado.', t:'navidad', tip:'Si caen en Roma ese día, planificarlo como día de paseo y comida, no de museos ni compras.'},
    {nota:1, n:'Conciertos de Navidad en las basílicas', d:'Santa Maria in Aracoeli, Sant’Ignazio y otras basílicas programan coros y música sacra durante todo diciembre, muchos gratuitos.', t:'navidad'}
  ]},
  {s:'Compras y mercadillos', k:'compra', items:[
    {n:'Porta Portese', d:'Domingos de 7:00 a 14:00, en el Trastevere. El mercado de pulgas más grande de Roma: ropa, antigüedades, discos, libros y de todo.', t:'compra', p:'€', tip:'Ir temprano y con el bolso adelante. Es enorme: dos horas y se ve solo una parte.'},
    {n:'Castel Romano Designer Outlet', d:'Outlet de firmas a media hora, con shuttle desde Termini. El descuento del Black Friday se suma al de outlet.', t:'compra', w:'https://www.mcarthurglen.com/it/outlets/it/designer-outlet-castel-romano/', tip:'Reservar el shuttle online. Sale de la zona de Termini varias veces al día.'},
    {n:'Via Cola di Rienzo', d:'En Prati, cruzando el río. Las mismas tiendas que Via del Corso pero sin la multitud, con veredas anchas.', t:'compra', tip:'Es donde compran los romanos. Mucho más agradable que el Corso un sábado.'},
    {ruta:['Via dei Condotti, Roma','Via Borgognona, Roma','Via del Babuino, Roma'], n:'Via Condotti y las calles de firmas', d:'Condotti sale de la Piazza di Spagna en línea recta: Bulgari, Prada, Gucci, Valentino, Cartier, y el Caffè Greco de 1760 en el medio. Alrededor, Via Borgognona, Via Frattina y Via del Babuino hacen el mismo recorrido con menos gente.', t:'compra', tip:'En diciembre las luces de Condotti son las mejores de Roma. Se camina de noche, después de cenar, cuando ya cerraron las tiendas y no queda nadie.'},
    {n:'Mercato Monti', d:'Fines de semana, en el barrio de Monti. Diseño independiente, vintage seleccionado y artesanía joven.', t:'compra', tip:'Monti entero (Via del Boschetto, Via Panisperna) es el mejor barrio de Roma para tiendas chicas.'},
    {n:'Via Sannio', d:'Mercado de ropa junto a San Giovanni, de lunes a sábado por la mañana. Ropa nueva barata y una zona grande de segunda mano.', t:'compra', p:'€'},
    {nota:1, n:'Saldi y Black Friday', d:'Las rebajas de invierno italianas (saldi invernali) empiezan a principios de enero, después del viaje. El Black Friday del 27 de noviembre sí se hace, sobre todo en outlets y cadenas.', t:'compra'}
  ]},
  {s:'Espectáculos de noviembre y diciembre', k:'evento', items:[
    {n:'Teatro dell’Opera di Roma', d:'Temporada de ópera y ballet en el teatro histórico de Via Firenze.', t:'evento', p:'€€', w:'https://www.operaroma.it/'},
    {n:'Auditorium Parco della Musica', d:'El complejo de Renzo Piano, con tres salas y programación constante: clásica, jazz, pop y conferencias.', t:'evento', p:'€€', w:'https://www.auditorium.com/'},
    {nota:1, n:'Roma Jazz Festival', d:'Se celebra en noviembre, sobre todo en el Auditorium. Una de las citas grandes del jazz europeo.', t:'evento', p:'€€', tip:'Confirmar el cartel y las fechas exactas cerca del viaje.'},
    {nota:1, n:'Cartelera oficial', d:'060608.it es el portal oficial de eventos de Roma, con todo lo que pasa día por día. TicketOne vende la mayoría de las entradas.', t:'evento', w:'https://www.060608.it/'}
  ]}
  ]
},
