{
  id:'mil', nav:'Milán', name:'Milán', plate:'ATM', accent:'#3F7361', lt:'#8FCFB6', maps:'Milan',
  lede:'Nadie le da bola a Milán y es un error. El centro es chico y peatonal, el aperitivo es casi una religión, y la primera semana de diciembre junta las dos cosas más milanesas del año: Sant’Ambrogio y la apertura de La Scala. Eso sí, abríguense en serio, que la humedad hace que 5 grados se sientan como 0.',
  quick:[
    ['Se cena','19:30 a 22:00, o aperitivo'],
    ['Urbano','€2,20, 90 minutos'],
    ['Diario','€7,60 · 3 días €15,50'],
    ['Sin papel','Desde 2026 solo contactless o app'],
    ['Diciembre','7° / 1°, niebla y humedad']
  ],
  sections:[
  {s:'Cómo moverse', k:'mover', items:[
    {nota:1, n:'Sin billetes de papel desde 2026', d:'Desde el 1 de enero de 2026 ATM no vende ni acepta billetes de papel. Se viaja apoyando la tarjeta bancaria o el celular en el torno, con la tarjeta recargable RicaricaMi o con billete digital en la app ATM.', t:'mover', tip:'Lo más simple: apoyar la tarjeta contactless al entrar y al salir del metro, como en Londres. Cada una con la suya.'},
    {nota:1, n:'Tarifas', d:'Urbano Mi1-Mi3 €2,20, válido 90 minutos con transbordos. Diario €7,60. Tres días €15,50.', t:'mover', tip:'Si van a hacer más de tres viajes en un día, el diario ya compensa.'},
    {nota:1, n:'Metro', d:'Cuatro líneas útiles: M1 (roja), M2 (verde), M3 (amarilla) y M5 (lila). Entre las cuatro cubren absolutamente todo lo turístico y funcionan muy bien.', t:'mover'},
    {nota:1, n:'Tranvías históricos', d:'Los tranvías de madera de los años 20 siguen en servicio. La línea 1 pasa por el centro y es transporte y paseo a la vez.', t:'mover', tip:'Cuesta lo mismo que cualquier billete. Sentarse en los bancos de madera y cruzar Milán es un plan en sí mismo.'},
    {ruta:['Piazza del Duomo, Milano','Teatro alla Scala, Milano','Brera, Milano','Castello Sforzesco, Milano'], n:'El centro se camina', d:'Duomo → Galleria → La Scala → Brera → Castello Sforzesco es un paseo continuo de 25 minutos, casi todo peatonal.', t:'mover'},
    {nota:1, n:'Aeropuertos', d:'Malpensa Express desde Centrale o Cadorna, unos 50 minutos. Linate está a 15 minutos del centro con la línea M4 del metro.', t:'mover', tip:'Linate con M4 es de las conexiones aeropuerto-centro más cómodas de Europa: metro directo, sin transbordo, con billete urbano normal.'},
    {nota:1, n:'Taxis', d:'No se paran en la calle: hay que ir a una parada o pedirlos por app (FreeNow, itTaxi). Uber solo opera como Black.', t:'mover'}
  ]},
  {s:'Comer', k:'comer', items:[
    {nota:1, n:'Los horarios de comida en Milán', d:'Parecido a Roma pero algo más temprano. Lo propio de Milán es el aperitivo: entre las 18:00 y las 21:00 se paga la bebida y el buffet viene incluido, y para mucha gente eso reemplaza la cena.', t:'comer', tip:'Si lo aprovechan, después no necesitan cenar. Y si igual quieren cenar, las cocinas trabajan hasta cerca de las 22:30.'},
    {n:'Luini', d:'A cincuenta metros del Duomo, desde 1949. El panzerotto (media luna frita rellena de tomate y mozzarella) que se come de pie en la calle. Cuesta unos €3.', t:'comer', p:'€', tip:'Siempre hay cola, pero avanza en cinco minutos. Cierra los domingos.'},
    {n:'Pizzeria Spontini', d:'Un solo producto desde 1953: el trancio, una porción gruesa de pizza margarita con mucho queso. Nada más.', t:'comer', p:'€'},
    {n:'Mercato Centrale Milano', d:'Dentro de la estación Centrale. Puestos de artesanos italianos: pasta fresca, pizza napolitana, carne, helado, vinos. Abierto hasta tarde.', t:'comer', p:'€'},
    {n:'Trattoria Milanese', d:'En el centro, desde 1933. Los dos clásicos de la ciudad hechos como corresponde: risotto alla milanese (con azafrán) y cotoletta alla milanese.', t:'comer', p:'€€', tip:'La cotoletta auténtica es de chuleta con hueso, empanada en pan rallado y frita en mantequilla. Si viene sin hueso y fina, es otra cosa.'},
    {n:'Ratanà', d:'Junto a Porta Nuova, en un edificio de principios del XX. Cocina lombarda de siempre, hecha con muy buen producto, en un salón cálido.', t:'comer', p:'€€', w:'https://www.ratana.it/', tip:'Es de los mejores sitios de Milán en relación calidad-precio. Reservar.'},
    {n:'Trattoria Masuelli San Marco', d:'Familiar desde 1921, con el interior original. Cocina lombarda y piamontesa, sin concesiones ni modernidades.', t:'comer', p:'€€'},
    {m:'Ristorante Cracco, Milano', n:'Cracco in Galleria', d:'Carlo Cracco dentro de la Galleria Vittorio Emanuele, con ventanales sobre la bóveda. Estrella Michelin y una de las mesas más buscadas de Italia.', t:'comer', p:'€€€', w:'https://www.ristorantecracco.it/', tip:'Hay un café y una pastelería en la planta baja, mucho más accesibles, con el mismo escenario.'},
    {m:'Mandarin Oriental, Milano', n:'Seta, Mandarin Oriental', d:'Dos estrellas Michelin, cocina italiana contemporánea de Antonio Guida. La cena de celebración de Milán.', t:'comer', p:'€€€'},
    {m:'Excelsior Hotel Gallia, Milano', n:'Terrazza Gallia', d:'Azotea del Excelsior Hotel Gallia, frente a la estación Centrale. Vista de la ciudad y de los rascacielos de Porta Nuova.', t:'comer', p:'€€€', tip:'Subir solo al aperitivo sale mucho menos que la cena y la vista es idéntica.'}
  ]},
  {s:'Café, panettone y merienda', k:'cafe', items:[
    {n:'Camparino in Galleria', d:'Abierto en 1867 en la esquina de la Galleria, es donde nació el Campari. Barra de mosaicos y hierro forjado art nouveau, intacta.', t:'cafe', p:'€€', w:'https://camparino.com/', tip:'De pie en la barra, un Campari con soda cuesta una fracción de lo que cuesta sentadas en la terraza de la Galleria. El sitio es el mismo.'},
    {n:'Pasticceria Marchesi', d:'Desde 1824, ahora de Prada. El local de la Galleria y el de Via Montenapoleone son de un verde menta y dorado que parece de película.', t:'cafe', p:'€€', tip:'En noviembre y diciembre es el mejor sitio para comprar panettone artesanal. Viene en caja pintada a mano y aguanta el viaje.'},
    {nota:1, n:'Panettone: dónde comprarlo bien', d:'El panettone de verdad es milanés y de temporada: se hace solo en noviembre y diciembre. Marchesi, Cova, Vergani y Giovanni Cova & C. son los nombres.', t:'cafe', tip:'El artesanal se reconoce por la lista de ingredientes corta y porque cuesta entre €30 y €50. El de supermercado no tiene nada que ver.'},
    {n:'Cova Montenapoleone', d:'Fundado en 1817 por un soldado de Napoleón, en plena calle del lujo. Pastelería histórica con salón de té.', t:'cafe', p:'€€'},
    {m:'Orsonero Coffee, Milano', n:'Pavé y Orsonero', d:'Los dos referentes del café de especialidad milanés. Orsonero es diminuto y hace el mejor filtrado de la ciudad; Pavé, la mejor bollería.', t:'cafe', p:'€'}
  ]},
  {s:'Aperitivo y cócteles', k:'coctel', items:[
    {nota:1, n:'El ritual del aperitivo', d:'De 18:00 a 21:00, se paga la bebida (entre €10 y €15) y el buffet de comida viene incluido. Es la institución social milanesa y muchas veces reemplaza la cena.', t:'coctel', p:'€€', tip:'En los Navigli y en Brera están los mejores. Un aperitivo bien elegido resuelve la cena de dos personas por €25 en total.'},
    {n:'Bar Basso', d:'Donde se inventó el Negroni Sbagliato, en 1972, al confundir la ginebra con el prosecco. Lo sirven en una copa enorme y desproporcionada, como corresponde.', t:'coctel', p:'€€', w:'https://www.barbasso.com/', tip:'Está lejos del centro (zona Lambrate), pero es peregrinación obligada. El vaso gigante es parte del chiste.'},
    {n:'Terrazza Aperol', d:'En la Piazza del Duomo, con la catedral enmarcada en el ventanal. Turístico, sí, pero la vista al atardecer es difícil de superar.', t:'coctel', p:'€€'},
    {n:'Dry Milano', d:'Cócteles serios y pizza napolitana en el mismo sitio, en Brera. La combinación funciona mucho mejor de lo que suena.', t:'coctel', p:'€€'},
    {n:'Nottingham Forest', d:'Cócteles de autor y tiki en un local abarrotado de objetos. Está desde hace años entre los mejores bares del mundo.', t:'coctel', p:'€€', tip:'No reservan y es diminuto. Abre sobre las 18:30 y a esa hora todavía se entra sin esperar.'},
    {n:'Ceresio 7', d:'Azotea con dos piscinas sobre el antiguo edificio de Enel, con vista al Cimitero Monumentale y a los rascacielos. De los Dean & Dan de DSquared2.', t:'coctel', p:'€€€'}
  ]},
  {s:'Al aire libre', k:'aire', items:[
    {m:'Duomo di Milano', n:'Terrazas del Duomo', d:'Se sube al tejado y se camina entre los pináculos de mármol y las gárgolas, con la ciudad abajo y los Alpes al fondo en días claros.', t:'aire', p:'€€', w:'https://www.duomomilano.it/', tip:'Subir por las escaleras en vez del ascensor: sale más barato y el recorrido es mejor. Reservar horario online.'},
    {n:'Parco Sempione y Arco della Pace', d:'El parque detrás del Castello Sforzesco, con la Torre Branca (mirador) y el arco neoclásico al fondo. El paseo verde de Milán.', t:'aire'},
    {n:'Navigli', d:'Los canales del sur, diseñados en parte por Leonardo. Naviglio Grande y Naviglio Pavese se llenan de bares al atardecer. Es la zona de aperitivo por excelencia.', t:'aire', tip:'La mejor hora es sobre las 18:00, cuando encienden las luces sobre el agua y empieza el aperitivo. La Darsena, donde se juntan los dos canales, es el punto de encuentro.'},
    {n:'Brera', d:'Calles empedradas, galerías y patios internos. El más bonito para caminar sin destino, y a diez minutos del Duomo.', t:'aire', tip:'La Via Fiori Chiari y la Via Madonnina concentran los mejores rincones. En diciembre está iluminado entero.'},
    {ruta:['Via Montenapoleone, Milano','Via della Spiga, Milano','Piazza del Duomo, Milano','Via Dante, Milano','Castello Sforzesco, Milano'], n:'Paseo por el Quadrilatero y Via Dante', d:'Montenapoleone, Della Spiga, Sant’Andrea y Manzoni forman el cuadrilátero del lujo, con palacios del XVIII y vidrieras montadas como escenografías. Della Spiga es peatonal y la más agradable de las cuatro. Del otro lado del Duomo, Via Dante es una peatonal ancha hasta el Castello, llena de gente y de músicos.', t:'aire', tip:'En diciembre las cuatro calles del cuadrilátero se iluminan y el paseo no cuesta nada. Se hace en media hora y se sale directo a Brera, que está pegado.'},
    {n:'Cimitero Monumentale', d:'Un museo de escultura al aire libre. Mausoleos de todos los estilos, del art nouveau al más contemporáneo, de las grandes familias milanesas. Gratis.', t:'aire', tip:'Suena raro como plan de pareja, pero es una de las visitas más impresionantes de Milán y casi no hay nadie.'},
    {ruta:['Piazza Gae Aulenti, Milano','Bosco Verticale, Milano'], n:'Porta Nuova, Gae Aulenti y Bosco Verticale', d:'El Milán contemporáneo: la plaza circular elevada, los rascacielos y las dos torres cubiertas de árboles. La Biblioteca degli Alberi, al lado, es un parque nuevo y bien hecho.', t:'aire', tip:'De noche, con la fuente de Gae Aulenti iluminada y las torres encendidas, es el mejor contraste con el centro histórico.'},
    {m:'Varenna, Lago di Como', n:'Escapada al Lago de Como', d:'Una hora en tren desde Milano Centrale hasta Varenna, y de ahí ferry a Bellagio. Montañas nevadas sobre el lago en pleno invierno.', t:'aire', tip:'En noviembre y diciembre muchos hoteles y restaurantes de Bellagio cierran, pero el paisaje está en su mejor momento y no hay nadie. Comprobar horarios de ferry antes de ir.'},
    {m:'Citta Alta, Bergamo', n:'Escapada a Bérgamo Alta', d:'50 minutos en tren. Una ciudad medieval amurallada en lo alto de una colina, a la que se sube en funicular.', t:'aire'}
  ]},
  {s:'Imprescindibles y dónde sacar la foto', k:'visita', items:[
    {n:'Duomo di Milano', d:'Seis siglos de construcción, 3.400 estatuas y la Madonnina dorada arriba. El interior es sobrio; el tejado es lo que hay que ver.', t:'visita', p:'€€', tip:'La foto: desde la esquina noreste de la plaza, con la Galleria entrando en el encuadre. Al amanecer no hay nadie.'},
    {n:'Galleria Vittorio Emanuele II', d:'Galería comercial cubierta de 1877, con bóveda de vidrio y hierro. El salón de la ciudad.', t:'visita', tip:'En el suelo, en el mosaico del toro de Turín, la tradición es apoyar el talón y girar tres veces sobre él para tener suerte. Se nota el agujero que dejaron generaciones haciéndolo.'},
    {m:'Santa Maria delle Grazie, Milano', n:'La Última Cena de Leonardo', d:'En el refectorio de Santa Maria delle Grazie. Se entra en grupos de 35 personas por 15 minutos exactos.', t:'visita', p:'€€', w:'https://cenacolovinciano.vivaticket.it/', tip:'Se reserva con meses de antelación y se agota el mismo día que se liberan las entradas. Si no consiguen, hay visitas guiadas que compran cupos: cuestan más pero funcionan.'},
    {m:'Museo Teatrale alla Scala, Milano', n:'Teatro alla Scala y su museo', d:'La ópera más famosa del mundo. Desde el museo se pueden asomar a un palco y ver la sala, aunque no haya función.', t:'visita', p:'€€', w:'https://www.teatroallascala.org/'},
    {n:'Castello Sforzesco', d:'Castillo de los Sforza, con varios museos adentro. En uno de ellos está la Pietà Rondanini, la última escultura de Miguel Ángel, inacabada.', t:'visita', p:'€', tip:'Entrar al patio es gratis. La Pietà Rondanini está en una sala aparte, sola, con luz cenital: vale la entrada.'},
    {n:'Pinacoteca di Brera', d:'La gran pinacoteca milanesa: Rafael, Caravaggio, Mantegna. En el palacio del barrio de Brera.', t:'visita', p:'€€', w:'https://pinacotecabrera.org/'},
    {nota:1, n:'Museos: cuáles valen la pena y cuáles se pueden saltar', d:'La Última Cena es la que hay que reservar con meses, y si no consiguen entrada no pasa nada: Milán no se arruina por eso. La Pinacoteca di Brera es la grande de verdad y se ve en dos horas. Y el Museo del Novecento, en la mismísima Piazza del Duomo, tiene arte del siglo XX y, sobre todo, una ventana desde la que se ve la catedral de frente, iluminada y sin nadie adelante.', t:'visita', tip:'Esa ventana, en la sala de Lucio Fontana, es de las mejores vistas de la ciudad y casi nadie la conoce. La entrada al museo cuesta poco.'},
    {ruta:['Villa Necchi Campiglio, Milano','Museo Poldi Pezzoli, Milano'], n:'Casas museo: Villa Necchi y Poldi Pezzoli', d:'Villa Necchi Campiglio es una casa de los años 30 con pileta y jardín en pleno centro, la de la película Yo soy el amor con Tilda Swinton, y está tal cual la dejó la familia. El Museo Poldi Pezzoli es la casa de un coleccionista del XIX, con armaduras, relojes y el retrato de mujer de Pollaiolo que es medio el ícono de Milán.', t:'visita', p:'€€', tip:'Villa Necchi tiene un café en el jardín que se puede usar aunque no visiten la casa. Es de los rincones más tranquilos del centro.'},
    {n:'Casa Museo Boschi Di Stefano', d:'Un departamento de los años 30 con las paredes cubiertas de arte italiano del siglo XX: Fontana, Morandi, De Chirico, Sironi. Se entra gratis y muchas veces no hay nadie más adentro.', t:'visita', w:'https://www.casemuseo.it/', tip:'Está a diez minutos del Duomo y se ve en cuarenta minutos. De las cosas más raras y mejores que tiene Milán.'},
    {n:'Fondazione Prada', d:'Antigua destilería reconvertida por Rem Koolhaas, con una torre dorada. Dentro está el Bar Luce, diseñado por Wes Anderson como el set de una de sus películas.', t:'visita', p:'€€', w:'https://www.fondazioneprada.org/', tip:'Se puede entrar al Bar Luce sin pagar la entrada del museo. Es de los cafés más fotogénicos de Europa.'},
    {n:'QC Terme Milano', d:'Spa urbano junto a las murallas españolas, con saunas, piscinas al aire libre calientes y un tranvía antiguo convertido en sala de vapor.', t:'visita', p:'€€€', w:'https://www.qcterme.com/', tip:'El mejor plan de pareja para un día de niebla y frío. Reservar con antelación e ir entre semana.'}
  ]},
  {s:'Navidad en Milán', k:'navidad', items:[
    {m:'Castello Sforzesco, Milano', n:'Oh Bej! Oh Bej!', d:'Del 5 al 8 de diciembre de 2026, alrededor del Castello Sforzesco y el Parco Sempione. Unos 230 puestos con artesanía, castañas asadas, libros usados, dulces, flores y adornos. Es la fiesta de Sant’Ambrogio, patrón de la ciudad, y se celebra desde el siglo XVI.', t:'navidad', w:'https://www.yesmilano.it/', tip:'Es la cita más milanesa del año y cae justo en la ventana del viaje. Si pueden elegir cuándo estar en Milán, que sea esa semana. Ir el sábado 5 o el domingo 6 por la mañana.'},
    {m:'Teatro alla Scala, Milano', n:'Prima della Scala', d:'El 7 de diciembre de 2026 abre la temporada con Otello de Verdi, en el debut de Myung-Whun Chung como director musical, con puesta en escena de Damiano Michieletto. Es el acontecimiento social del año en Italia.', t:'navidad', w:'https://www.teatroallascala.org/', tip:'Las entradas de la Prima son inalcanzables, pero se retransmite en pantalla gigante en la Galleria y en varias plazas, y por RAI 1. Hay una anteprima para menores de 30 el 4 de diciembre. La ópera sigue en cartel del 7 de diciembre al 5 de enero, con entradas normales.'},
    {m:'Giardini Indro Montanelli, Milano', n:'Villaggio delle Meraviglie', d:'En los Giardini Indro Montanelli, desde mediados de noviembre hasta enero. Pista de hielo grande (en parte cubierta y climatizada), mercadillo, comida callejera y atracciones. Entrar al parque es gratis.', t:'navidad', w:'https://villaggiodellemeraviglie.com/', tip:'La pista de hielo es de las mayores del norte de Italia. Se paga solo lo que se usa.'},
    {ruta:['Piazza del Duomo, Milano','Via Montenapoleone, Milano','Corso Como, Milano'], n:'Árbol del Duomo y luces', d:'El abeto de la Piazza del Duomo se enciende a finales de noviembre. Via Montenapoleone, Corso Vittorio Emanuele y Corso Como se iluminan enteras.', t:'navidad', tip:'Montenapoleone en diciembre es el mejor paseo de escaparates de Europa, aunque no se entre a ninguna tienda.'},
    {ruta:['Piazza del Duomo, Milano','Via Dante, Milano'], n:'Mercadillos de Piazza Duomo y Via Dante', d:'Casetas de madera con artesanía y comida en pleno centro durante todo diciembre.', t:'navidad'}
  ]},
  {s:'Compras y outlets', k:'compra', items:[
    {n:'Serravalle Designer Outlet', d:'El outlet más grande de Europa, a una hora de Milán. Shuttle oficial desde Largo Cairoli 18 (Zani Viaggi), Milano Centrale y Via Paleocapa 5, junto a Cadorna.', t:'compra', w:'https://www.mcarthurglen.com/en/outlets/it/designer-outlet-serravalle/', tip:'Salidas sobre las 9:00 desde Centrale y 9:30 desde Largo Cairoli, con regreso a las 16:15. Reservar el shuttle online con antelación. La semana del Black Friday es cuando más compensa.'},
    {ruta:['Via Montenapoleone, Milano','Via della Spiga, Milano','Via Sant Andrea, Milano','Via Manzoni, Milano'], n:'Quadrilatero della Moda', d:'Montenapoleone, Della Spiga, Sant’Andrea y Manzoni. El cuadrilátero del lujo mundial. Los escaparates de diciembre son un espectáculo gratuito.', t:'compra'},
    {n:'Corso Buenos Aires', d:'La calle comercial más larga de Europa: más de 350 tiendas de precio medio, sin el ambiente de escaparate del Quadrilatero.', t:'compra', tip:'Es donde compran los milaneses de verdad. Metro Lima o Porta Venezia.'},
    {m:'Libreria Bocca, Galleria Vittorio Emanuele, Milano', n:'Libreria Bocca, en la Galleria', d:'Abierta en 1775, es la librería más antigua de Italia todavía en funcionamiento, y está en el primer piso de la Galleria Vittorio Emanuele. Libros de arte, ediciones de artista y una vista de la bóveda desde arriba.', t:'compra', tip:'Vale subir aunque no compren nada: es de los pocos lugares desde donde se ve la Galleria por dentro y desde lo alto.'},
    {n:'Il Salvagente', d:'Outlet urbano de firmas en Via Fratelli Bronzetti, sin salir de Milán. Restos de colección de marcas grandes a precios de outlet.', t:'compra', p:'€€', tip:'Hay que revolver, pero es la alternativa a Serravalle sin perder un día entero.'},
    {n:'Fiera di Sinigaglia', d:'Sábados en la Darsena, junto a los Navigli. El mercadillo histórico de Milán: vintage, discos, objetos, ropa militar.', t:'compra', p:'€'},
    {nota:1, n:'Vintage: Cavalli e Nastri y Bivio', d:'Cavalli e Nastri (Brera y Navigli) tiene vintage de lujo seleccionado; Bivio compra y vende ropa de segunda mano de marca a precios razonables.', t:'compra', p:'€€'}
  ]},
  {s:'Espectáculos de noviembre y diciembre', k:'evento', items:[
    {n:'Teatro alla Scala', d:'Otello desde el 7 de diciembre, y programación de ópera, ballet y conciertos durante toda la temporada.', t:'evento', p:'€€€', w:'https://www.teatroallascala.org/', tip:'Se venden entradas de galería a precio bajo, y hay 140 localidades de último minuto que se sortean el mismo día en la taquilla. Hay que ir en persona por la tarde.'},
    {n:'Blue Note Milano', d:'El club de jazz más importante de Italia, en la zona de Isola. Dos pases por noche y programación internacional.', t:'evento', p:'€€', w:'https://www.bluenotemilano.com/'},
    {n:'Conservatorio Giuseppe Verdi', d:'Conciertos de cámara y sinfónicos casi todas las semanas, en una sala excelente y a precios muy accesibles.', t:'evento', p:'€€'},
    {m:'Unipol Forum, Assago', n:'Unipol Forum de Assago', d:'Los grandes conciertos internacionales que pasan por Milán. Metro M2 hasta Assago Forum.', t:'evento', w:'https://www.ticketone.it/'},
    {nota:1, n:'Cartelera oficial', d:'YesMilano es el portal oficial de la ciudad, con todos los eventos ordenados por fecha. Vale la pena mirarlo la semana antes de viajar.', t:'evento', w:'https://www.yesmilano.it/en/whats-on'}
  ]}
  ]
},
