{
  id:'tos', nav:'Toscana', name:'Toscana', plate:'Autolinee Toscane', accent:'#5C6E33', lt:'#B6C77E', maps:'Italia',
  opcional:1,
  lede:'Es la única parada del viaje que no es una ciudad sino una región, y eso cambia cómo se arma el día: Florencia se camina como cualquier otra, pero el campo, los pueblos amurallados y las bodegas piden auto o excursión. En noviembre y diciembre está casi vacía, que es la mejor versión que tiene, con la contra de que oscurece tempranísimo y muchas cosas cierran.',
  quick:[
    ['Desde Roma','Tren, 1 h 35 a Florencia'],
    ['Se cena','19:30 a 22:00'],
    ['El auto','Solo para el campo'],
    ['Ojo','ZTL: cámara y multa'],
    ['Noviembre','13° / 5°, oscurece 16:45']
  ],
  sections:[
  {s:'Cómo moverse', k:'mover', items:[
    {nota:1, n:'Desde Roma, en tren', d:'Frecciarossa o Italo salen de Termini y llegan a Firenze Santa Maria Novella en poco más de hora y media, en pleno centro. En auto son casi tres horas de autopista con peaje, y al llegar empieza el problema de dónde dejarlo.', t:'mover', tip:'Comprarlo con semanas de anticipación cambia todo: el mismo asiento pasa de quince euros a más de cien si se compra el mismo día. Y los trenes rápidos no cobran por valija ni pesan nada, al revés que las low cost.'},
    {nota:1, n:'Florencia se camina entera', d:'Del Duomo al Ponte Vecchio hay cinco minutos y a Santa Croce diez. El centro es tan chico que el transporte urbano casi no se usa.', t:'mover', tip:'El tranvía sirve para una sola cosa importante: la línea T2 conecta el aeropuerto de Peretola con la estación en veinte minutos, y sale mucho menos que un taxi.'},
    {nota:1, n:'El auto, solo para los días de campo', d:'Alquilarlo la mañana que salen al Chianti o a la Val d’Orcia y devolverlo al volver. Tenerlo estacionado en Florencia mientras tanto es pagar cochera cara por un problema.', t:'mover', tip:'Las oficinas de alquiler están junto a la estación de Santa Maria Novella y en el aeropuerto. Pedir auto chico: las calles de los pueblos son de un ancho de carro, literalmente.'},
    {nota:1, n:'La ZTL, que es la trampa cara del viaje', d:'Casi todos los centros históricos, Florencia incluida, son zona de tráfico limitado. Hay cámaras en cada entrada y te sacan una foto por cada vez que cruzás. La multa no llega en el momento: aparece meses después por la empresa de alquiler, que además suma su propio cargo administrativo.', t:'mover', tip:'El cartel es un círculo blanco con borde rojo. Ahí empieza, y se estaciona antes. Si el alojamiento queda adentro, mandarle la matrícula a la recepción con anticipación para que la registren, y pedir que confirmen por escrito.'},
    {nota:1, n:'Dónde dejar el auto en Siena', d:'Siena resolvió esto mejor que nadie: hay estacionamientos en la ladera, fuera de la muralla, con escaleras mecánicas que suben directo al centro. El de San Francesco y el de Santa Caterina son los más cómodos.', t:'mover', tip:'Cuestan unos pocos euros por hora y se paga a la salida. Buscarlos por nombre en el mapa antes de arrancar, porque el cartel aparece cuando ya estás encima.'},
    {nota:1, n:'Dónde dejar el auto en San Gimignano', d:'El pueblo entero está adentro de la muralla y es ZTL: no se entra. Los estacionamientos son numerados y están afuera. El P1, Giubileo, es el más barato y queda a diez o quince minutos a pie de la puerta; el P2, Montemaggio, está pegado a la entrada y sale bastante más.', t:'mover', tip:'De noche cuesta casi nada. Si duermen ahí, el pueblo vacío después de que se van los buses de excursión es una de las mejores cosas de la Toscana en invierno.'},
    {nota:1, n:'Si no alquilan auto', d:'Se puede igual, con recortes. En tren se llega a Siena, Lucca, Pisa, Arezzo y Pistoia sin cambiar nada. A San Gimignano no llega el tren: hay bus desde Florencia con cambio en Poggibonsi, o desde Siena.', t:'mover', tip:'La Val d’Orcia y el Chianti son el punto donde el transporte público deja de servir. Para esos dos, o auto, o una excursión de un día, o un chofer entre las dos, que dividido no sale tan distinto de alquilar.'},
    {nota:1, n:'Manejar en el campo, en invierno', d:'Las rutas son de curvas y muchos accesos a bodegas y caseríos son de tierra blanca compactada, las famosas strade bianche. Se anda bien despacio, pero con lluvia se embarran.', t:'mover', tip:'A las 16:45 ya es noche cerrada y en el campo no hay iluminación ninguna. Armar los días para estar de vuelta con luz, que además es cuando cierran las bodegas.'},
    {nota:1, n:'Peaje y nafta', d:'La autopista A1 es de peaje: se saca un ticket al entrar y se paga al salir, con tarjeta sin problema. En las estaciones de servicio hay dos precios para el mismo combustible, el de autoservicio y el de atendido, y la diferencia por tanque se nota.', t:'mover', tip:'Buscar el surtidor que dice fai da te, que es el de autoservicio. Y devolver el auto con el tanque como te lo dieron: rellenarlo la rentadora siempre sale peor.'}
  ]},
  {s:'Comer', k:'comer', items:[
    {nota:1, n:'Los horarios, y por qué acá importan más', d:'Florencia funciona parecido a Roma: almuerzo de 12:30 a 14:30 y cena desde las 19:30. En los pueblos chicos es más estricto, la cocina cierra a las 14:00 y no vuelve hasta las 19:30, y en invierno muchos lugares cierran un día entre semana.', t:'comer', tip:'Antes de manejar media hora hasta un pueblo para almorzar, mirar el horario en Google o llamar. En noviembre es bastante común encontrar el cartel de cerrado por temporada.'},
    {nota:1, n:'Cómo se pide una bistecca alla fiorentina', d:'No es un plato individual: es un corte enorme que se pide por peso para compartir, y difícilmente baje del kilo. Viene poco hecha y eso no se negocia, es parte de lo que es.', t:'comer', tip:'Se piden dos guarniciones aparte y con eso comen las dos de sobra. Si a alguna la carne muy jugosa no le va, mejor pedir otra cosa y no arruinar el plato pidiéndolo cocido.'},
    {a:'Firenze', n:'All’Antico Vinaio', d:'La schiacciata más famosa de Italia: un pan plano gigante relleno de embutidos, quesos y cremas, por unos pocos euros. Hay varios locales de la misma casa en la misma cuadra de Via dei Neri.', t:'comer', p:'€', tip:'La cola parece imposible y avanza rápido. Pedir la mitad si no vienen con mucha hambre, porque la entera es enorme, y comerla parada en la calle como todo el mundo.'},
    {a:'Firenze', n:'Trattoria Mario', d:'Junto al Mercato Centrale, abierta desde 1953 y solo al mediodía. Se comparte mesa con desconocidos, la carta está escrita a mano cada día y se paga en efectivo.', t:'comer', p:'€', tip:'Abre a las 12 y a las 12:20 ya hay cola. Es de los pocos lugares del centro donde sigue comiendo gente del barrio.'},
    {a:'Firenze', n:'Trattoria Sostanza', d:'De 1869, con mesas comunes y cocina a la vista. Famosa por dos cosas: la bistecca y el petto di pollo al burro, una pechuga en manteca que no parece gran cosa escrita y es memorable.', t:'comer', p:'€€', tip:'Se reserva por teléfono y conviene hacerlo con días. Hay dos turnos de cena y el primero es el más temprano de Florencia.'},
    {a:'Firenze', n:'Il Latini', d:'Jamones colgando del techo, mesas largas y un menú toscano clásico que va saliendo sin que uno pida demasiado. Ruidoso, familiar y muy divertido.', t:'comer', p:'€€', tip:'No siempre respetan la reserva a rajatabla: se hace un rato de cola en la vereda con una copa de vino en la mano. Es parte del asunto.'},
    {m:'Mercato Centrale Firenze', n:'Mercato Centrale', d:'Abajo, el mercado de siempre con puestos de fiambre, quesos y pasta. Arriba, un patio de comidas grande y abierto hasta tarde, útil cuando las trattorias ya cerraron cocina.', t:'comer', p:'€', tip:'Abajo está Nerbone, un puesto de 1872 donde se come el bollito y el lampredotto de pie en la barra. Es más barato y mejor que casi todo lo de arriba.'},
    {nota:1, n:'El lampredotto, que hay que probarlo', d:'El sándwich callejero de Florencia: mondongo hervido largo rato, metido en un pan mojado en el caldo, con salsa verde y un poco de picante. Se vende en carritos en la calle y cuesta unos pocos euros.', t:'comer', tip:'Suena feo y está buenísimo. Si a alguna no la convence, en el mismo carrito venden el bollito, que es carne hervida normal en el mismo pan. Los carritos buenos están en el Mercato Centrale, en Sant’Ambrogio y junto a la casa de Dante.'},
    {a:'Firenze', n:'Buca Lapi', d:'En el sótano del Palazzo Antinori, con las paredes empapeladas de afiches de viaje viejos. Es de los más antiguos de la ciudad y de los más serios para una bistecca.', t:'comer', p:'€€€', tip:'Reservar. Si van a hacer una sola cena cara en la Toscana, la bistecca acá con una botella de Chianti Classico es la versión completa de lo que vinieron a comer.'},
    {a:'Siena', n:'La Taverna di San Giuseppe', d:'En un sótano excavado en la roca etrusca, a cinco minutos de la Piazza del Campo. Cocina sienesa seria, con pici hechos a mano y una carta de vinos larga.', t:'comer', p:'€€', tip:'Reservar con días. Es de los pocos lugares de Siena que no bajan la guardia con el turismo.'},
    {a:'Siena', n:'Trattoria Papei', d:'Detrás de la Piazza del Campo, en la Piazza del Mercato. Casera, barata y de toda la vida: pici all’aglione, ribollita, conejo.', t:'comer', p:'€'},
    {a:'San Gimignano', n:'Dal Bertelli', d:'Un cuarto diminuto sin mesas, con jamones colgados y libros viejos en los estantes. Hacen un solo tipo de cosa, sándwiches de embutido y queso de la zona, y los hacen muy bien.', t:'comer', p:'€', tip:'No hay carta ni precios a la vista: se elige señalando. Cierra temprano y cuando se acaba el pan, se acabó.'},
    {nota:1, n:'La trufa blanca, que es justo ahora', d:'Noviembre es el mes de la trufa blanca, y una de las zonas buenas de Italia es San Miniato, entre Florencia y Pisa, que arma una feria los fines de semana de noviembre.', t:'comer', tip:'La trufa fresca es carísima por peso, pero en las trattorias de esas semanas aparece rallada sobre huevos o sobre tagliolini, y ahí sale mucho menos. Es la forma sensata de probarla.'}
  ]},
  {s:'Café y gelato', k:'cafe', items:[
    {a:'Firenze', n:'Vivoli', d:'De 1930 y en manos de la misma familia desde entonces. Lo sirven en vaso a propósito, para que el barquillo no le cambie la temperatura ni el gusto.', t:'cafe', p:'€', tip:'Pedir el affogato: gelato de crema con un espresso caliente encima, tirado en el momento. En invierno es mejor idea que un cucurucho.'},
    {a:'Firenze', n:'Gelateria dei Neri', d:'A media cuadra de Via dei Neri, con tandas chicas y sabores que cambian. De los mejores de Florencia sin ser el más famoso.', t:'cafe', p:'€'},
    {a:'Firenze', n:'La Carraia', d:'Al pie del puente del mismo nombre, sobre el Arno. Es donde van los estudiantes: barato, bueno y siempre lleno.', t:'cafe', p:'€', tip:'Cruzar al Oltrarno con el helado en la mano y seguir caminando por la orilla. El puente de al lado, el Santa Trinita, tiene la mejor vista del Ponte Vecchio.'},
    {a:'San Gimignano', n:'Gelateria Dondoli', d:'En la Piazza della Cisterna, del heladero que ganó el campeonato mundial de gelato. Sabores raros que funcionan, tipo azafrán con piñones o queso de oveja con nueces.', t:'cafe', p:'€', tip:'En verano la cola da la vuelta a la plaza; en noviembre se entra caminando. Es una de las ventajas de venir ahora.'},
    {a:'Firenze', n:'Ditta Artigianale', d:'Café de especialidad, tostado propio y gente que sabe lo que hace. Es de los pocos lugares de Italia donde se puede pedir un café con leche a la tarde sin que nadie levante una ceja.', t:'cafe', p:'€', tip:'Tienen varias sucursales; la de Via dei Neri es la más cómoda para sentarse a trabajar o a matar una hora de lluvia.'},
    {m:'Rivoire, Piazza della Signoria, Firenze', n:'Rivoire', d:'Frente al Palazzo Vecchio desde 1872. El chocolate caliente es espeso de verdad, casi para comer con cuchara, y la vista desde la mesa de afuera es la Piazza della Signoria entera.', t:'cafe', p:'€€', tip:'Es caro y se paga la ubicación, pero una vez vale. Si prefieren lo mismo más barato, Gilli en Piazza della Repubblica es igual de histórico y algo menos turístico.'},
    {nota:1, n:'El desayuno toscano, que dura tres minutos', d:'Se toma de pie en la barra: un café y una pasta dulce, casi siempre un cornetto. No existe el desayuno largo, y sentarse a una mesa para eso cuesta el doble.', t:'cafe', tip:'La versión local del cornetto es la schiacciata con l’uva en otoño, un pan dulce aplastado con uva adentro. Si la ven en una panadería, comprarla.'}
  ]},
  {s:'Vino y cócteles', k:'coctel', items:[
    {nota:1, n:'Las buchette del vino', d:'En los palacios de Florencia hay ventanitas de medio metro a la altura de la cintura: por ahí las familias nobles vendían su vino directo a la calle en el siglo XVI. Varias volvieron a funcionar y te pasan la copa por el hueco.', t:'coctel', tip:'La más fácil de encontrar abierta es la de Babae, en Via Santo Spirito, que abre a la tarde. Hay un mapa de las que quedan, y buscarlas es una excusa perfecta para caminar el Oltrarno.'},
    {a:'Firenze', n:'Le Volpi e l’Uva', d:'Enoteca chiquita en una plaza escondida cruzando el Ponte Vecchio. Vinos por copa de productores pequeños y tablas de queso y fiambre para acompañar.', t:'coctel', p:'€', tip:'Se puede pedir que te hagan probar antes de elegir. Es el mejor lugar para entender qué es el Chianti Classico sin ir hasta el Chianti.'},
    {a:'Firenze', n:'Manifattura', d:'Coctelería que usa solo destilados italianos, con estética de los años sesenta. El Negroni, que se inventó en Florencia, acá se toma como corresponde.', t:'coctel', p:'€€'},
    {a:'Firenze', n:'Locale', d:'Adentro de un palacio renacentista, con un patio cubierto lleno de plantas y luz baja. Es el trago caro y lindo de Florencia.', t:'coctel', p:'€€€', tip:'Ir temprano, cerca de las 19, que después se llena y se pierde la parte de estar en un palacio en silencio.'},
    {a:'Firenze', n:'Rasputin', d:'Bar clandestino sin cartel, detrás de una puerta que no parece una puerta, en el Oltrarno. Coctelería clásica y luz de vela.', t:'coctel', p:'€€', tip:'Hay que reservar y les mandan la dirección exacta. Sin reserva es probable que no abran.'},
    {m:'Antinori nel Chianti Classico, Bargino', n:'Antinori nel Chianti Classico', d:'Una bodega enterrada en la colina, con el techo cubierto de viñedo y una escalera de caracol que baja entre las barricas. La familia hace vino desde 1385 y el edificio es de los mejores de la arquitectura italiana reciente.', t:'coctel', p:'€€', w:'https://www.antinorichianticlassico.it/', tip:'Está a media hora de Florencia y se visita con reserva. Es la bodega más fácil de sumar a un día de Chianti sin meterse en caminos de tierra.'},
    {nota:1, n:'Bodegas en invierno', d:'Siguen recibiendo, pero con horario corto y solo con reserva previa. La ventaja es grande: en vez de una visita en grupo de treinta personas, muchas veces las atiende el dueño sin apuro.', t:'coctel', tip:'Si manejan, acuerden antes quién prueba y quién no. Una degustación son cinco o seis copas por cabeza, que es media botella, y los controles en la ruta existen.'},
    {a:'Montalcino', n:'Enoteca de la Fortezza de Montalcino', d:'Adentro de la fortaleza del pueblo, con mesas entre los muros. Es el lugar más directo para probar un Brunello sin sacar turno en una bodega.', t:'coctel', p:'€€', tip:'El Brunello necesita años en botella y por eso es caro. El Rosso di Montalcino es el mismo viñedo con menos crianza, sale bastante menos y para tomar ahora está mejor.'}
  ]},
  {s:'Al aire libre', k:'aire', items:[
    {m:'Piazzale Michelangelo, Firenze', n:'Piazzale Michelangelo', d:'La vista postal de Florencia entera, con el Duomo, el campanile y el río en la misma foto. Está en alto, cruzando el Arno.', t:'aire', tip:'Subir a pie desde el Ponte alle Grazie por las rampas del Poggi, que son escaleras entre jardines y fuentes, y no en bus. En invierno el atardecer es a las 16:45, así que se hace temprano y queda toda la noche libre.'},
    {m:'Giardino Bardini, Firenze', n:'Giardino Bardini', d:'Un jardín en pendiente con una pérgola de glicinas y una terraza que mira al Duomo de frente. Al lado del Boboli y con una décima parte de la gente.', t:'aire', p:'€', tip:'La terraza del café de arriba tiene la misma vista que el Piazzale, sentadas y sin nadie. Es de las cosas mejor guardadas de Florencia.'},
    {m:'Giardino di Boboli, Firenze', n:'Giardino di Boboli', d:'El jardín del Palazzo Pitti: estatuas, un anfiteatro y senderos de cipreses. Grande de verdad, para una mañana entera.', t:'aire', p:'€€'},
    {ruta:['Ponte Vecchio, Firenze','Piazza Santo Spirito, Firenze','Piazza della Passera, Firenze','San Niccolo, Firenze'], n:'El paseo del Oltrarno', d:'Cruzar el río y meterse del otro lado, que es donde todavía viven florentinos: talleres de restauración, tiendas de artesanos, la Piazza Santo Spirito con su iglesia sin fachada y la Piazza della Passera, minúscula.', t:'aire', tip:'Hacerlo a la tarde y terminar en San Niccolò, que es la zona de bares. Los talleres cierran temprano, así que ver primero y tomar algo después.'},
    {m:'Ponte Santa Trinita, Firenze', n:'Ponte Santa Trinita', d:'El puente de al lado del Ponte Vecchio. Suena tonto pero es importante: la foto del Ponte Vecchio no se saca desde el Ponte Vecchio, se saca desde acá.', t:'aire', tip:'Al atardecer, con el reflejo en el Arno y las luces encendiéndose, es la mejor foto de la ciudad. Y es gratis y no tiene cola.'},
    {m:'Podere Belvedere, San Quirico d’Orcia', n:'Los cipreses de la Val d’Orcia', d:'La imagen que todo el mundo tiene de la Toscana: colinas peladas, una casa de piedra sola arriba y una fila de cipreses subiendo. La zona buena está entre San Quirico d’Orcia y Pienza.', t:'aire', tip:'Los dos lugares con nombre propio son el Podere Belvedere y la capilla de la Madonna di Vitaleta. Se ven desde la ruta y hay banquinas para parar. En invierno el campo está verde y con niebla baja, que es distinto a la foto de verano y bastante mejor.'},
    {ruta:['Greve in Chianti','Panzano in Chianti','Radda in Chianti','Castellina in Chianti'], n:'La ruta del Chianti en auto', d:'Greve, Panzano, Radda y Castellina, cuatro pueblos de piedra encadenados por una ruta de curvas entre viñedos. Es medio día largo con paradas, y se puede hacer entre Florencia y Siena en vez de tomar la autopista.', t:'aire', tip:'En Panzano está la carnicería de Dario Cecchini, que es una atracción en sí misma: recita a Dante mientras corta y convida vino y pan con manteca de cerdo a quien entre.'},
    {m:'Bagno Vignoni, San Quirico d’Orcia', n:'Bagno Vignoni', d:'Un pueblo donde la plaza principal no es una plaza: es una piscina termal del siglo XV, llena de agua caliente que humea. No se puede entrar a esa, pero verla humear en una mañana fría es raro y lindo.', t:'aire', tip:'Alrededor hay establecimientos donde sí se entra al agua. En invierno, con cinco grados afuera, meterse en agua termal al aire libre es de las mejores cosas que se pueden hacer en la Toscana.'},
    {m:'Bagni San Filippo, Castiglione d’Orcia', n:'Bagni San Filippo', d:'Una cascada termal en el medio del bosque, con las piedras cubiertas de una costra blanca de calcio que parece hielo. Es gratis, al aire libre y siempre está a temperatura de bañadera.', t:'aire', tip:'Llevar toalla, ojotas y una bolsa para la ropa mojada, porque no hay vestuario ni nada. El agua huele a azufre y el olor se queda en la malla.'},
    {m:'Mura di Lucca', n:'Las murallas de Lucca', d:'Lucca conserva la muralla completa, y arriba hay un paseo arbolado de cuatro kilómetros que da la vuelta a la ciudad entera. Se camina o se anda en bicicleta.', t:'aire', tip:'Hay alquiler de bicicletas en varias puertas. La vuelta entera lleva menos de una hora pedaleando y se ve la ciudad desde arriba todo el tiempo.'},
    {m:'Piazza del Campo, Siena', n:'Piazza del Campo', d:'Una plaza en pendiente con forma de concha, hecha de ladrillo, donde corre el Palio. La gente se sienta directamente en el suelo inclinado a mirar.', t:'aire', tip:'Hacer eso, sentarse en el ladrillo un rato. Es lo que hace todo el mundo en Siena y es más lindo que cualquier café de la plaza, que además son caros.'},
    {m:'Fiesole, Firenze', n:'Fiesole', d:'Un pueblo en la colina justo arriba de Florencia, con teatro romano y una vista de la ciudad desde más lejos y más alto que el Piazzale.', t:'aire', tip:'Se llega con el bus 7 desde la estación en media hora. Es la escapada más fácil si les sobra media tarde y no quieren manejar.'}
  ]},
  {s:'Imprescindibles y dónde sacar la foto', k:'visita', items:[
    {m:'Cattedrale di Santa Maria del Fiore, Firenze', n:'Duomo y cúpula de Brunelleschi', d:'La catedral por dentro es sorprendentemente pelada y la entrada es gratis. Lo que se paga y se reserva es subir a la cúpula: 463 escalones por una escalera angosta que en el último tramo va entre las dos capas de la bóveda.', t:'visita', p:'€€', w:'https://duomo.firenze.it/', tip:'La franja horaria se agota con dos o tres semanas. Y una cosa que casi nadie piensa: desde la cúpula no se ve la cúpula. La mejor foto es desde el Campanile de Giotto, que está al lado y tiene la misma vista con el Duomo adentro.'},
    {nota:1, n:'Claustrofobia y la cúpula', d:'El tramo final son escaleras de caracol muy angostas, con gente subiendo y bajando por el mismo hueco y sin lugar donde parar a mitad de camino.', t:'visita', tip:'Si a alguna eso le juega en contra, el Campanile de Giotto es escalera abierta, tiene descansos y llega casi a la misma altura. Y desde arriba se ve la cúpula, que es lo que uno quiere ver.'},
    {m:'Galleria degli Uffizi, Firenze', n:'Galleria degli Uffizi', d:'El Nacimiento de Venus, la Primavera, los Botticelli, Leonardo, Caravaggio. Es de los museos más importantes del mundo y se recorre en tres horas largas.', t:'visita', p:'€€', w:'https://www.uffizi.it/', tip:'Cierra los lunes. Reservar franja horaria por la web oficial y entrar temprano. El corredor de las ventanas sobre el Arno, al final, es donde casi nadie se detiene y es lo mejor del edificio.'},
    {m:'Galleria dell’Accademia, Firenze', n:'Galleria dell’Accademia y el David', d:'Está el David y está en una sala hecha para él, con luz cenital. Verlo en persona sí cambia algo: la escala y las manos no se entienden en foto.', t:'visita', p:'€€', w:'https://www.galleriaaccademiafirenze.it/', tip:'Cierra los lunes y hay que reservar. Siendo honestos, el resto del museo es menor: se entra, se ve el David y los Prisioneros sin terminar del camino de entrada, y en una hora están afuera.'},
    {m:'Palazzo Vecchio, Firenze', n:'Palazzo Vecchio y la Torre de Arnolfo', d:'El ayuntamiento desde el siglo XIV, con el Salone dei Cinquecento, que es una sala enorme cubierta de frescos. Se puede subir a la torre aparte.', t:'visita', p:'€€', tip:'La torre es la vista de Florencia con el Duomo bien cerca y desde adentro de la ciudad, no desde afuera. Menos famosa que la cúpula y con muchísima menos cola.'},
    {m:'Basilica di Santa Croce, Firenze', n:'Basilica di Santa Croce', d:'Adentro están enterrados Miguel Ángel, Galileo, Maquiavelo y Rossini, uno al lado del otro. Es prácticamente el panteón de Italia.', t:'visita', p:'€', tip:'La plaza de afuera es donde se monta el mercado navideño en diciembre, así que conviene combinar las dos cosas el mismo día.'},
    {m:'Cappelle Medicee, Firenze', n:'Cappelle Medicee', d:'Las tumbas de los Médici, con la Sagrestia Nuova diseñada y esculpida por Miguel Ángel. Está a dos cuadras del Duomo y casi nunca tiene cola.', t:'visita', p:'€', tip:'Si tuvieran que elegir un solo museo chico en Florencia, este. Se ve en una hora y es Miguel Ángel puro, sin la multitud del David.'},
    {m:'Ponte Vecchio, Firenze', n:'Ponte Vecchio', d:'El puente con casas y joyerías encima, el único que los alemanes no volaron en 1944. Arriba de las tiendas pasa el Corredor Vasariano, el pasillo privado que los Médici usaban para cruzar el río sin pisar la calle.', t:'visita', tip:'Cruzarlo temprano, antes de las nueve, cuando las joyerías todavía tienen los postigos de madera cerrados y parece otra cosa.'},
    {m:'Duomo di Siena', n:'Duomo de Siena', d:'Rayado en mármol blanco y negro por dentro y por fuera, con el piso hecho de escenas de mármol embutido y la Libreria Piccolomini pintada entera al fresco. Para mucha gente es más impresionante que el de Florencia.', t:'visita', p:'€€', tip:'El piso completo solo se destapa unas semanas al año, entre agosto y octubre, así que en el viaje va a estar tapado en parte. Igual vale mucho la pena.'},
    {m:'Torre del Mangia, Siena', n:'Torre del Mangia', d:'La torre del ayuntamiento de Siena, altísima y flaquísima, con vista a la plaza en concha desde arriba y al campo sienés alrededor.', t:'visita', p:'€', tip:'Son más de trescientos escalones y dejan subir a poca gente por vez, así que puede haber espera. En invierno, poca.'},
    {m:'Piazza della Cisterna, San Gimignano', n:'San Gimignano y sus torres', d:'Un pueblo amurallado con catorce torres medievales todavía en pie, que eran la manera que tenían las familias ricas de medirse entre ellas. Se ve desde lejos en la ruta y parece un dibujo.', t:'visita', tip:'La Torre Grossa se puede subir y es la única que deja ver las otras trece. Y la Rocca, arriba del todo, es un mirador gratis entre olivos donde no hay nadie al atardecer.'},
    {m:'Pienza, Siena', n:'Pienza', d:'Un pueblo renacentista de bolsillo, diseñado entero de una vez en el siglo XV. Se recorre en dos horas y tiene un camino de ronda con la Val d’Orcia entera de fondo.', t:'visita', tip:'Es la capital del pecorino de oveja. Las queserías dejan probar antes de comprar y venden envasado al vacío, que aguanta el viaje de vuelta.'},
    {m:'Montepulciano, Siena', n:'Montepulciano', d:'Un pueblo largo y en subida sobre una loma, con bodegas históricas que tienen las cavas excavadas debajo de las casas del centro.', t:'visita', tip:'La calle principal sube en serio. Estacionar arriba y bajar caminando, no al revés.'},
    {m:'Arezzo, Toscana', n:'Arezzo y los frescos de Piero della Francesca', d:'La Leyenda de la Vera Cruz, en la Basílica de San Francesco: uno de los ciclos de frescos más importantes del Renacimiento, y casi no va nadie.', t:'visita', p:'€', tip:'Se entra por turnos cortos y con reserva. Arezzo además es donde está el mercado navideño más grande de la Toscana, así que el día cierra solo.'},
    {nota:1, n:'Qué se puede saltar sin culpa', d:'La torre de Pisa se ve en una hora y la foto es la misma que sacaron todos: si el tiempo aprieta, se puede dejar afuera o pasar de camino a otro lado. Y los museos chicos de Florencia son muchos y buenos, pero uno o dos alcanzan.', t:'visita', tip:'Si van a Pisa igual, la Piazza dei Miracoli entera vale más que la torre sola, y el Camposanto de al lado está casi vacío siempre.'},
    {nota:1, n:'El primer domingo de mes, en Italia', d:'Los museos estatales italianos abren gratis el primer domingo de cada mes. En el viaje eso cae el 1 de noviembre y el 6 de diciembre, y alcanza a los Uffizi, la Accademia y buena parte de lo demás.', t:'visita', tip:'Gratis quiere decir sin reserva y con mucha gente. Si quieren aprovecharlo, llegar antes de que abra; si no, esos dos días son perfectos para dedicarlos al campo o a los pueblos.'}
  ]},
  {s:'Navidad en la Toscana', k:'navidad', items:[
    {m:'Piazza Grande, Arezzo', n:'Arezzo Città del Natale', d:'El evento navideño más grande de la Toscana, previsto de mediados de noviembre al 6 de enero. Mercado tirolés de casitas de madera en la Piazza Grande, casa de Papá Noel y proyecciones sobre las fachadas renacentistas.', t:'navidad', w:'https://mercatininatalearezzo.it/', tip:'Arezzo está a una hora de tren de Florencia y a una hora y media de Roma, así que se puede hacer en el día desde cualquiera de las dos. Ir entre semana.'},
    {m:'Piazza Santa Croce, Firenze', n:'Weihnachtsmarkt de Santa Croce', d:'El mercado navideño de Florencia, de casitas de madera al estilo del Tirol, montado en la plaza de Santa Croce. Vino caliente, embutidos y artesanía.', t:'navidad', tip:'Las fechas exactas se anuncian tarde: suele arrancar entre mediados y fines de noviembre. Conviene confirmarlo cerca del viaje.'},
    {nota:1, n:'Florence Lights Up', d:'Durante diciembre proyectan video e instalaciones de luz sobre las fachadas y los monumentos del centro. Cambia cada año y es gratis, se ve caminando.', t:'navidad', tip:'Suele empezar a principios de diciembre. Es lo que hace que valga la pena caminar el centro de noche aunque haga frío.'},
    {m:'Piazza del Campo, Siena', n:'Mercato nel Campo, Siena', d:'Siena arma un mercado de época en la Piazza del Campo a principios de diciembre, con puestos de comida y artesanía de la provincia rodeando la concha.', t:'navidad', tip:'Es de un fin de semana solo y la fecha cambia cada año, así que hay que mirarlo cerca. Si coincide, es el mejor día para ir a Siena.'},
    {nota:1, n:'Dos feriados que caen en el viaje', d:'El 1 de noviembre es Todos los Santos y el 8 de diciembre es la Inmaculada, y los dos son feriados nacionales en Italia. El 8 es además el día en que tradicionalmente se arma el árbol y se prenden las luces en todos lados.', t:'navidad', tip:'Esos días muchos comercios cierran y los pueblos se llenan de italianos de paseo. Son buenos para mercados y malos para museos y compras.'}
  ]},
  {s:'Compras y mercadillos', k:'compra', items:[
    {m:'Officina Profumo Farmaceutica di Santa Maria Novella, Firenze', n:'Officina di Santa Maria Novella', d:'Una perfumería y herboristería que funciona desde 1612, en las capillas frescadas de un convento dominico. Vale entrar aunque no compren nada: es medio tienda y medio museo.', t:'compra', w:'https://smnovella.com/', tip:'El agua de colonia y los jabones vienen en cajas que son un regalo resuelto y pesan poco. Está a dos cuadras de la estación.'},
    {m:'Scuola del Cuoio, Firenze', n:'Scuola del Cuoio', d:'Una escuela taller de marroquinería adentro del convento de Santa Croce, abierta desde la posguerra. Se entra y se ve trabajar a los artesanos en el mismo lugar donde venden.', t:'compra', p:'€€', tip:'Acá el cuero es cuero. Es la referencia contra la cual comparar lo que ofrecen en la calle, aunque después compren en otro lado.'},
    {nota:1, n:'El cuero de San Lorenzo, con cuidado', d:'Los puestos del mercado de San Lorenzo venden campera y cartera de cuero por todos lados, y la calidad va desde muy buena hasta sintético con olor a cuero puesto encima.', t:'compra', tip:'El cuero de verdad tiene poros irregulares, huele fuerte y no es perfectamente parejo. Regatear se estila. Y si dudan, mejor pagar más en una tienda con nombre que llevarse algo que se despega en seis meses.'},
    {m:'The Mall Luxury Outlets, Leccio, Reggello', n:'The Mall Luxury Outlets', d:'El outlet de firmas alto de la Toscana, con Gucci, Prada, Saint Laurent y compañía, a media hora de Florencia. El descuento del Black Friday se suma al de outlet.', t:'compra', w:'https://www.themall.it/', tip:'Hay shuttle desde Florencia que sale de la estación y se reserva online. Y si no viven en la Unión Europea pueden pedir la devolución del IVA: guardar los tickets.'},
    {m:'Barberino Designer Outlet', n:'Barberino Designer Outlet', d:'El otro outlet, más de marca de cadena y menos de lujo. Al norte de Florencia, también con shuttle.', t:'compra', w:'https://www.mcarthurglen.com/it/outlets/it/designer-outlet-barberino/'},
    {m:'Fiera Antiquaria di Arezzo, Piazza Grande', n:'Fiera Antiquaria de Arezzo', d:'La feria de antigüedades más grande de Italia, el primer domingo de cada mes y el sábado anterior, ocupando la Piazza Grande y las calles de alrededor. Muebles, discos, lámparas, ropa vieja.', t:'compra', p:'€', tip:'En el viaje caen el 1 de noviembre y el 6 de diciembre. El de diciembre coincide con el mercado navideño, así que Arezzo ese fin de semana es un día entero.'},
    {m:'Mercato delle Pulci, Piazza dei Ciompi, Firenze', n:'Mercato delle Pulci', d:'El mercado de pulgas de Florencia, chico y permanente. Grabados, marcos, monedas y cosas raras.', t:'compra', p:'€'},
    {nota:1, n:'El aceite nuevo y qué traer', d:'La cosecha de aceituna es en noviembre, así que el olio nuovo recién prensado está justo en su momento: es verde, turbio y pica en la garganta, y no se parece al que llega a Uruguay.', t:'compra', tip:'Comprarlo en una almazara o en una cooperativa, no en el supermercado. Y ojo con el bolso de mano: es líquido, así que va en la valija despachada o no viaja.'}
  ]},
  {s:'Espectáculos de noviembre y diciembre', k:'evento', items:[
    {m:'Teatro del Maggio Musicale Fiorentino, Firenze', n:'Teatro del Maggio Musicale Fiorentino', d:'La ópera y la sinfónica de Florencia, en una sala moderna cerca del parque de las Cascine. Programación fuerte todo el invierno.', t:'evento', p:'€€', w:'https://www.maggiofiorentino.com/'},
    {m:'Teatro della Pergola, Firenze', n:'Teatro della Pergola', d:'De 1656 y considerado el primer teatro a la italiana del mundo, con los palcos en herradura. Teatro y conciertos de cámara.', t:'evento', p:'€€', w:'https://www.teatrodellapergola.com/'},
    {nota:1, n:'Dónde mirar la cartelera', d:'Los sitios de turismo de cada ciudad publican lo que pasa día por día, y las entradas de casi todo se venden por TicketOne. En invierno hay bastante música sacra gratis en las iglesias.', t:'evento', w:'https://www.destinationflorence.com/'}
  ]}
  ]
},
